namespace Pathway.Api;

public record CompetencyDefinition(string Id, string Title, string Description, string[] Evidence);
public record CapstoneRubricItem(string Id, string Title, string Requirement);
public record CapstoneDefinition(string Id, string CourseId, string Title, string Brief, string[] Outcomes, CapstoneRubricItem[] Rubric);
public record CareerScenario(string Id, string CourseId, string Type, string Title, string Prompt, string[] Deliverables, string[]? Evidence = null);
public record CapstoneReviewRequest(string? DemoUrl, string? ArchitectureUrl, string? RepositoryUrl, Dictionary<string, string>? Evidence);
public record CapstoneReviewResponse(bool ReadyForReview, int SatisfiedCriteria, int TotalCriteria, string[] MissingCriteria, string[] Feedback, string[] RecommendedReviewLessonSlugs);
public record CapstoneReviewRequestPost(string? DemoUrl, string? ArchitectureUrl, string? RepositoryUrl, Dictionary<string, string>? Evidence, string? ReviewFocus);
public record CompetencyEvidenceResponse(string Id, string Title, string Description, int EarnedEvidence, int TargetEvidence, string[] Evidence);
public record ScenarioReviewRequest(Dictionary<string, string>? Responses);
public record ScenarioReviewResponse(bool ReadyForFeedback, int SatisfiedDeliverables, int TotalDeliverables, string[] MissingDeliverables, string[] Feedback, string[] RecommendedReviewLessonSlugs);

public static class CareerReadinessCatalog
{
    public static readonly CompetencyDefinition[] Competencies =
    [
        new("programming", "Programming", "Solve problems with clear, correct, maintainable code.", ["Passes exercises", "Explains a design choice", "Completes a project requirement"]),
        new("testing", "Testing", "Proves behavior at the right boundary.", ["Writes unit tests", "Writes an integration test", "Explains an edge case"]),
        new("delivery", "Delivery", "Builds, deploys, and operates software safely.", ["CI workflow", "Deployment and rollback notes", "Health check or readiness signal"]),
        new("debugging", "Debugging", "Forms hypotheses from evidence and verifies a fix.", ["Reproduces a defect", "Uses logs, traces, or tests", "Writes a prevention step"]),
        new("collaboration", "Collaboration", "Communicates changes and gives useful feedback.", ["Writes a focused PR summary", "Leaves an actionable review", "Responds to review feedback"]),
        new("architecture", "Architecture", "Makes tradeoffs explicit and designs for ownership.", ["States constraints", "Writes an ADR", "Defines rollout and reversal signals"])
    ];

    private static CapstoneRubricItem[] Rubric =>
    [
        new("requirements", "Requirements", "State the user problem, constraints, assumptions, and acceptance criteria."),
        new("api", "API design", "Document success and failure contracts, validation, and compatibility decisions."),
        new("tests", "Tests", "Include focused unit tests and a boundary or integration test."),
        new("ci", "Continuous delivery", "Provide a CI workflow that builds and tests the project."),
        new("auth", "Security boundary", "Describe authentication, authorization, secrets, and abuse controls."),
        new("observability", "Observability", "Define structured logs, metrics/traces, health checks, and an actionable alert."),
        new("deployment", "Deployment", "Describe deploy, migration, rollback, and readiness steps."),
        new("readme", "README and runbook", "Explain local setup, the contract, operations, and recovery."),
        new("tradeoffs", "Tradeoffs", "Write an ADR that compares alternatives and revisit signals.")
    ];

    public static readonly CapstoneDefinition[] Capstones =
    [
        new("csharp-foundation-api", "csharp-dotnet", "Foundation API", "Build a small .NET API that solves a learner-facing problem and exposes a deliberate HTTP contract.", ["A deployed API", "Contract and integration tests", "A clear README"], Rubric),
        new("csharp-production-service", "csharp-dotnet", "Production service", "Evolve the API with persistence, authorization, cancellation, telemetry, and safe delivery.", ["Health and readiness signals", "CI workflow", "Deployment/runbook evidence"], Rubric),
        new("csharp-staff-platform", "csharp-dotnet", "Staff platform design", "Design the learning platform under scale, ownership, cost, and reliability constraints.", ["Architecture diagram", "ADR and rollout plan", "SLO and incident plan"], Rubric),
        new("python-foundation-api", "python-web", "Foundation API", "Build a typed Python web API with a focused domain boundary and an observable HTTP contract.", ["A deployed API", "Tests and API documentation", "A clear README"], Rubric),
        new("python-production-service", "python-web", "Production service", "Ship a Python service with persistence, authorization, background work, telemetry, and delivery discipline.", ["Health and readiness signals", "CI workflow", "Deployment/runbook evidence"], Rubric),
        new("python-staff-platform", "python-web", "Staff platform design", "Design a multi-tenant learning platform and make its tradeoffs, ownership, and recovery plan legible.", ["Architecture diagram", "ADR and rollout plan", "SLO and incident plan"], Rubric),
        new("rust-foundation-service", "rust-systems", "Foundation Rust service", "Build a small Axum service with explicit domain types, a deliberate HTTP contract, and tests.", ["Deployed service", "Contract and integration tests", "Clear README"], Rubric),
        new("rust-production-service", "rust-systems", "Production Rust service", "Ship a Rust service with persistence, authorization, bounded concurrency, tracing, and safe delivery.", ["Health and readiness signals", "CI workflow", "Deployment/runbook evidence"], Rubric),
        new("rust-staff-platform", "rust-systems", "Staff systems platform", "Design a multi-tenant Rust platform with explicit unsafe boundaries, ownership, reliability, and recovery tradeoffs.", ["Architecture diagram", "ADR and rollout plan", "SLO and incident plan"], Rubric),
        new("react-foundation-app", "react-enterprise", "Enterprise feature foundation", "Build a typed Vite/React application slice with route-owned data, accessible reusable UI, and behavior-focused tests.", ["Deployed SPA", "Component and network tests", "Clear architecture README"], Rubric),
        new("react-production-workflow", "react-enterprise", "Production business workflow", "Ship a business-critical React workflow with API boundaries, mutations, auth-aware UX, observability, performance evidence, and browser tests.", ["Critical Playwright journey", "Telemetry and failure states", "CI and deployment evidence"], Rubric),
        new("react-frontend-platform", "react-enterprise", "Frontend platform design", "Design a multi-team React frontend platform with feature boundaries, design-system ownership, dependency rules, upgrade policy, and measurable performance/accessibility standards.", ["Architecture diagram", "ADR and dependency policy", "Ownership, upgrade, and quality gates"], Rubric),
        new("react-lite-admin-dashboard", "react-lite", "First admin dashboard", "Build a responsive React admin dashboard with typed pages/components, a dummy async API wrapper, CRUD flows, routing, filtering, accessible forms, and basic tests.", ["Working dashboard", "Dummy API/service boundary", "Focused tests and README"], Rubric),
        new("sqlite-issue-tracker-db", "sqlite", "SQLite issue-tracker database", "Design and operate a production-minded SQLite database for a local issue tracker with constraints, transactions, indexes, query-plan evidence, backup/restore steps, and a DB Browser inspection walkthrough.", ["Schema and seed SQL", "Query-plan and integrity evidence", "Backup/restore and DB Browser walkthrough"], Rubric),
        new("linux-cli-support-bundle", "linux-cli-bash-vim", "Terminal support-bundle workflow", "Build and explain a terminal-only support workflow that safely gathers logs/configuration, summarizes failures, archives evidence, and uses Vim for targeted edits without breaking argument boundaries or permissions.", ["Executable Bash support-bundle script", "Sample archive and verification commands", "Vim editing walkthrough and README"], Rubric)
    ];

    public static readonly CareerScenario[] Scenarios =
    [
        new("incident-timeout", "csharp-dotnet", "Incident", "Checkout timeouts after a dependency release", "Investigate a rising p95 latency graph, a trace with a slow downstream call, and incomplete retry logs. Decide what to mitigate now and what to change safely.", ["Hypothesis and evidence", "Mitigation", "Blameless postmortem", "Prevention test or alert"], ["Dashboard: checkout p95 rose from 240 ms to 8.4 s at 10:04 UTC; error rate is 3.2%.", "Trace: POST /checkout spent 7.9 s in PaymentClient.AuthorizeAsync; the trace has no retry child span.", "Log: downstream status 504, attempt=1, correlation=9f7a. No cancellation or timeout value is recorded.", "Failing integration test: checkout returns 500 instead of a bounded 503 when PaymentClient exceeds its timeout."]),
        new("pr-order-validation", "csharp-dotnet", "Code review", "Review an order validation pull request", "Find correctness, authorization, resilience, readability, and test gaps. Write concise, actionable review comments and an approval summary.", ["Line-level findings", "Risk classification", "Approval criteria"], ["Diff note: the endpoint trusts request.CustomerId instead of the authenticated subject.", "Test note: only a happy-path unit test exists; no duplicate order or forbidden-user coverage.", "Performance note: each order line triggers a sequential SKU lookup inside a loop."]),
        new("ticket-slice-csharp", "csharp-dotnet", "Career", "Turn a vague ticket into a safe slice", "A product manager asks: ‘Let learners export their progress.’ Identify ambiguity, ask clarifying questions, estimate the smallest safe slice, and explain what you would defer.", ["Clarifying questions", "Smallest viable slice", "Estimate and assumptions", "Deferred risks"]),
        new("ai-review-csharp", "csharp-dotnet", "AI literacy", "Verify an AI-generated endpoint", "An AI suggests an endpoint that compiles but omits authorization, cancellation, tests, and failure semantics. Treat it as an untrusted draft: review, verify, and improve it.", ["Verification plan", "Missing correctness or security concerns", "Tests to add", "Explanation of the final design"]),
        new("team-migration-csharp", "csharp-dotnet", "Team simulation", "Negotiate a zero-downtime migration", "You are the staff engineer coordinating a schema change across two teams with a release deadline. Define the contract, sequencing, ownership, rollback, and ADR decision.", ["Stakeholder and ownership map", "Expand-contract rollout", "Rollback trigger", "ADR tradeoff"]),
        new("interview-csharp", "csharp-dotnet", "Career", "Explain a project under interview pressure", "Present a capstone to an interviewer who asks why you chose the architecture, what failed, how you tested it, and what you would improve with more time.", ["Two-minute project narrative", "Tradeoff explanation", "Failure and learning", "Next improvement"]),
        new("feedback-csharp", "csharp-dotnet", "Career", "Handle a difficult review conversation", "A teammate rejects your proposed caching approach after an incident. Acknowledge the feedback, distinguish facts from assumptions, propose a next experiment, and preserve a constructive working relationship.", ["Response that acknowledges feedback", "Evidence and assumptions", "Next experiment", "Follow-up communication"]),
        new("incident-worker-duplicates", "python-web", "Incident", "Duplicate notification delivery", "Use queue logs, duplicate delivery records, and a retry graph to identify why a background task produced duplicate effects.", ["Hypothesis and evidence", "Mitigation", "Blameless postmortem", "Idempotency change"], ["Queue dashboard: delivery attempts doubled after the worker deployment; queue depth remains flat.", "Log: event=notification.sent event_id=e-184 attempt=1 followed by the same event_id attempt=2 after an acknowledgement timeout.", "Trace: send_notification completes in 120 ms, but the worker acknowledges the message only after a 35 s database write.", "Failing test: processing the same event ID twice produces two outbound messages instead of one recorded effect."]),
        new("pr-enrollment-boundary", "python-web", "Code review", "Review an enrollment endpoint pull request", "Identify contract, authorization, transaction, test, and readability concerns before approving a change.", ["Line-level findings", "Risk classification", "Approval criteria"], ["Diff note: client-supplied learner_id is used without comparing it to the authenticated principal.", "Transaction note: enrollment creation and seat decrement are separate commits.", "Test note: no forbidden-user, full-class, or duplicate-enrollment coverage exists."]),
        new("ticket-slice-python", "python-web", "Career", "Turn a vague ticket into a safe slice", "A product manager asks: ‘Let learners export their progress.’ Identify ambiguity, ask clarifying questions, estimate the smallest safe slice, and explain what you would defer.", ["Clarifying questions", "Smallest viable slice", "Estimate and assumptions", "Deferred risks"]),
        new("ai-review-python", "python-web", "AI literacy", "Verify an AI-generated endpoint", "An AI suggests an endpoint that compiles but omits authorization, timeout policy, tests, and failure semantics. Treat it as an untrusted draft: review, verify, and improve it.", ["Verification plan", "Missing correctness or security concerns", "Tests to add", "Explanation of the final design"]),
        new("team-migration-python", "python-web", "Team simulation", "Negotiate a zero-downtime migration", "You are the staff engineer coordinating a schema change across two teams with a release deadline. Define the contract, sequencing, ownership, rollback, and ADR decision.", ["Stakeholder and ownership map", "Expand-contract rollout", "Rollback trigger", "ADR tradeoff"]),
        new("interview-python", "python-web", "Career", "Explain a project under interview pressure", "Present a capstone to an interviewer who asks why you chose the architecture, what failed, how you tested it, and what you would improve with more time.", ["Two-minute project narrative", "Tradeoff explanation", "Failure and learning", "Next improvement"]),
        new("feedback-python", "python-web", "Career", "Handle a difficult review conversation", "A teammate rejects your proposed caching approach after an incident. Acknowledge the feedback, distinguish facts from assumptions, propose a next experiment, and preserve a constructive working relationship.", ["Response that acknowledges feedback", "Evidence and assumptions", "Next experiment", "Follow-up communication"]),
        new("incident-rust-task-leak", "rust-systems", "Incident", "Runaway Rust task fan-out", "Use traces, task counts, and queue-delay signals to mitigate a service that spawns unbounded async work after a dependency slowdown.", ["Hypothesis and evidence", "Mitigation", "Blameless postmortem", "Bounded-concurrency prevention"], ["Dashboard: request p95 rose from 180 ms to 9.1 s and active Tokio tasks rose from 240 to 42,000.", "Trace: each request spawns a downstream task with no semaphore or timeout.", "Log: dependency status 504; cancellation count remains zero.", "Failing test: 1,000 requests create 1,000 concurrent downstream calls."]),
        new("pr-rust-boundary", "rust-systems", "Code review", "Review an unsafe parser boundary", "Review a Rust pull request that introduces unsafe parsing and a new HTTP handler. Identify soundness, authorization, test, and operational gaps.", ["Line-level findings", "Risk classification", "Approval criteria"], ["Diff note: unsafe pointer conversion has no SAFETY comment or safe wrapper.", "Authorization note: handler accepts an organization ID without checking the principal.", "Test note: no malformed-input, forbidden-user, or cancellation coverage exists."]),
        new("ticket-slice-rust", "rust-systems", "Career", "Turn a vague ticket into a safe Rust slice", "A product manager asks for offline export. Identify ambiguity, choose a minimal safe slice, and explain what you defer.", ["Clarifying questions", "Smallest viable slice", "Estimate and assumptions", "Deferred risks"]),
        new("ai-review-rust", "rust-systems", "AI literacy", "Verify an AI-generated Rust handler", "Treat an AI-generated handler as an untrusted draft that compiles but omits validation, cancellation, tests, and error semantics.", ["Verification plan", "Missing correctness or security concerns", "Tests to add", "Explanation of the final design"]),
        new("team-migration-rust", "rust-systems", "Team simulation", "Negotiate a zero-downtime event migration", "Coordinate a schema and event-contract change across Rust services with ownership, sequencing, rollback, and an ADR.", ["Stakeholder and ownership map", "Expand-contract rollout", "Rollback trigger", "ADR tradeoff"]),
        new("interview-rust", "rust-systems", "Career", "Explain a Rust project under interview pressure", "Present a capstone and explain architecture, ownership choices, testing, failures, and next improvements.", ["Two-minute project narrative", "Tradeoff explanation", "Failure and learning", "Next improvement"]),
        new("feedback-rust", "rust-systems", "Career", "Handle a difficult review conversation", "A teammate challenges an unsafe optimization. Acknowledge concerns, distinguish evidence from assumptions, and propose a safe next experiment.", ["Response that acknowledges feedback", "Evidence and assumptions", "Next experiment", "Follow-up communication"]),
        new("incident-react-render-storm", "react-enterprise", "Incident", "Order workspace becomes unresponsive after a release", "Use React Profiler evidence, browser timing, and API traces to distinguish excessive rendering from network latency and choose the smallest safe mitigation.", ["Hypothesis and evidence", "Immediate mitigation", "Profiler-backed fix", "Regression test"], ["Profiler: OrderGrid commits 96 times during one filter edit; most rows receive a new callback prop.", "Network: /api/orders remains 180 ms p95 before and after the release.", "Browser trace: main-thread scripting rises above 1.8 s while typing.", "Diff: a tenant-wide context provider now stores query text and recreates its value object on every keystroke."]),
        new("pr-react-boundaries", "react-enterprise", "Code review", "Review an enterprise React feature pull request", "Identify state ownership, accessibility, routing, API-boundary, testing, and dependency-direction issues before approving a feature.", ["Line-level findings", "Risk classification", "Approval criteria"], ["Diff note: OrdersPage fetches data in useEffect even though the route already owns orderId.", "Architecture note: components/ui imports a reducer from features/orders/internal.", "Accessibility note: a clickable div is used for the primary Approve action.", "Test note: the API client is mocked directly, so loading/error network behavior is never exercised."]),
        new("ticket-slice-react", "react-enterprise", "Career", "Turn a business workflow into a safe frontend slice", "Product asks for bulk order approval. Clarify permissions, failure behavior, selection persistence, URL semantics, accessibility, and the smallest production-safe increment.", ["Clarifying questions", "Smallest viable slice", "Estimate and assumptions", "Deferred risks"]),
        new("ai-review-react", "react-enterprise", "AI literacy", "Verify AI-generated React code", "An AI generates a plausible page with useEffect fetching, duplicated server state, missing cleanup, weak types, and inaccessible controls. Treat it as an untrusted draft and produce an evidence-backed correction plan.", ["Verification plan", "State and effect issues", "Accessibility and test gaps", "Final boundary design"]),
        new("team-design-system-react", "react-enterprise", "Team simulation", "Negotiate a shared design-system boundary", "Two product teams need similar tables and forms but have different business rules. Define what belongs in shared UI, what remains feature-owned, migration sequencing, and governance.", ["Ownership map", "Public component contract", "Migration plan", "ADR tradeoff"]),
        new("interview-react", "react-enterprise", "Career", "Explain an enterprise React architecture under interview pressure", "Present a feature and explain render/state ownership, routing, API contracts, accessibility, testing, performance evidence, and what you would change at greater scale.", ["Two-minute architecture narrative", "Tradeoff explanation", "Failure and learning", "Next improvement"]),
        new("feedback-react", "react-enterprise", "Career", "Handle a frontend architecture disagreement", "A teammate argues for one global store and a flat components folder. Acknowledge the concern, separate evidence from preference, and propose a small experiment that compares maintainability and render behavior.", ["Response that acknowledges feedback", "Evidence and assumptions", "Next experiment", "Follow-up communication"]),
        new("debug-react-lite", "react-lite", "Debugging", "A users page is blank after adding the dummy API wrapper", "Use the browser console, Network/route behavior, and component state to identify whether the failure is data loading, rendering, or filtering.", ["Evidence checked", "Likely cause", "Small fix", "Regression check"], ["Console: no JavaScript exception is present.", "usersApi.list resolves with three users.", "The query state defaults to the literal string 'undefined'.", "The table filters name/email using query before rendering."]),
        new("ticket-react-lite", "react-lite", "Career", "Add a user-status filter safely", "Turn a request for an Active/Disabled filter into a small change that preserves the API wrapper boundary and keeps filtering derived from loaded users.", ["UI change", "State location", "Derived filtering approach", "Test to add"]),
        new("review-react-lite", "react-lite", "Code review", "Review a beginner React dashboard change", "Identify a few high-impact issues without over-engineering the application.", ["Correctness finding", "React/web finding", "Accessibility finding", "Suggested fix"], ["Diff note: UserTable mutates the users prop with users.sort().", "Form note: email input has no label.", "Service note: a component imports seedUsers directly instead of calling usersApi.list()."]),
        new("incident-sqlite-busy", "sqlite", "Incident", "Investigate database is locked failures", "A desktop application intermittently reports SQLITE_BUSY while background sync is active. Use the transaction and WAL evidence to propose a bounded fix instead of retrying forever.", ["Likely lock owner", "Immediate mitigation", "Transaction change", "Verification plan"], ["Foreground log: SQLITE_BUSY while saving an issue.", "Background trace: sync opens a write transaction, performs HTTP work, then commits 14 seconds later.", "PRAGMA journal_mode returns WAL.", "busy_timeout is currently 0."]),
        new("review-sqlite-index", "sqlite", "Code review", "Review an index-everything migration", "A pull request adds indexes to almost every column in the issue database. Identify write-cost, redundancy, and query-plan concerns and propose evidence-based indexes.", ["Redundant indexes", "Queries to measure", "EXPLAIN QUERY PLAN evidence", "Migration recommendation"], ["Migration adds 17 new single-column indexes.", "Dashboard query filters project_id + status and orders created_at DESC.", "Write volume is high during sync.", "No EXPLAIN QUERY PLAN output is included."]),
        new("ticket-sqlite-migration", "sqlite", "Career", "Plan a safe SQLite schema migration", "Add a new issue priority field to a database already installed on thousands of desktops. Define compatibility, migration sequencing, defaults, backup/recovery, and verification.", ["Schema change", "Compatibility plan", "Backup/recovery", "Verification query"]),
        new("incident-linux-disk", "linux-cli-bash-vim", "Incident", "Investigate a suddenly full Linux filesystem", "Use terminal evidence to distinguish large files, deleted-but-open files, and runaway logs before deleting anything.", ["Inspection commands", "Likely cause", "Safe mitigation", "Verification"], ["df reports the root filesystem at 100%.", "du under /var/log accounts for only a small fraction of the missing space.", "A long-running process recently rotated a very large log file."]),
        new("review-bash-script", "linux-cli-bash-vim", "Code review", "Review a fragile deployment shell script", "Identify quoting, error-handling, permission, and destructive-path problems without turning a small Bash script into a framework.", ["High-risk lines", "Quoting/failure issues", "Safer replacement", "Verification steps"], ["The script uses rm -rf $WORK_DIR/* with an unvalidated variable.", "It loops over for file in $(find ...).", "It uses chmod 777 to fix a permission error.", "No trap cleans temporary state."])
    ];

    public static IEnumerable<CapstoneDefinition> CapstonesFor(string courseId) => Capstones.Where(item => item.CourseId == courseId);
    public static IEnumerable<CareerScenario> ScenariosFor(string courseId) => Scenarios.Where(item => item.CourseId == courseId);

    public static string[] RecommendedLessons(string courseId, IEnumerable<string> gaps)
    {
        var isPython = courseId == "python-web";
        var isRust = courseId == "rust-systems";
        var isReact = courseId == "react-enterprise";
        var isReactLite = courseId == "react-lite";
        var isSqlite = courseId == "sqlite";
        var isLinux = courseId == "linux-cli-bash-vim";
        var matches = new List<string>();
        foreach (var gap in gaps)
        {
            var lesson = gap.ToLowerInvariant() switch
            {
                var value when value.Contains("auth") => isReact ? "react-auth-security" : isRust ? "rust-auth-security" : isPython ? "python-auth-security" : "web-api-validation-auth",
                var value when value.Contains("test") => isLinux ? "bash-safe-scripting" : isSqlite ? "sqlite-integrity-maintenance" : isReactLite ? "react-lite-basic-testing" : isReact ? "react-testing-vitest-rtl" : isRust ? "rust-testing-integration" : isPython ? "python-testing-pytest" : "quality-tests",
                var value when value.Contains("observ") || value.Contains("alert") || value.Contains("incident") => isLinux ? "linux-processes-jobs" : isSqlite ? "sqlite-wal-locking" : isReactLite ? "react-lite-loading-errors-empty" : isReact ? "react-observability-errors" : isRust ? "rust-observability" : isPython ? "python-reliability-design" : "operations-observability",
                var value when value.Contains("deploy") || value.Contains("rollback") || value.Contains("migration") => isLinux ? "bash-safe-scripting" : isSqlite ? "sqlite-schema-migrations" : isReact ? "react-delivery-env-upgrades" : isRust ? "rust-containers-delivery" : isPython ? "python-delivery-containers" : "operations-delivery",
                var value when value.Contains("tradeoff") || value.Contains("adr") || value.Contains("approval") => isLinux ? "linux-shell-terminal" : isSqlite ? "sqlite-what-it-is" : isReact ? "react-feature-architecture" : isRust ? "rust-staff-architecture" : isPython ? "python-system-design" : "staff-architecture-decisions",
                var value when value.Contains("api") || value.Contains("contract") => isSqlite ? "sqlite-parameters" : isReactLite ? "react-lite-dummy-api-read" : isReact ? "react-api-client-boundary" : isRust ? "rust-api-contracts" : isPython ? "python-api-contracts" : "web-api-contracts",
                _ => isLinux ? "linux-paths-navigation" : isSqlite ? "sqlite-open-inspect" : isReactLite ? "react-lite-folder-structure" : isReact ? "react-enterprise-folders" : isRust ? "rust-toolchain-cargo" : isPython ? "python-project-foundations" : "foundations-methods"
            };
            matches.Add(lesson);
        }
        return matches.Distinct(StringComparer.Ordinal).Take(3).ToArray();
    }
}
