static partial class Curriculum
{
    private static readonly VersionStamp GitCliDocs = new(
        "Git",
        "CLI",
        "2026-09-26",
        "https://git-scm.com/docs");

    private static Exercise GitExercise(
        string title,
        string prompt,
        string starter,
        string hint,
        params string[] tests) =>
        new(
            ExerciseKind.Code,
            title,
            prompt,
            [
                "Write Git CLI commands that satisfy the task",
                "Your commands run inside a disposable, network-isolated repository",
                "The sandbox verifies repository state after your commands finish"
            ],
            starter,
            null,
            [],
            hint,
            tests);

    public static readonly Lesson[] GitCliLessons = NormalizeLessons(
    [
        new(
            "git-init-status",
            "Git foundations",
            1,
            "Create a repository and read its state",
            "Git is a version-control system: it records meaningful snapshots of files so you can inspect and combine changes over time. A repository is a project directory plus Git's stored history and bookkeeping data (metadata). Your working tree is the editable files you currently see.",
            "git init creates Git's .git metadata directory. git status compares three states: the working tree (files you are editing), the index or staging area (the proposed next snapshot), and the current commit (the snapshot your checked-out history currently points to).",
            "A Git repository is ordinary files plus metadata stored under .git. The working tree is what you can edit. The index, also called the staging area, is the proposed contents of the next commit. git status is the safest first command when you are unsure what state you are in.",
            "git init\ngit status --short",
            GitExercise(
                "Initialize the repository",
                "Initialize the prepared directory as a Git repository, then inspect its short status. README.md should remain untracked.",
                "# Initialize the repository, then inspect it\n",
                "Use git init first, then ask Git for a concise status.",
                "Repository metadata exists",
                "git status succeeds",
                "README.md remains visible as untracked"),
            null,
            GitCliDocs),
        new(
            "git-stage-files",
            "Git foundations",
            2,
            "Stage exactly what belongs in the next commit",
            "Staging is an explicit review boundary, not a synonym for saving a file.",
            "git add copies selected working-tree content into the index so the next commit can include it.",
            "A file can be untracked, modified but unstaged, or staged. This separation lets you build a focused commit from only the changes that belong together. git status --short uses two columns to show index state and working-tree state.",
            "git add README.md\ngit status --short",
            GitExercise(
                "Stage one file",
                "Stage README.md but leave notes.txt untracked. Inspect the short status afterward.",
                "# Stage only README.md; leave notes.txt alone\n",
                "Use git add with the specific path instead of staging everything.",
                "README.md is staged",
                "notes.txt is not staged",
                "notes.txt remains untracked"),
            null,
            GitCliDocs),
        new(
            "git-first-commit",
            "Git foundations",
            3,
            "Commit a coherent snapshot",
            "A commit is a saved project snapshot plus identifying information and a message. Most commits also record a parent: the earlier commit they follow, which is how Git builds history.",
            "git commit records the staged snapshot; a useful message describes the intent of that snapshot.",
            "Commits form a graph. Each normal commit points to a parent commit and records a tree of file contents. Git does not commit whatever happens to be in your editor; it commits what is staged in the index.",
            "git add README.md\ngit commit -m \"Add project README\"",
            GitExercise(
                "Create the first commit",
                "Commit the staged README.md with a non-empty commit message and leave the working tree clean.",
                "# README.md is already staged\n# Create the repository's first commit\n",
                "Use git commit with a concise message.",
                "HEAD points to a commit",
                "README.md is tracked by that commit",
                "The working tree is clean"),
            null,
            GitCliDocs),
        new(
            "git-history-diff",
            "Git foundations",
            4,
            "Inspect history and unstaged changes",
            "Before changing history, read it.",
            "git log shows commit history; git diff shows content changes that have not been staged.",
            "Inspection commands are low-risk and should be habitual. git log --oneline gives a compact history. git diff compares the working tree to the index, while git diff --staged compares the index to HEAD.",
            "git log --oneline -2\ngit diff --name-only",
            GitExercise(
                "Read the repository",
                "Print the two most recent commits in one-line form and print the name of the currently modified file with git diff --name-only.",
                "# Inspect history and the current unstaged change\n",
                "Use git log --oneline with a limit, then git diff --name-only.",
                "Output includes both recent commit subjects",
                "Output identifies notes.txt as modified"),
            null,
            GitCliDocs),

        new(
            "git-switch-branch",
            "Branching and merging",
            5,
            "Create and switch branches",
            "A branch is a movable name pointing at a commit.",
            "git switch -c creates a branch at the current commit and checks it out.",
            "Branches are cheap references. Creating a branch does not duplicate the repository. HEAD normally points to the currently checked-out branch, and new commits advance that branch reference.",
            "git switch -c feature/navigation",
            GitExercise(
                "Start a feature branch",
                "Create and switch to a branch named feature/navigation.",
                "# Create the requested feature branch and switch to it\n",
                "git switch can create and select a branch in one command.",
                "Current branch is feature/navigation",
                "The branch starts from main"),
            null,
            GitCliDocs),
        new(
            "git-feature-commit",
            "Branching and merging",
            6,
            "Commit work on a feature branch",
            "A branch becomes useful when its commits can diverge safely from main.",
            "Make the change, stage it, and commit it on the feature branch while main remains unchanged.",
            "The same working-tree and staging rules apply on every branch. A focused feature branch usually contains commits that represent one coherent line of work and can be reviewed or integrated independently.",
            "printf '\\nHello from the feature branch\\n' >> app.txt\ngit add app.txt\ngit commit -m \"Add greeting\"",
            GitExercise(
                "Record feature work",
                "On the already checked-out feature/greeting branch, append the requested greeting to app.txt, stage it, and commit it.",
                "# Append exactly this line to app.txt: Hello from the feature branch\n# Then stage and commit the change\n",
                "Use shell redirection for the file edit, then git add and git commit.",
                "feature/greeting has a new commit",
                "app.txt contains the greeting",
                "main still points to the original commit"),
            null,
            GitCliDocs),
        new(
            "git-merge-feature",
            "Branching and merging",
            7,
            "Merge a completed branch",
            "Merging combines reachable history and moves the current branch forward to include the feature.",
            "git merge integrates another branch into the branch currently checked out.",
            "If main has not moved since the feature branch was created, Git can fast-forward main. If both sides have new commits, Git may create a merge commit. In both cases, inspect status and history before and after integration.",
            "git merge feature/readme",
            GitExercise(
                "Merge the feature",
                "Merge feature/readme into the currently checked-out main branch.",
                "# Integrate feature/readme into main\n",
                "Run git merge while main is checked out.",
                "The feature commit is reachable from main",
                "README.md contains the feature content",
                "The working tree is clean"),
            null,
            GitCliDocs),
        new(
            "git-resolve-conflict",
            "Branching and merging",
            8,
            "Resolve a merge conflict deliberately",
            "A conflict means Git cannot choose the intended content for you.",
            "Resolve conflicts by editing the file to the intended result, staging the resolution, and completing the merge.",
            "When both branches change overlapping lines, git merge stops and leaves conflict markers in the working tree. Do not blindly accept one side. Understand the intended result, edit the file, git add the resolved version, and commit the merge.",
            "git merge feature/theme || true\nprintf 'theme=purple\\nfont=mono\\n' > settings.txt\ngit add settings.txt\ngit commit -m \"Merge feature/theme\"",
            GitExercise(
                "Resolve the conflict",
                "Merge feature/theme. Resolve settings.txt so it contains exactly theme=purple and font=mono on separate lines, then finish the merge.",
                "# The merge is expected to report a conflict\n# Resolve settings.txt to the required final content, stage it, and complete the merge\n",
                "Allow the conflicted merge to stop, edit the file, git add it, then git commit.",
                "No unmerged paths remain",
                "settings.txt has the required combined content",
                "HEAD is a merge commit"),
            null,
            GitCliDocs),

        new(
            "git-restore-reset",
            "Collaboration and recovery",
            9,
            "Undo local staging and working-tree mistakes",
            "Use the narrowest recovery command that matches the state you want to change.",
            "git restore changes working-tree or index state without rewriting published history.",
            "git restore file discards an unstaged working-tree change by restoring from the index. git restore --staged file removes a path from the index while preserving the working-tree edit. These are different operations; status tells you which state you are changing.",
            "git restore app.txt\ngit restore --staged notes.txt",
            GitExercise(
                "Repair local state",
                "Discard the unstaged change to app.txt and unstage notes.txt without deleting the notes.txt edit.",
                "# Restore app.txt in the working tree\n# Unstage notes.txt but keep its edited contents\n",
                "Use git restore for the working tree and git restore --staged for the index.",
                "app.txt matches HEAD",
                "notes.txt is no longer staged",
                "notes.txt remains modified in the working tree"),
            null,
            GitCliDocs),
        new(
            "git-ignore-generated-files",
            "Collaboration and recovery",
            10,
            "Ignore files that do not belong in history",
            "Version control should contain source-of-truth project files, not secrets or generated noise.",
            ".gitignore patterns keep matching untracked files out of normal status and staging workflows.",
            "Ignore rules are repository policy, not a security boundary. Never commit real secrets, even if you later add them to .gitignore. Common candidates include local environment files, generated build output, caches, and logs.",
            "printf '.env\\n*.log\\n' > .gitignore\ngit add .gitignore src.txt",
            GitExercise(
                "Create ignore rules",
                "Create .gitignore rules for .env and all .log files. Stage .gitignore and src.txt while leaving the ignored files out of the index.",
                "# Create the two ignore patterns, then stage .gitignore and src.txt\n",
                "Put one ignore pattern per line, then stage only the project files that belong in history.",
                ".env is ignored",
                "app.log is ignored",
                ".gitignore and src.txt are staged"),
            null,
            GitCliDocs),
        new(
            "git-fetch-remote",
            "Collaboration and recovery",
            11,
            "Fetch before integrating remote work",
            "Fetching updates remote-tracking references without changing your checked-out branch.",
            "git fetch origin downloads remote references and objects; it does not merge them into your current branch.",
            "A local branch such as main and a remote-tracking reference such as origin/main are different refs. Fetch first when you want to inspect what changed before choosing whether to merge, rebase, or do nothing.",
            "git fetch origin\ngit log --oneline main..origin/main",
            GitExercise(
                "Fetch a newer remote commit",
                "Fetch origin so origin/main advances to the newer commit that exists in the prepared local remote. Do not merge it into local main.",
                "# Update remote-tracking references without changing local main\n",
                "Use git fetch origin. A fetch alone should not move your local main branch.",
                "origin/main matches the remote's main",
                "local main remains behind",
                "The working tree is unchanged"),
            null,
            GitCliDocs),
        new(
            "git-rebase-feature",
            "Collaboration and recovery",
            12,
            "Rebase a private feature branch onto updated main",
            "Rebase rewrites private branch commits onto a new base to create a linear history.",
            "git rebase main replays the current branch's unique commits on top of main.",
            "Rebase changes commit identities, so it is best used on unpublished or coordinated private work. Do not casually rebase commits other people may already be building on. Inspect the graph before and after.",
            "git rebase main",
            GitExercise(
                "Rebase the feature",
                "Rebase the currently checked-out feature/search branch onto main.",
                "# Replay this private feature branch on top of main\n",
                "Run git rebase main while feature/search is checked out.",
                "main is now an ancestor of feature/search",
                "The feature change is preserved",
                "History is linear"),
            null,
            GitCliDocs),
        new(
            "git-revert-push",
            "Collaboration and recovery",
            13,
            "Undo published work safely and push the repair",
            "Shared history is usually repaired with a new commit rather than rewritten.",
            "git revert creates a new commit that inverses an earlier commit; git push publishes the new history.",
            "When a bad commit has already been shared, resetting and force-pushing can invalidate other people's work. Revert records the correction explicitly. In this sandbox, origin is a local bare repository so you can practice the full workflow without network access.",
            "git revert --no-edit HEAD\ngit push origin main",
            GitExercise(
                "Revert and publish",
                "Revert the bad commit at HEAD without rewriting history, then push main to origin.",
                "# Create a revert commit for HEAD, then publish main\n",
                "Use git revert for shared history, then git push origin main.",
                "A new revert commit exists",
                "The bad file change is undone",
                "origin/main matches local main"),
            null,
            GitCliDocs)
    ]);
}
