static partial class Curriculum
{
    private static readonly VersionStamp KubernetesDocs = new(
        "Kubernetes 1.35",
        "kubectl · containerd · CNI · CSI",
        "2026-09-26",
        "https://kubernetes.io/docs/");

    private static Exercise KubeChoice(string title, string prompt, string correct, Choice[] choices, string hint, params string[] tests) =>
        new(ExerciseKind.MultipleChoice, title, prompt, ["Choose the best answer"], null, correct, choices, hint, tests);

    private static Exercise KubeCode(string title, string prompt, string starter, string hint, params string[] tests) =>
        new(ExerciseKind.Code, title, prompt,
            ["Write Kubernetes YAML or kubectl commands that satisfy the requested state",
             "Prefer declarative configuration when the desired state should be reproducible",
             "The evaluator checks important object fields and command intent"],
            starter, null, [], hint, tests);

    private static Lesson KubePresentation(string slug, string module, int order, string title, string concept, string explanation, string practice, string example) =>
        new(slug, module, order, title, concept, explanation, practice, example,
            new Exercise(ExerciseKind.Presentation, "Architecture check", "Explain the lesson model in your own words before continuing.",
                ["Name the important components", "Describe the flow of state or traffic", "Identify one failure mode"], null, null, [],
                "Re-read the model and make sure each new term has a concrete job.", []), null, KubernetesDocs);

    public static Lesson[] BuildKubernetesLessons() => NormalizeLessons(
    [
        new("k8s-why-orchestration", "Foundations", 1, "Why container orchestration exists",
            "A container packages an application process with the user-space files it needs; orchestration coordinates many containers across machines.",
            "A container is not a tiny virtual machine. Containers normally share the host Linux kernel while isolation features separate processes, filesystems, networking, and resource usage. Once applications span machines, operators need repeatable placement, restart, networking, rollout, and scaling behavior. Kubernetes is a system for declaring that desired state and continuously working toward it.",
            "Keep the problem separate from the product: first understand why fleets of containers need scheduling and recovery, then learn how Kubernetes supplies those capabilities.",
            "application → container image → container runtime → host kernel",
            KubeChoice("Identify orchestration", "Which problem is Kubernetes primarily adding above a container runtime?", "orchestration",
                [new("orchestration", "Coordinate desired application state across a fleet of machines"), new("compile", "Compile application source code"), new("kernel", "Replace the Linux kernel")],
                "A runtime starts containers; an orchestrator coordinates them across machines.", "Separates containers from orchestration"), null, KubernetesDocs),

        new("k8s-linux-container-prereqs", "Foundations", 2, "Linux isolation and container runtimes",
            "Linux namespaces isolate what processes can see; cgroups account for and limit resources; a container runtime creates and manages containers.",
            "A namespace here is a Linux kernel isolation mechanism, not yet a Kubernetes Namespace. PID, network, mount, and other namespaces give processes separate views of system resources. Control groups (cgroups) organize processes for CPU, memory, and other resource accounting or limits. Kubernetes does not implement containers itself: the kubelet asks a CRI-compatible container runtime such as containerd to do that work.",
            "When debugging a container problem, distinguish Kubernetes desired state from runtime behavior and from the underlying kernel mechanisms.",
            "kubelet → CRI → containerd → Linux namespaces + cgroups",
            KubeChoice("Place the runtime", "What directly creates the Linux container after the kubelet requests it?", "runtime",
                [new("runtime", "A container runtime such as containerd"), new("dns", "CoreDNS"), new("scheduler", "The scheduler")],
                "The kubelet manages node workload state and delegates container lifecycle through CRI.", "Defines runtime boundary"), null, KubernetesDocs),

        new("k8s-images-registries", "Foundations", 3, "Images, registries, tags, and digests",
            "A container image is an immutable packaged filesystem plus metadata; a registry stores and distributes images.",
            "An image reference can use a tag such as :1.4 or an immutable content digest such as @sha256:.... Tags are human-friendly pointers and may move; digests identify exact content. Nodes pull images from registries before runtimes can create containers.",
            "Use meaningful immutable release tags or digests for production deployments. Avoid relying on :latest when reproducibility matters.",
            "registry.example.com/orders:1.4\nregistry.example.com/orders@sha256:<digest>",
            KubeChoice("Choose reproducibility", "Which image reference most precisely identifies exact image content?", "digest",
                [new("digest", "A sha256 digest"), new("latest", "The latest tag"), new("pod", "The Pod name")],
                "A digest is content-addressed.", "Distinguishes tags and digests"), null, KubernetesDocs),

        new("k8s-network-storage-prereqs", "Foundations", 4, "Networking and storage vocabulary",
            "IP addresses identify network interfaces, ports identify endpoints on a host, DNS maps names to records, and persistent storage outlives an individual process.",
            "Kubernetes networking builds on ordinary IP networking. A process listens on a port; clients connect to an address and port; DNS provides names that can resolve to addresses. Storage has a separate lifetime question: container writable layers are ephemeral, while persistent application data needs storage whose lifecycle is not tied to one container.",
            "Before blaming Kubernetes networking, identify the client, destination name/IP, destination port, protocol, and where name resolution occurs.",
            "client → DNS → IP:port → server process\ncontainer lifecycle ≠ persistent data lifecycle",
            KubeChoice("Separate identities", "What does DNS primarily provide?", "names",
                [new("names", "Name-to-record resolution"), new("storage", "Persistent block storage"), new("cpu", "CPU scheduling")],
                "DNS lets clients use names instead of hard-coded addresses.", "Defines networking prerequisites"), null, KubernetesDocs),

        new("k8s-yaml-api-objects", "Core model", 5, "YAML and Kubernetes API objects",
            "YAML is a data serialization format; Kubernetes manifests use it to describe API objects.",
            "A manifest commonly contains apiVersion, kind, metadata, and spec. kind names the object type, metadata carries identity such as name and labels, and spec describes desired state. The API server validates requests and stores accepted persistent cluster state.",
            "Treat YAML as structured data, not magic Kubernetes syntax. Indentation changes structure; use kubectl explain and server-side validation to inspect schemas.",
            "apiVersion: v1\nkind: Pod\nmetadata:\n  name: demo\nspec:\n  containers:\n    - name: app\n      image: nginx:1.29",
            KubeCode("Write a Pod manifest", "Define a Pod named web with one container named web using nginx:1.29.", "apiVersion: v1\nkind: Pod\n", "Include metadata.name and spec.containers with a name and image.", "Pod is named web", "container is named web", "image is nginx:1.29"), null, KubernetesDocs),

        new("k8s-cluster-architecture", "Core model", 6, "Cluster, control plane, and worker nodes",
            "A Kubernetes cluster is a control plane plus worker nodes; the control plane manages cluster state while workers run application workloads.",
            "The API server is the front door to the Kubernetes API. etcd is the strongly consistent key-value store used for persistent cluster state. The scheduler chooses nodes for unscheduled Pods. Controller managers run control loops. On each worker, kubelet drives Pod state and the container runtime manages containers.",
            "Do not memorize a component diagram without tracing state: client request → API server → stored desired state → controllers/scheduler → kubelet/runtime → observed state.",
            "kubectl → kube-apiserver ↔ etcd\n                    ↓\ncontrollers + scheduler\n                    ↓\nkubelet → runtime",
            KubeChoice("Locate persistent state", "Which control-plane component stores Kubernetes cluster state?", "etcd",
                [new("etcd", "etcd"), new("kubelet", "kubelet"), new("coredns", "CoreDNS")],
                "The API server is the API boundary; etcd is its backing state store.", "Maps control-plane responsibilities"), null, KubernetesDocs),

        new("k8s-declarative-reconciliation", "Core model", 7, "Desired state and reconciliation",
            "A reconciliation loop repeatedly compares desired state with observed state and acts to reduce the difference.",
            "Kubernetes is declarative: you normally describe what should be true rather than scripting every step to make it true. Controllers watch API objects and reconcile them. This explains self-healing, asynchronous status changes, and why deleting a managed Pod may cause another Pod to appear.",
            "Debug controllers by comparing spec, status, events, and the owning resource. Ask which controller is responsible for making this object true.",
            "desired replicas: 3\nobserved ready: 2\ncontroller action: create/replace until desired state is approached",
            KubeChoice("Reason about replacement", "Why can a deleted Pod immediately be replaced?", "controller",
                [new("controller", "A controller is reconciling a higher-level desired replica count"), new("yaml", "YAML automatically starts processes"), new("dns", "DNS recreates Pods")],
                "Managed objects are part of a larger desired state.", "Understands reconciliation"), null, KubernetesDocs),

        new("k8s-kubectl-contexts", "Core model", 8, "kubectl, kubeconfig, contexts, and namespaces",
            "kubectl is a Kubernetes API client; kubeconfig stores connection and identity configuration; a context selects a cluster, user, and default Kubernetes Namespace.",
            "A Kubernetes Namespace is an API-level scope for grouping many namespaced objects; it is different from a Linux namespace. kubectl reads kubeconfig, selects a context, authenticates to the API server, and sends API requests. The current context is operationally important because the same command can target a different cluster.",
            "Before destructive commands, verify kubectl config current-context and the target Namespace. Prefer explicit -n for important operations.",
            "kubectl config current-context\nkubectl get namespaces\nkubectl get pods -n default",
            KubeCode("Inspect the target", "Write commands that print the current context and list Pods in Namespace payments.", "kubectl ", "Use kubectl config current-context and kubectl get pods -n payments.", "checks context", "targets payments namespace"), null, KubernetesDocs),

        new("k8s-pods", "Workloads", 9, "Pods and multi-container cooperation",
            "A Pod is Kubernetes' smallest schedulable workload unit and contains one or more tightly coupled containers sharing a network identity and selected storage.",
            "Containers in one Pod are placed together on one node and can communicate over localhost. Pods are intended to be replaceable. Put containers together only when they truly share a lifecycle and need close cooperation, such as an application plus a sidecar helper.",
            "Do not treat a Pod as a durable server identity. Higher-level workload controllers create and replace Pods.",
            "Pod\n├─ app container :8080\n└─ helper container\n   shared network: localhost\n   shared volumes: when configured",
            KubeChoice("Choose a Pod boundary", "Which pair most plausibly belongs in one Pod?", "sidecar",
                [new("sidecar", "An application and a helper that must share its lifecycle and localhost"), new("services", "Two independently deployed business services"), new("databases", "Every database in the company")],
                "A Pod is a tight lifecycle boundary.", "Uses Pod boundaries deliberately"), null, KubernetesDocs),

        new("k8s-labels-selectors", "Workloads", 10, "Labels, selectors, and annotations",
            "Labels are indexed identifying metadata used for grouping and selection; selectors query labels; annotations hold non-identifying metadata.",
            "Controllers and Services often use selectors to discover Pods. A label such as app: orders can participate in selection. An annotation can hold tooling or descriptive metadata that should not define membership.",
            "Design a small stable label vocabulary. Selector changes can disconnect a controller or Service from its intended Pods.",
            "metadata:\n  labels:\n    app: orders\n    tier: api\n  annotations:\n    owner.example.com/team: commerce",
            KubeCode("Label a Pod", "Define metadata for a Pod named orders with labels app=orders and tier=api.", "metadata:\n", "Use metadata.name and metadata.labels.", "name is orders", "app label exists", "tier label exists"), null, KubernetesDocs),

        new("k8s-deployments-replicasets", "Workloads", 11, "Deployments, ReplicaSets, and rolling updates",
            "A Deployment declares rollout and replica intent for stateless Pods; it manages ReplicaSets, which maintain matching Pod replicas.",
            "The Deployment controller creates ReplicaSets and changes them during rollouts. A ReplicaSet maintains a desired number of matching Pods. Updating the Pod template creates a new rollout rather than editing existing Pods in place.",
            "Operate the Deployment, not its generated ReplicaSet or Pods, unless debugging. Inspect rollout status and history when releases fail.",
            "Deployment → ReplicaSet → Pods\nkubectl rollout status deployment/orders",
            KubeCode("Deploy a stateless API", "Create a Deployment named orders with 3 replicas running ghcr.io/example/orders:2.0 and label/select app=orders.", "apiVersion: apps/v1\nkind: Deployment\n", "The selector must match the Pod template labels.", "Deployment named orders", "replicas is 3", "selector matches template", "image is versioned"), null, KubernetesDocs),

        new("k8s-services", "Networking", 12, "Services and stable virtual endpoints",
            "A Service gives a changing set of backend Pods a stable network endpoint selected by labels.",
            "Pods are replaceable and their IP addresses can change. A Service selects endpoints and provides a stable name and virtual IP inside the cluster. ClusterIP is the default internal Service type. targetPort is the backend port; port is the Service-facing port.",
            "If a Service has no working backends, inspect its selector, EndpointSlices, Pod readiness, and targetPort before changing network infrastructure.",
            "client → orders Service :80 → ready Pod endpoints :8080",
            KubeCode("Expose a Deployment", "Create a ClusterIP Service named orders selecting app=orders, serving port 80 and forwarding to container port 8080.", "apiVersion: v1\nkind: Service\n", "Set spec.selector.app, port, and targetPort.", "selects orders", "port 80", "targetPort 8080"), null, KubernetesDocs),

        new("k8s-dns-discovery", "Networking", 13, "Cluster DNS and service discovery",
            "Service discovery is the process of finding a service endpoint; Kubernetes commonly provides it through DNS records maintained for cluster objects.",
            "CoreDNS is a common cluster DNS implementation. A Pod can usually resolve a Service by short name in the same Namespace or by a fully qualified cluster DNS name such as orders.payments.svc.cluster.local. DNS resolution and Service routing are separate steps.",
            "When a name fails, test DNS resolution separately from TCP/HTTP connectivity to the resolved Service.",
            "orders\norders.payments\norders.payments.svc.cluster.local",
            KubeChoice("Separate DNS from routing", "If a Service name does not resolve at all, which layer should you inspect first?", "dns",
                [new("dns", "Cluster DNS configuration and records"), new("scheduler", "Pod scheduling score plugins"), new("storage", "StorageClass reclaim policy")],
                "Resolution happens before connecting to the Service address.", "Separates discovery from routing"), null, KubernetesDocs),

        new("k8s-config-secrets", "Application configuration", 14, "ConfigMaps and Secrets",
            "A ConfigMap stores non-confidential configuration; a Secret is a Kubernetes API object intended for sensitive values but requires proper cluster security to remain confidential.",
            "Both can be exposed to Pods as environment variables or mounted files. Secret data being base64-encoded is not encryption. Encryption at rest, RBAC, external secret systems, and careful logging may all matter for real confidentiality.",
            "Keep configuration outside immutable images when it varies by environment. Do not commit real credentials to manifests.",
            "envFrom:\n  - configMapRef:\n      name: orders-config\n  - secretRef:\n      name: orders-secrets",
            KubeChoice("Understand Secrets", "What does base64 encoding of a Secret provide by itself?", "encoding",
                [new("encoding", "Encoding, not encryption"), new("encryption", "Strong encryption"), new("rbac", "Authorization")],
                "Base64 is reversible representation.", "Avoids Secret misconception"), null, KubernetesDocs),

        new("k8s-health-probes", "Application configuration", 15, "Startup, readiness, and liveness probes",
            "A startup probe protects slow startup, a readiness probe controls whether a Pod receives Service traffic, and a liveness probe can trigger container restart.",
            "Readiness answers 'can this instance serve traffic now?' Liveness answers 'should this container be restarted?' Startup probes delay the other probe semantics until startup succeeds. Poor liveness checks can turn dependency outages into restart storms.",
            "Make readiness sensitive to serving ability, but keep liveness focused on whether the process can recover only through restart.",
            "startupProbe → startup gate\nreadinessProbe → traffic eligibility\nlivenessProbe → restart decision",
            KubeChoice("Drain traffic", "Which probe should fail when an instance temporarily cannot serve requests but should not be restarted?", "readiness",
                [new("readiness", "Readiness probe"), new("liveness", "Liveness probe"), new("startup", "Startup probe after normal operation")],
                "Readiness removes an endpoint from normal Service traffic.", "Distinguishes probe semantics"), null, KubernetesDocs),

        new("k8s-resources-qos", "Scheduling", 16, "CPU, memory, requests, limits, and QoS",
            "A resource request expresses scheduling needs; a limit constrains allowed resource usage; CPU and memory behave differently when limits are reached.",
            "The scheduler uses requests when deciding whether a node has capacity. CPU limits can throttle CPU time. Exceeding a memory limit can lead to an out-of-memory kill. Kubernetes derives QoS classes from resource configuration, which influences eviction behavior.",
            "Measure workloads before choosing values. Missing requests make scheduling capacity misleading; unrealistic limits can create throttling or OOM failures.",
            "resources:\n  requests:\n    cpu: 250m\n    memory: 256Mi\n  limits:\n    memory: 512Mi",
            KubeCode("Declare resources", "Write a container resources block requesting 250m CPU and 256Mi memory with a 512Mi memory limit.", "resources:\n", "Use requests and limits with Kubernetes quantity syntax.", "cpu request", "memory request", "memory limit"), null, KubernetesDocs),

        new("k8s-scheduling-placement", "Scheduling", 17, "Scheduling, taints, tolerations, affinity, and topology",
            "Scheduling assigns an unscheduled Pod to a node; placement constraints filter or prefer where that assignment may occur.",
            "nodeSelector is a simple label requirement. Node affinity expresses richer node preferences/requirements. Pod affinity and anti-affinity relate placement to other Pods. A taint repels Pods unless they have a matching toleration; toleration permits scheduling but does not force it. Topology spread constraints distribute replicas across topology domains such as zones.",
            "Use the least complex placement rule that expresses the requirement. Separate hard requirements from preferences.",
            "taint on node: dedicated=gpu:NoSchedule\nmatching toleration: Pod may be considered there\naffinity: attraction/requirement rules",
            KubeChoice("Interpret toleration", "What does a matching toleration guarantee?", "permit",
                [new("permit", "It permits the Pod to tolerate that taint; other scheduling rules still apply"), new("force", "It forces the Pod onto that node"), new("network", "It opens a network port")],
                "Tolerations remove a repelling condition; they are not attraction.", "Understands placement semantics"), null, KubernetesDocs),

        new("k8s-jobs-cronjobs", "Workloads", 18, "Jobs, CronJobs, DaemonSets, and StatefulSets",
            "Different workload controllers encode different lifecycle guarantees: Jobs complete work, CronJobs schedule Jobs, DaemonSets place Pods across selected nodes, and StatefulSets preserve ordered identities.",
            "Use a Job for finite work and a CronJob for recurring finite work. DaemonSets suit node-local agents such as log collectors. StatefulSets provide stable ordinal identities and ordered management useful for some stateful systems, often alongside persistent volumes.",
            "Choose a controller from workload lifecycle requirements, not from familiarity.",
            "Deployment: replaceable replicas\nJob: run to completion\nCronJob: scheduled Jobs\nDaemonSet: node-oriented replicas\nStatefulSet: stable identities",
            KubeChoice("Choose node-local workload", "Which controller naturally runs one eligible logging agent per node?", "daemonset",
                [new("daemonset", "DaemonSet"), new("cronjob", "CronJob"), new("service", "Service")],
                "DaemonSets are designed for node-oriented workloads.", "Chooses workload controllers"), null, KubernetesDocs),

        new("k8s-volumes-pv-pvc", "Storage", 19, "Volumes, PersistentVolumes, and claims",
            "A volume exposes storage to containers in a Pod; a PersistentVolume represents cluster storage and a PersistentVolumeClaim requests persistent storage.",
            "A PVC describes a workload's storage request. A PV represents provisioned capacity. Dynamic provisioning can create storage in response to claims. Mounting the claim into a Pod separates application configuration from the storage implementation.",
            "Treat persistent data lifecycle separately from Pod lifecycle and understand the underlying storage system's failure and backup properties.",
            "Pod → PVC → PV → storage backend",
            KubeChoice("Request storage", "Which object does an application workload normally create to request persistent storage?", "pvc",
                [new("pvc", "PersistentVolumeClaim"), new("pv", "A manually chosen node path"), new("service", "Service")],
                "The claim expresses the consumer's storage requirement.", "Understands PV/PVC boundary"), null, KubernetesDocs),

        new("k8s-storageclass-csi", "Storage", 20, "StorageClasses and CSI",
            "A StorageClass describes a class of provisioned storage; CSI is the Container Storage Interface used by storage plugins to integrate with Kubernetes.",
            "StorageClasses can select provisioners and parameters and influence reclaim or binding behavior. CSI standardizes operations such as provisioning, attaching, and mounting storage without baking vendor-specific storage code into Kubernetes core.",
            "Know which CSI driver and StorageClass back production claims; Kubernetes cannot make an unreliable storage backend reliable.",
            "PVC → StorageClass → CSI driver → cloud/SAN/local storage",
            KubeChoice("Locate vendor integration", "Which interface standardizes Kubernetes integration with storage systems?", "csi",
                [new("csi", "CSI"), new("cni", "CNI"), new("cri", "CRI")],
                "CSI is storage; CNI is networking; CRI is container runtime integration.", "Distinguishes extension interfaces"), null, KubernetesDocs),

        new("k8s-cni-pod-network", "Networking internals", 21, "The Pod network and CNI",
            "The Kubernetes network model expects Pods to have network identities and broad Pod-to-Pod reachability; CNI plugins configure container networking to realize that model.",
            "CNI means Container Network Interface. Implementations may use routing, overlays, eBPF, iptables, or other mechanisms. Kubernetes defines the networking model but does not mandate one packet-forwarding implementation.",
            "When debugging packet flow, identify the installed CNI and its data plane instead of assuming every cluster uses the same mechanism.",
            "Pod network namespace → veth/interface → CNI data plane → node/network → destination Pod",
            KubeChoice("Locate Pod networking", "Which plugin family normally configures Pod networking?", "cni",
                [new("cni", "CNI"), new("csi", "CSI"), new("cri", "CRI")],
                "CNI is the container networking interface.", "Maps CNI responsibility"), null, KubernetesDocs),

        new("k8s-service-routing", "Networking internals", 22, "Service routing, EndpointSlices, and kube-proxy",
            "EndpointSlices represent Service backend endpoints; a Service data plane routes traffic from a stable Service address toward those endpoints.",
            "kube-proxy historically programs node networking rules for Services using supported proxy modes, while some CNI implementations provide alternative/eBPF Service data planes. EndpointSlices are API objects that scale endpoint representation. The Service abstraction is stable even when the implementation differs.",
            "Debug from abstraction downward: Service selector → EndpointSlices → backend readiness → node/CNI Service data plane.",
            "Service selector → EndpointSlices → Service data plane → Pod IP",
            KubeChoice("Find backends", "Which API object family records scalable Service endpoint sets?", "endpointslice",
                [new("endpointslice", "EndpointSlice"), new("configmap", "ConfigMap"), new("storageclass", "StorageClass")],
                "EndpointSlices represent groups of network endpoints.", "Understands Service backend discovery"), null, KubernetesDocs),

        new("k8s-ingress-gateway", "Networking internals", 23, "North-south traffic: Ingress and Gateway API",
            "North-south traffic enters or leaves a cluster; Ingress and Gateway API objects describe ways to route incoming application traffic when corresponding controllers are installed.",
            "An Ingress is an API object for HTTP(S) routing interpreted by an Ingress controller. Gateway API provides more expressive role-oriented networking resources such as Gateway and HTTPRoute. Creating these objects alone does not create a working data plane unless an implementation/controller supports them.",
            "Separate the Kubernetes routing object from the controller/load balancer that implements it.",
            "client → external load balancer/controller → Gateway/Ingress rules → Service → Pods",
            KubeChoice("Recognize implementation", "What must exist for an Ingress object to actually route traffic?", "controller",
                [new("controller", "A compatible Ingress controller/data plane"), new("etcd-only", "Only etcd"), new("pvc", "A PersistentVolumeClaim")],
                "The API object declares routing intent; an implementation realizes it.", "Separates API from implementation"), null, KubernetesDocs),

        new("k8s-networkpolicy", "Security", 24, "NetworkPolicy and workload isolation",
            "A NetworkPolicy declares allowed network traffic for selected Pods when the installed network plugin enforces NetworkPolicy.",
            "Policies can select Pods and define ingress and egress allowances. Once a Pod is isolated for a traffic direction, traffic not allowed by applicable policies is denied for that direction. Exact capabilities depend on the network implementation.",
            "Start from required communication paths and test them. A policy object without an enforcing network implementation provides no isolation.",
            "frontend → API : allowed\nAPI → database : allowed\nother paths : denied when isolation applies",
            KubeChoice("Enforce policy", "What is required in addition to NetworkPolicy objects?", "plugin",
                [new("plugin", "A network implementation that enforces NetworkPolicy"), new("cronjob", "A CronJob"), new("secret", "A Secret")],
                "Policy intent needs a data plane that implements it.", "Understands policy enforcement"), null, KubernetesDocs),

        new("k8s-identity-rbac", "Security", 25, "Authentication, authorization, ServiceAccounts, and RBAC",
            "Authentication establishes an identity; authorization decides what that identity may do; a ServiceAccount provides a Kubernetes identity for workloads.",
            "RBAC means role-based access control. Roles/ClusterRoles contain permission rules; RoleBindings/ClusterRoleBindings grant those roles to subjects. Namespaced RoleBindings can scope grants. Authentication and RBAC are separate stages of an API request.",
            "Grant the smallest permissions needed. Avoid broad cluster-admin bindings and avoid automatically mounting credentials into workloads that do not need API access.",
            "request → authenticate identity → authorize via policy/RBAC → admission → API operation",
            KubeChoice("Grant permissions", "Which object connects an RBAC role to a subject?", "binding",
                [new("binding", "RoleBinding or ClusterRoleBinding"), new("deployment", "Deployment"), new("pvc", "PersistentVolumeClaim")],
                "Roles describe permissions; bindings grant them.", "Understands RBAC composition"), null, KubernetesDocs),

        new("k8s-admission-security", "Security", 26, "Admission control and Pod security",
            "Admission controllers inspect API requests after authentication and authorization but before object persistence, and can validate or mutate supported requests.",
            "Built-in and dynamic admission mechanisms enforce or transform policy at the API boundary. Pod Security Admission can enforce Pod Security Standards at Namespace scope. Validating admission policy/webhooks can reject unsafe configuration; mutating admission can modify requests.",
            "Use admission for guardrails that must hold regardless of which client submits YAML, but keep policies observable and testable to avoid mysterious deployment failures.",
            "authenticate → authorize → admission → persist object",
            KubeChoice("Place admission", "When does admission normally run for an API request?", "after-authz",
                [new("after-authz", "After authentication/authorization and before persistence"), new("after-etcd", "Only after etcd persistence"), new("dns", "During DNS lookup")],
                "Admission is an API-server request stage.", "Places admission correctly"), null, KubernetesDocs),

        new("k8s-api-machinery", "Control plane internals", 27, "API machinery: spec, status, watch, and resource versions",
            "Kubernetes resources separate desired configuration in spec from observed information in status; clients can watch API changes rather than constantly rediscovering all state.",
            "The API server exposes versioned resources. metadata.resourceVersion represents an object's version in API storage semantics and supports concurrency/watch behavior; it is not an application version. Controllers list/watch resources, maintain caches, and reconcile changes.",
            "When writing automation, use Kubernetes client semantics rather than treating etcd as your application's database.",
            "API object: metadata + spec + status\nlist/watch → local cache → reconcile",
            KubeChoice("Interpret status", "What is status primarily intended to represent?", "observed",
                [new("observed", "Observed/current information reported by controllers or components"), new("desired", "The user's entire desired configuration"), new("secret", "Encrypted credentials only")],
                "spec expresses desired state; status reports observations.", "Understands API object semantics"), null, KubernetesDocs),

        new("k8s-controllers-operators-crds", "Control plane internals", 28, "Controllers, CRDs, and operators",
            "A CustomResourceDefinition (CRD) extends the Kubernetes API with a new resource type; a custom controller can reconcile instances of that type.",
            "An operator is a pattern that combines custom resources and controllers to encode operational knowledge. CRDs provide API schema/storage integration; controllers supply behavior. A CRD by itself does not automate anything.",
            "Use a custom controller when reconciliation is truly the right abstraction, not merely to turn every script into Kubernetes YAML.",
            "CustomResource → API server → custom controller reconcile loop → external/cluster state",
            KubeChoice("Add behavior", "What gives a custom resource active reconciliation behavior?", "controller",
                [new("controller", "A controller watching and reconciling it"), new("crd-only", "The CRD alone"), new("label", "A label")],
                "The CRD defines the API type; the controller implements behavior.", "Separates CRD and controller"), null, KubernetesDocs),

        new("k8s-scheduler-internals", "Control plane internals", 29, "Scheduler internals and preemption",
            "The scheduler chooses a feasible node and then scores feasible choices according to scheduling plugins and policy.",
            "Scheduling conceptually includes filtering nodes that cannot satisfy hard constraints and scoring remaining nodes. Binding records the chosen node. Priority can affect ordering and, when necessary and permitted, preemption can remove lower-priority Pods to make room.",
            "A Pending Pod is evidence, not a diagnosis. Inspect scheduler events for resource, affinity, taint, volume, and topology constraints.",
            "unscheduled Pod → filter feasible nodes → score → bind nodeName",
            KubeChoice("Debug Pending", "Where should you look first for why a Pod cannot be scheduled?", "events",
                [new("events", "Pod/scheduler events and scheduling constraints"), new("restart", "Restart every node"), new("dns", "Delete CoreDNS")],
                "Scheduler events usually expose failed predicates/constraints.", "Uses scheduler evidence"), null, KubernetesDocs),

        new("k8s-etcd-ha", "Control plane internals", 30, "etcd, consensus, and control-plane availability",
            "etcd is a distributed strongly consistent key-value store; a multi-member etcd cluster uses consensus so a majority quorum is required to make progress.",
            "Kubernetes control-plane availability depends on API-server availability and the health of its backing etcd. Consensus protects agreement, not backups: operator mistakes or bad data can still be consistently replicated. Production clusters need supported etcd backup and restore procedures.",
            "Do not casually operate on etcd data directly. Test restore procedures, protect credentials, and understand quorum before maintenance.",
            "3-member etcd cluster → quorum 2\n5-member etcd cluster → quorum 3",
            KubeChoice("Understand quorum", "How many members form a majority in a healthy 3-member etcd cluster?", "2",
                [new("2", "2"), new("1", "1"), new("3-only", "Exactly 3 are always required")],
                "Consensus needs a majority, not every member.", "Understands quorum"), null, KubernetesDocs),

        new("k8s-autoscaling", "Operations", 31, "Horizontal, vertical, and node autoscaling",
            "Autoscaling changes capacity in response to policy: HPA changes replica counts, VPA can recommend or adjust Pod resources, and node autoscaling changes cluster machine capacity.",
            "Horizontal Pod Autoscaler uses metrics to adjust scalable workload replicas. Vertical Pod Autoscaler addresses resource requests and may require Pod replacement depending on mode. Node autoscalers provision or remove nodes when workload scheduling and utilization justify it. These loops interact.",
            "Do not scale on a metric merely because it exists. Choose a signal tied to bottleneck or demand and understand startup time and downstream limits.",
            "demand metric → HPA → replicas\nPod resource need → VPA → requests\nunschedulable capacity → node autoscaler → nodes",
            KubeChoice("Scale replicas", "Which Kubernetes mechanism directly adjusts a Deployment's replica count from metrics?", "hpa",
                [new("hpa", "Horizontal Pod Autoscaler"), new("vpa", "Vertical Pod Autoscaler"), new("csi", "CSI")],
                "Horizontal scaling changes replica count.", "Distinguishes autoscaling layers"), null, KubernetesDocs),

        new("k8s-observability", "Operations", 32, "Logs, metrics, traces, events, and audit",
            "Observability uses emitted evidence to understand system behavior: logs record events, metrics summarize numeric signals, traces connect distributed request work, and Kubernetes Events describe notable resource activity.",
            "kubectl logs reads container logs exposed through node/container runtime integration. Metrics systems provide time-series telemetry. Distributed tracing follows requests across services. Kubernetes Events are useful but not a durable general-purpose log. Audit logging records API activity when configured.",
            "Correlate layers: user symptom → application telemetry → Kubernetes object state/events → node/runtime/network/storage evidence.",
            "kubectl get pods\nkubectl describe pod <name>\nkubectl logs <pod>\nkubectl get events --sort-by=.lastTimestamp",
            KubeChoice("Choose evidence", "Which signal is designed to connect one request across multiple services?", "trace",
                [new("trace", "Distributed trace"), new("pvc", "PersistentVolumeClaim"), new("taint", "Node taint")],
                "Traces model distributed request spans.", "Separates telemetry types"), null, KubernetesDocs),

        new("k8s-debugging", "Operations", 33, "Systematic Kubernetes debugging",
            "Effective debugging follows dependencies and evidence instead of randomly restarting components.",
            "Start with the symptom and object status. For a failing workload inspect Pod phase/conditions, events, logs, container termination reason, probes, configuration, and resources. For traffic inspect DNS, Service selectors, EndpointSlices, readiness, ports, NetworkPolicy, and the data plane. For Pending Pods inspect scheduling events and volume binding.",
            "Change one hypothesis at a time. Preserve evidence before deleting or restarting the object that contains it.",
            "kubectl get pod -o wide\nkubectl describe pod <pod>\nkubectl logs <pod> --previous\nkubectl get endpointslices",
            KubeCode("Build a debug sequence", "Write kubectl commands to inspect a failing Pod named orders-abc in Namespace payments: get it wide, describe it, and read previous container logs.", "kubectl ", "Use -n payments consistently and kubectl logs --previous.", "get wide", "describe", "previous logs", "payments namespace"), null, KubernetesDocs),

        new("k8s-rollouts-disruption", "Operations", 34, "Rollouts, disruption, and graceful termination",
            "A rollout changes managed Pods over time; graceful termination gives applications time to stop accepting and finish work; disruption controls preserve availability during voluntary changes.",
            "Deployments use rollout strategy fields such as maxUnavailable and maxSurge. terminationGracePeriodSeconds bounds normal shutdown time. PodDisruptionBudgets constrain voluntary disruptions but do not prevent every outage. Readiness and graceful shutdown must align so terminating instances stop receiving new work appropriately.",
            "Design releases around application behavior, not only YAML. Test shutdown, startup, rollback, and node-drain behavior.",
            "new ReplicaSet ↑ while old ReplicaSet ↓\nSIGTERM → grace period → forced termination if still running",
            KubeChoice("Protect drain availability", "Which object constrains how many selected Pods may be voluntarily disrupted at once?", "pdb",
                [new("pdb", "PodDisruptionBudget"), new("secret", "Secret"), new("storageclass", "StorageClass")],
                "PDBs participate in voluntary disruption decisions.", "Understands disruption"), null, KubernetesDocs),

        new("k8s-helm-kustomize-gitops", "Delivery", 35, "Configuration packaging: Kustomize, Helm, and GitOps",
            "Kustomize composes YAML through overlays; Helm packages parameterized Kubernetes resources into charts; GitOps continuously reconciles cluster state from version-controlled desired configuration.",
            "These tools solve related but different problems. Kustomize transforms base manifests without a template language. Helm renders and manages chart releases. GitOps tools such as Argo CD or Flux add a reconciliation workflow around a source repository. None replaces understanding the rendered Kubernetes objects.",
            "Always be able to inspect the final manifests and diff the intended change before applying it.",
            "kustomize build overlays/prod\nhelm template orders ./chart\nGit repository → GitOps controller → Kubernetes API",
            KubeChoice("Inspect reality", "What should you inspect when a packaging tool behaves unexpectedly?", "rendered",
                [new("rendered", "The final rendered Kubernetes objects"), new("logo", "The tool's logo"), new("dns", "Only DNS")],
                "Kubernetes ultimately receives API objects.", "Looks through tooling abstractions"), null, KubernetesDocs),

        new("k8s-upgrades-api-lifecycle", "Operations", 36, "API versions, deprecations, and cluster upgrades",
            "Kubernetes APIs evolve through versioned resources, and cluster upgrades must account for supported version skew, removed APIs, node components, and add-ons.",
            "A manifest's apiVersion selects an API version, not the Kubernetes server version. APIs can graduate or be removed after deprecation. Safe upgrades include reading release notes, checking deprecated APIs, respecting supported component skew, backing up critical state, upgrading in supported order, and validating workloads/add-ons.",
            "Treat upgrades as production changes with rehearsal, compatibility checks, rollback/recovery planning, and post-upgrade verification.",
            "discover deprecated APIs → validate add-ons → backup → control plane → nodes → verify",
            KubeChoice("Interpret apiVersion", "What does apps/v1 in a Deployment identify?", "api",
                [new("api", "The API group/version used for that resource"), new("server", "The exact cluster binary version"), new("image", "The container image version")],
                "Resource API versions and cluster release versions are related but different concepts.", "Understands API lifecycle"), null, KubernetesDocs),

        new("k8s-multitenancy-policy", "Production architecture", 37, "Namespaces, quotas, policy, and multi-tenancy",
            "Multi-tenancy means multiple teams or tenants share infrastructure while controls limit interference; Kubernetes Namespaces are useful scopes but are not complete security boundaries by themselves.",
            "ResourceQuota limits aggregate resource consumption in a Namespace. LimitRange can establish per-object defaults/constraints. RBAC, NetworkPolicy, Pod security, admission policy, node isolation, and sometimes separate clusters combine to create stronger boundaries.",
            "Choose isolation strength from threat and failure models. Do not claim a Namespace alone isolates hostile tenants.",
            "tenant boundary = identity/RBAC + resources + network + workload policy + infrastructure decisions",
            KubeChoice("Assess Namespace isolation", "Is a Kubernetes Namespace alone a complete hostile-tenant security boundary?", "no",
                [new("no", "No; multiple security and resource controls are required"), new("yes", "Yes, automatically"), new("storage", "Only when a PVC exists")],
                "Namespaces scope objects but do not independently provide every isolation property.", "Understands multi-tenancy"), null, KubernetesDocs),

        new("k8s-production-design", "Production architecture", 38, "Designing a production Kubernetes platform",
            "A production platform combines availability, security, capacity, delivery, observability, recovery, and ownership decisions around Kubernetes.",
            "Define failure domains, control-plane responsibility, node pools, network and storage implementations, ingress/gateway strategy, identity and RBAC, secret management, policy, resource standards, autoscaling, observability, backup/restore, upgrade cadence, cost controls, and an incident ownership model. Managed Kubernetes can transfer some operational responsibility but not application architecture or workload correctness.",
            "Prefer boring, documented defaults. Every optional platform component creates another API, upgrade path, failure mode, and on-call responsibility.",
            "platform = cluster lifecycle + workload contract + security guardrails + telemetry + recovery + delivery",
            KubeChoice("Evaluate platform complexity", "What is the best reason to add another cluster-wide platform component?", "requirement",
                [new("requirement", "It satisfies a clear requirement whose operational cost is understood"), new("popular", "It is popular"), new("yaml", "It adds more YAML")],
                "Platform components should earn their operational burden.", "Reasons about production tradeoffs"), null, KubernetesDocs),

        new("k8s-capstone", "Production architecture", 39, "Capstone: reason through a production service",
            "Deep Kubernetes skill is the ability to trace a workload from desired state through controllers, scheduling, runtime, networking, storage, security, and operations.",
            "Design an orders API with multiple replicas, stable Service discovery, configuration and credentials, resource requests, health probes, topology-aware placement, least-privilege API access, network isolation, autoscaling, controlled disruption, external HTTP routing, telemetry, and a rollout/recovery strategy. Then explain which control loop or data plane implements each behavior.",
            "Do not hide behind a manifest dump. A production design should explain why each object exists, what component acts on it, and what happens when a dependency fails.",
            "client → Gateway → Service → ready Pods\n                         ↓\n                  config/secrets\ncontrol plane → scheduler/controllers → kubelet/runtime\ntelemetry + policy + recovery surround the workload",
            new Exercise(ExerciseKind.Presentation, "Production architecture review",
                "Design the production orders service and explain the complete request, reconciliation, failure, and recovery paths.",
                ["Explain every Kubernetes object before using it", "Trace an incoming request to a Pod", "Trace a Deployment change through reconciliation", "Describe node, network, storage, and dependency failures", "Define security, observability, backup, and upgrade controls"],
                null, null, [], "Use the course layers as a checklist; focus on mechanisms and tradeoffs rather than a giant YAML file.", []), null, KubernetesDocs)
    ]);
}
