static partial class Curriculum
{
    private static readonly VersionStamp LinuxCliDocs = new(
        "GNU/Linux CLI · Bash 5.3",
        "GNU coreutils · common Unix tools",
        "2026-09-26",
        "https://www.gnu.org/software/bash/manual/bash.html");

    private static readonly VersionStamp VimDocs = new(
        "Vim 9.2",
        "Terminal Vim",
        "2026-09-26",
        "https://www.vim.org/docs.php");

    private static Exercise LinuxChoice(
        string title,
        string prompt,
        string correct,
        Choice[] choices,
        string hint,
        params string[] tests) =>
        new(
            ExerciseKind.MultipleChoice,
            title,
            prompt,
            ["Choose the best answer"],
            null,
            correct,
            choices,
            hint,
            tests);

    private static Exercise LinuxCode(
        string title,
        string prompt,
        string starter,
        string hint,
        params string[] tests) =>
        new(
            ExerciseKind.Code,
            title,
            prompt,
            [
                "Write commands or a Bash script that produces the requested filesystem/result state",
                "The submission runs inside a disposable, network-isolated Linux sandbox",
                "The evaluator verifies the resulting files, output, permissions, or process behavior"
            ],
            starter,
            null,
            [],
            hint,
            tests);

    public static Lesson[] BuildLinuxCliLessons() => NormalizeLessons(
    [
        new(
            "linux-shell-terminal",
            "Terminal foundations",
            1,
            "Understand the terminal, shell, and command",
            "A terminal is the text interface you type into; a shell reads commands, expands them, launches programs, and connects their input/output.",
            "Bash is a shell. Commands can be shell builtins such as cd, external programs such as ls, scripts, aliases, or functions. The shell parses quoting, variables, redirects, pipes, and control operators before programs receive their arguments.",
            "When a command surprises you, separate the layers: what text Bash parsed, which executable or builtin ran, what arguments it received, and where stdin/stdout/stderr were connected.",
            "type cd\ntype ls\ncommand -V printf",
            LinuxChoice(
                "Identify the shell's job",
                "Which responsibility belongs to Bash rather than to the terminal emulator?",
                "parse",
                [new("parse", "Parse quoting, variables, pipes, and redirects before launching commands"), new("pixels", "Draw every terminal glyph on the screen"), new("kernel", "Implement the Linux kernel scheduler")],
                "The shell interprets command language; the terminal provides the interactive text interface.",
                "Separates terminal, shell, program, and kernel responsibilities"),
            null,
            LinuxCliDocs),
        new(
            "linux-paths-navigation",
            "Terminal foundations",
            2,
            "Navigate with absolute and relative paths",
            "The working directory gives relative paths their meaning; absolute paths start at the filesystem root.",
            "pwd prints the current directory. cd changes it. . means the current directory, .. means the parent, and ~ expands to the current user's home directory in Bash.",
            "Prefer explicit paths in scripts and automation. Interactive shortcuts are convenient, but reliable scripts should make their working-directory assumptions obvious.",
            "pwd\ncd /workspace/project\nls ./src\ncd ..",
            LinuxCode(
                "Navigate to the target",
                "Start in /workspace. Change into project/src and print the absolute working directory followed by the contents of the parent project directory.",
                "cd ",
                "Use cd, pwd, and ls with .. or an absolute path.",
                "ends in /workspace/project/src",
                "prints the absolute path",
                "lists the project directory"),
            null,
            LinuxCliDocs),
        new(
            "linux-files-directories",
            "Terminal foundations",
            3,
            "Create, copy, move, and remove filesystem entries",
            "Most filesystem work is composition of a few commands: mkdir, touch, cp, mv, rm, and rmdir.",
            "mkdir -p creates missing parent directories. cp copies data; mv renames or relocates it. rm removes files and rm -r recursively removes directories.",
            "Treat destructive commands as irreversible unless you have another recovery mechanism. Inspect the path and expansion before recursive deletion, especially when variables or globs are involved.",
            "mkdir -p archive/2026\ncp notes.txt archive/2026/notes.txt\nmv draft.txt final.txt\nrm scratch.txt",
            LinuxCode(
                "Reshape a project directory",
                "Create archive/2026, copy report.txt into it as report.txt, rename draft.txt to release-notes.txt, and remove scratch.tmp.",
                "# Work in the prepared project directory\n",
                "Use mkdir -p, cp, mv, and rm.",
                "archive copy exists",
                "draft is renamed",
                "scratch file is removed"),
            null,
            LinuxCliDocs),
        new(
            "linux-help-inspection",
            "Terminal foundations",
            4,
            "Discover commands instead of memorizing everything",
            "Productive CLI work depends on knowing how to ask the system what a command is and how it behaves.",
            "type and command -V show how Bash resolves a name. --help often gives a compact option summary. man opens the manual page when installed. apropos searches manual descriptions.",
            "Before copying an unfamiliar destructive command, inspect its help and understand the options. Command names are portable more often than every option is, so verify the implementation on the machine you are using.",
            "type grep\ngrep --help\nman grep",
            LinuxChoice(
                "Inspect resolution",
                "Which command tells you whether cd is a builtin, alias, function, or external command?",
                "type",
                [new("type", "type cd"), new("cat", "cat cd"), new("pwd", "pwd cd")],
                "Bash's type builtin describes how a command name resolves.",
                "Uses built-in discovery tools"),
            null,
            LinuxCliDocs),
        new(
            "linux-read-text",
            "Terminal foundations",
            5,
            "Inspect text without opening an editor",
            "CLI tools let you inspect exactly the slice of a file or stream that you need.",
            "cat writes files to stdout, less pages interactively, head and tail select the beginning/end, wc counts lines/words/bytes, and tail -f follows a growing file.",
            "Use the smallest tool that answers the question. For a large log, head/tail/grep are usually safer and faster than dumping the entire file to the terminal.",
            "head -n 5 app.log\ntail -n 20 app.log\nwc -l app.log",
            LinuxCode(
                "Inspect a log",
                "Print the first 2 lines of app.log, then the final 2 lines, then print only the total line count.",
                "# app.log is prepared\n",
                "Use head, tail, and wc.",
                "prints the first lines",
                "prints the final lines",
                "prints the correct count"),
            null,
            LinuxCliDocs),
        new(
            "linux-pipes-redirection",
            "Terminal foundations",
            6,
            "Connect commands with pipes and redirection",
            "Unix commands become powerful when stdout from one process becomes stdin for another.",
            "| creates a pipeline. > replaces a file with stdout, >> appends stdout, < supplies stdin from a file, and 2> redirects stderr. 2>&1 points stderr at the current stdout destination.",
            "A pipe connects processes; a redirect connects a stream to a file or other descriptor. Do not use > when you mean >>—truncation happens before the command runs.",
            "grep ERROR app.log | sort | uniq -c > error-counts.txt\ncommand 2> errors.log",
            LinuxCode(
                "Build a small pipeline",
                "From app.log, select lines containing ERROR, sort them, count duplicate lines with uniq -c, and write the result to error-counts.txt.",
                "grep ",
                "Pipe grep to sort to uniq -c, then redirect stdout.",
                "filters ERROR lines",
                "aggregates duplicates",
                "writes error-counts.txt"),
            null,
            LinuxCliDocs),
        new(
            "linux-grep-find",
            "Terminal foundations",
            7,
            "Search file contents and filesystem paths",
            "grep searches text; find searches directory trees based on file metadata and paths.",
            "grep -R can search recursively, while find combines predicates such as -type, -name, -mtime, and -size. find -exec can safely run a command for each matched path.",
            "Do not parse ls output in scripts. Use find, globs, or null-delimited tools when filenames can contain spaces or unusual characters.",
            "grep -Rni 'timeout' config/\nfind . -type f -name '*.log' -size +1M",
            LinuxCode(
                "Find matching configuration",
                "Print config files under config/ ending in .conf that contain the exact text enabled=true.",
                "find ",
                "Use find for the path set and grep for file contents.",
                "only .conf files are considered",
                "enabled=true is required",
                "matching paths are printed"),
            null,
            LinuxCliDocs),
        new(
            "linux-expansion-quoting",
            "Terminal foundations",
            8,
            "Control expansion, globbing, and quoting",
            "Bash transforms command text before execution: variables expand, globs match paths, command substitutions produce text, and quoting controls those transformations.",
            "Single quotes preserve literal text. Double quotes allow parameter and command substitution while preventing word splitting and pathname expansion of the expanded value. Unquoted variables are often a bug when values may contain spaces or wildcard characters.",
            "Default to quoting parameter expansions: \"$file\". Use arrays when you need a list of arguments. Understand a glob before combining it with destructive commands.",
            "name='Ada Lovelace'\nprintf '%s\\n' \"$name\"\nprintf '%s\\n' ./*.log",
            LinuxCode(
                "Preserve filenames safely",
                "Copy the prepared file whose path is stored in SOURCE into backup/ while preserving a filename that contains spaces.",
                "mkdir -p backup\n",
                "Quote the variable expansion passed to cp.",
                "source with spaces is copied",
                "destination filename is preserved",
                "no accidental split paths are created"),
            null,
            LinuxCliDocs),
        new(
            "linux-permissions",
            "Terminal foundations",
            9,
            "Read and change Unix permissions",
            "Unix mode bits describe read, write, and execute permissions for the file owner, group, and others.",
            "ls -l displays permission bits. chmod can use symbolic forms such as u+x and go-rwx or octal forms such as 750. Directories use execute permission to allow traversal.",
            "Do not solve permission problems with chmod 777. Give only the identities that need access the permissions they need, and remember ownership and ACLs can also affect access.",
            "chmod u+x deploy.sh\nchmod 750 private-bin\nls -l deploy.sh",
            LinuxCode(
                "Protect an executable",
                "Make deploy.sh executable by its owner, readable/executable by its group, and inaccessible to others.",
                "chmod ",
                "A mode of 750 expresses rwx for owner, r-x for group, and --- for others.",
                "owner can execute",
                "group can read and execute",
                "others have no permissions"),
            null,
            LinuxCliDocs),
        new(
            "linux-processes-jobs",
            "Terminal foundations",
            10,
            "Inspect processes and control shell jobs",
            "A process is a running program; a shell job is Bash's interactive grouping for processes started from that shell.",
            "ps inspects processes. & starts a pipeline in the background. jobs lists shell jobs, fg/bg resume jobs, and kill sends signals to processes. Ctrl-C normally sends SIGINT to the foreground job.",
            "Prefer graceful termination before SIGKILL. A stuck process may be waiting on I/O or holding resources that need cleanup.",
            "sleep 60 &\njobs\nps -o pid,ppid,stat,command\nkill \"$pid\"",
            LinuxChoice(
                "Stop gracefully first",
                "Which approach is usually appropriate before reaching for kill -9?",
                "term",
                [new("term", "Send the process a normal termination signal and allow cleanup"), new("nine", "Always use SIGKILL first"), new("reboot", "Reboot the machine")],
                "SIGKILL cannot be caught for cleanup; use it when ordinary termination cannot work.",
                "Uses signals deliberately"),
            null,
            LinuxCliDocs),
        new(
            "linux-environment-path",
            "Terminal foundations",
            11,
            "Understand environment variables, PATH, and shell startup",
            "Environment variables are name/value strings inherited by child processes; PATH tells the shell which directories to search for executables.",
            "NAME=value sets a shell variable. export NAME makes it part of the environment inherited by commands. command -v shows what executable will run. ~/.bashrc commonly configures interactive Bash sessions.",
            "Do not put secrets directly into shell history or committed startup files. When modifying PATH, append/prepend intentionally and quote the previous value.",
            "export APP_ENV=development\nexport PATH=\"$HOME/bin:$PATH\"\ncommand -v bash",
            LinuxCode(
                "Expose a user command",
                "Create $HOME/bin if needed, prepend it to PATH for this shell, and print the resolved path to the prepared hello-pathway executable.",
                "mkdir -p \"$HOME/bin\"\n",
                "Export PATH with $HOME/bin before the existing PATH, then use command -v.",
                "HOME/bin is first in PATH",
                "hello-pathway resolves",
                "resolved path is printed"),
            null,
            LinuxCliDocs),
        new(
            "linux-archives-compression",
            "Terminal foundations",
            12,
            "Archive and compress files",
            "tar combines a directory tree into an archive; gzip and related compressors reduce its size.",
            "tar -cf creates an uncompressed archive, tar -xf extracts one, and common tar implementations support -z for gzip-compressed .tar.gz archives.",
            "An archive is not a backup strategy by itself. Know where extraction will write files, inspect untrusted archives before extraction, and preserve permissions/ownership only when appropriate.",
            "tar -czf logs.tar.gz logs/\ntar -tzf logs.tar.gz\ntar -xzf logs.tar.gz -C restore/",
            LinuxCode(
                "Package a release",
                "Create release.tar.gz containing the prepared dist/ directory, then list the archive contents.",
                "tar ",
                "Use tar with gzip compression and then list the archive.",
                "release.tar.gz exists",
                "archive contains dist files",
                "contents are printed"),
            null,
            LinuxCliDocs),
        new(
            "bash-script-basics",
            "Bash scripting",
            13,
            "Turn commands into an executable Bash script",
            "A shell script is a text file of commands interpreted by a shell; the shebang selects the interpreter when the file is executed directly.",
            "#!/usr/bin/env bash is a common portable shebang when Bash must come from PATH. chmod +x adds execute permission, but scripts can also be run explicitly with bash script.sh.",
            "Keep scripts deterministic: establish inputs, quote paths, return useful exit codes, and avoid depending silently on the caller's current directory.",
            "#!/usr/bin/env bash\nprintf 'Pathway\\n'",
            LinuxCode(
                "Create an executable script",
                "Create greet.sh with a Bash shebang that prints exactly Hello, Pathway!, make it executable, and run it.",
                "cat > greet.sh <<'EOF'\n#!/usr/bin/env bash\n# add output here\nEOF\n",
                "Write the script, chmod +x it, then execute ./greet.sh.",
                "greet.sh has a Bash shebang",
                "greet.sh is executable",
                "script prints the required text"),
            null,
            LinuxCliDocs),
        new(
            "bash-variables-arguments",
            "Bash scripting",
            14,
            "Use variables, positional arguments, and command substitution",
            "Bash scripts receive arguments separately from their source text; quoting preserves each argument's boundaries.",
            "$1, $2, and so on are positional parameters, $# is the argument count, and \"$@\" expands to all arguments while preserving each as a separate word. $(command) captures stdout from a command.",
            "Use \"$@\" when forwarding arguments. Avoid eval for routine argument handling. Validate required arguments and print usage information when inputs are missing.",
            "name=${1:-world}\nprintf 'Hello, %s\\n' \"$name\"\ncount=$(wc -l < input.txt)",
            LinuxCode(
                "Read a required argument",
                "Create show-user.sh. It should require one username argument, print Usage: show-user.sh USER to stderr and exit 2 when missing, otherwise print User: NAME.",
                "cat > show-user.sh <<'EOF'\n#!/usr/bin/env bash\n\nEOF\nchmod +x show-user.sh\n",
                "Check $# or ${1:-}; write the usage line to >&2 and exit 2.",
                "missing argument exits 2",
                "usage goes to stderr",
                "provided username is printed"),
            null,
            LinuxCliDocs),
        new(
            "bash-status-conditionals",
            "Bash scripting",
            15,
            "Branch on exit status and test expressions",
            "Unix commands report success or failure with an integer exit status; Bash conditionals are designed to branch on that status.",
            "if command; then ... fi tests a command directly. [[ ... ]] is Bash's safer conditional syntax for strings, patterns, and file tests. && and || conditionally run commands based on success/failure.",
            "Do not write if [ $? -eq 0 ] when you can write if command directly. Preserve meaningful failure codes instead of hiding them.",
            "if [[ -f config.env ]]; then\n  printf 'found\\n'\nelse\n  printf 'missing\\n' >&2\n  exit 1\nfi",
            LinuxCode(
                "Validate an input file",
                "Create validate.sh that accepts a path, prints ready and exits 0 only when it names a non-empty regular file; otherwise print invalid to stderr and exit 1.",
                "cat > validate.sh <<'EOF'\n#!/usr/bin/env bash\n\nEOF\nchmod +x validate.sh\n",
                "Use [[ -f ... && -s ... ]] with a quoted argument.",
                "valid file succeeds",
                "empty or missing file fails",
                "failure message uses stderr"),
            null,
            LinuxCliDocs),
        new(
            "bash-loops-functions",
            "Bash scripting",
            16,
            "Use loops and functions without losing argument boundaries",
            "Loops repeat command structures; functions name reusable shell logic in the current shell process.",
            "for item in \"$@\" safely iterates arguments. while IFS= read -r line reads text without treating backslashes or leading/trailing whitespace as syntax. Functions receive their own positional parameters.",
            "Prefer small functions with explicit inputs and observable outputs. Avoid parsing line-oriented data with for item in $(command), which performs word splitting.",
            "print_file() {\n  local file=$1\n  printf '%s: ' \"$file\"\n  wc -l < \"$file\"\n}\nfor file in \"$@\"; do print_file \"$file\"; done",
            LinuxCode(
                "Process arbitrary filenames",
                "Create count-lines.sh that accepts any number of file paths and prints FILE: N for each, correctly handling filenames that contain spaces.",
                "cat > count-lines.sh <<'EOF'\n#!/usr/bin/env bash\n\nEOF\nchmod +x count-lines.sh\n",
                "Iterate over \"$@\" and quote each filename.",
                "processes every argument",
                "handles spaces in filenames",
                "prints each line count"),
            null,
            LinuxCliDocs),
        new(
            "bash-safe-scripting",
            "Bash scripting",
            17,
            "Make failure behavior explicit",
            "Reliable scripts decide how unset variables, failed pipelines, temporary files, and cleanup should behave.",
            "set -u catches unset variables and set -o pipefail makes a pipeline fail when an earlier command fails. set -e can be useful but has context-sensitive behavior; understand it rather than treating it as exception handling. trap registers cleanup actions.",
            "For temporary resources, create them safely with mktemp and clean them in a trap. Check expected failures explicitly. ShellCheck is useful static analysis when available.",
            "set -euo pipefail\ntmp=$(mktemp)\ntrap 'rm -f \"$tmp\"' EXIT",
            LinuxCode(
                "Clean up temporary work",
                "Create safe-temp.sh using set -euo pipefail, create a temporary file with mktemp, register an EXIT trap that removes it, write Pathway into it, and print its contents.",
                "cat > safe-temp.sh <<'EOF'\n#!/usr/bin/env bash\n\nEOF\nchmod +x safe-temp.sh\n",
                "Use mktemp and trap ... EXIT after enabling strict failure checks.",
                "strict settings are enabled",
                "temporary file is removed",
                "Pathway is printed"),
            null,
            LinuxCliDocs),
        new(
            "bash-text-processing",
            "Bash scripting",
            18,
            "Compose grep, sort, uniq, cut, sed, and awk",
            "Text tools are small data transformations that work well when the input format is genuinely line-oriented text.",
            "cut selects delimited fields, sort orders records, uniq collapses adjacent duplicates, sed performs stream edits, and awk combines field-oriented selection/calculation.",
            "Choose a structured parser for JSON, XML, CSV with complex quoting, or other formats where line/field assumptions are unsafe. Text pipelines are excellent when their input contract is simple and explicit.",
            "awk -F, '$3 == \"active\" { print $2 }' users.csv | sort -u",
            LinuxCode(
                "Summarize a CSV-like file",
                "From users.csv with id,name,status columns and simple comma-delimited values, print the unique active user names in alphabetical order.",
                "awk ",
                "Use awk -F, to filter status and print name, then sort -u.",
                "only active rows are used",
                "names are selected",
                "output is unique and sorted"),
            null,
            LinuxCliDocs),
        new(
            "vim-modes-save-quit",
            "Vim",
            19,
            "Understand Vim modes and leave the editor safely",
            "Vim is modal: the same key means different things depending on whether you are navigating, inserting text, selecting text, or entering command-line commands.",
            "Normal mode is the command/navigation home base. i enters Insert mode and Esc returns to Normal mode. :w writes, :q quits, :wq writes and quits, and :q! abandons unsaved changes.",
            "When Vim feels stuck, press Esc to return to Normal mode before reasoning about the next command. Avoid memorizing random key sequences without understanding the current mode.",
            "i        # enter Insert mode\n<Esc>    # return to Normal mode\n:w       # write\n:q       # quit\n:wq      # write and quit",
            LinuxChoice(
                "Return to Normal mode",
                "You are typing text in Insert mode and want to issue a navigation command. What should you do first?",
                "escape",
                [new("escape", "Press Esc"), new("colon", "Type :q! immediately"), new("ctrlc", "Close the terminal")],
                "Normal mode is Vim's command/navigation home base.",
                "Understands Vim's modal model"),
            null,
            VimDocs),
        new(
            "vim-motions-operators",
            "Vim",
            20,
            "Combine motions with operators",
            "Vim editing is compositional: operators say what to do and motions/text objects say what range to do it to.",
            "h/j/k/l move by character/line, w/b/e move by words, 0/^/$ move within a line, gg/G move to file boundaries. d deletes, c changes, and y yanks. dw, d$, ciw, and yyp are combinations rather than unrelated shortcuts.",
            "Learn the grammar before collecting plugins: operator + count + motion/text object. That model scales to commands you have never memorized.",
            "dw    # delete through a word motion\nd$    # delete to end of line\nciw   # change inner word\nyy    # yank line\np     # paste after",
            LinuxChoice(
                "Compose an edit",
                "In Normal mode, which command changes the word under the cursor without requiring you to position at its first character?",
                "ciw",
                [new("ciw", "ciw"), new("gg", "gg"), new("wq", ":wq")],
                "c is the change operator and iw is the inner-word text object.",
                "Uses Vim's operator + text-object grammar"),
            null,
            VimDocs),
        new(
            "vim-search-substitute",
            "Vim",
            21,
            "Search and substitute efficiently",
            "Vim can navigate matches and perform precise substitutions without leaving the editor.",
            "/pattern searches forward, ?pattern searches backward, n/N move among matches, and :s uses a regular-expression substitution over a chosen range.",
            ":%s/old/new/g replaces every match in the file. Add c to confirm each replacement when the change is broad or risky.",
            "/timeout\nn\n:%s/timeout/request_timeout/gc",
            LinuxCode(
                "Apply a Vim substitution",
                "Write Vim Ex commands that replace every TODO with DONE in the prepared notes.txt file and save it.",
                ":%s/",
                "Use :%s/TODO/DONE/g followed by :write.",
                "all TODO markers are replaced",
                "DONE markers remain",
                "file is saved"),
            null,
            VimDocs),
        new(
            "vim-yank-paste-undo",
            "Vim",
            22,
            "Yank, delete, paste, undo, and redo",
            "Vim stores deleted and yanked text in registers, which makes many edits naturally become move/copy operations.",
            "yy yanks a line, dd deletes a line, p/P paste after/before, u undoes, and Ctrl-r redoes. Named registers such as \"ayy and \"ap let you preserve specific text instead of relying only on the unnamed register.",
            "Remember that delete operations also populate registers. When a paste target matters, use a named register or the black-hole register deliberately.",
            "yy\np\ndd\nu\n<C-r>\n\"ayy\n\"ap",
            LinuxChoice(
                "Preserve a yank",
                "You want to keep a copied line available while performing other deletes. What is the most deliberate approach?",
                "register",
                [new("register", "Yank it into a named register and paste from that register"), new("mouse", "Depend only on terminal mouse selection"), new("quit", "Quit after every delete")],
                "Named registers prevent unrelated deletes from replacing the text you intend to paste.",
                "Uses registers intentionally"),
            null,
            VimDocs),
        new(
            "vim-buffers-windows-config",
            "Vim",
            23,
            "Work with buffers, windows, and small configuration",
            "A Vim buffer is an in-memory file representation; a window is a viewport onto a buffer. Keeping those concepts separate makes multi-file editing predictable.",
            ":edit opens a file into a buffer, :ls lists buffers, :buffer switches buffers, :split/:vsplit create windows, and Ctrl-w motions move among windows. Vim 9.2 supports XDG-style configuration locations on Unix in addition to traditional vimrc behavior.",
            "Keep initial configuration small: line numbers, sensible indentation, search behavior, and syntax/filetype support. Add plugins only when a repeated workflow justifies them.",
            ":edit src/app.sh\n:ls\n:vsplit README.md\n:set number\n:filetype plugin indent on",
            LinuxChoice(
                "Distinguish buffer and window",
                "What is a Vim window?",
                "viewport",
                [new("viewport", "A viewport displaying a buffer"), new("file", "The file on disk itself"), new("shell", "A separate Bash process")],
                "Buffers hold editable file contents; windows display buffers.",
                "Understands Vim's multi-file model"),
            null,
            VimDocs),
        new(
            "linux-cli-capstone",
            "Capstone",
            24,
            "Build a terminal-only support bundle",
            "Terminal fluency means combining filesystem tools, pipelines, permissions, Bash control flow, and editor knowledge into a repeatable workflow.",
            "The capstone creates a support-bundle.sh script that validates a source directory, gathers selected log/config data into a staging directory, summarizes ERROR lines, archives the bundle, and cleans temporary state.",
            "Use quoted variables, set -euo pipefail, mktemp -d with an EXIT trap, find/grep or a safe equivalent, and tar. The evaluator supplies a directory with spaces in its name to prove your script preserves argument boundaries.",
            "# Build support-bundle.sh, make it executable, then run it against the prepared source directory.",
            LinuxCode(
                "Create the support-bundle script",
                "Create executable support-bundle.sh SOURCE OUTPUT. Require SOURCE to be a directory, stage *.log and *.conf files into a temporary directory, write error-summary.txt containing sorted unique ERROR lines, create OUTPUT as a .tar.gz archive, and clean the temporary directory on exit.",
                "cat > support-bundle.sh <<'EOF'\n#!/usr/bin/env bash\nset -euo pipefail\n\nEOF\nchmod +x support-bundle.sh\n",
                "Quote SOURCE/OUTPUT, use mktemp -d plus an EXIT trap, and build the archive from the staging directory.",
                "handles a source path containing spaces",
                "archive contains selected files and error summary",
                "temporary staging directory is cleaned"),
            null,
            LinuxCliDocs)
    ]);
}
