using System.Text.Json.Serialization;
using System.Net.Http.Json;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Pathway.Api;

var builder = WebApplication.CreateBuilder(args);
builder.Services.ConfigureHttpJsonOptions(options => options.SerializerOptions.Converters.Add(new JsonStringEnumConverter()));
builder.Services.AddHttpClient();
var databaseUrl = builder.Configuration["DATABASE_URL"] ?? builder.Configuration.GetConnectionString("Pathway");
if (!string.IsNullOrWhiteSpace(databaseUrl))
    builder.Services.AddDbContextFactory<ProgressDbContext>(options => options.UseNpgsql(ToNpgsqlConnectionString(databaseUrl)));
var allowedOrigins = (builder.Configuration["CORS_ORIGINS"] ?? "http://localhost:5173,http://127.0.0.1:5173")
    .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
builder.Services.AddCors(options => options.AddDefaultPolicy(policy => policy.WithOrigins(allowedOrigins).AllowAnyHeader().AllowAnyMethod()));
builder.Services.AddAuthorization();
var keycloakAuthority = builder.Configuration["KEYCLOAK_AUTHORITY"]?.TrimEnd('/');
var keycloakAudience = builder.Configuration["KEYCLOAK_AUDIENCE"];
if (!string.IsNullOrWhiteSpace(keycloakAuthority) && !string.IsNullOrWhiteSpace(keycloakAudience))
{
    builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
    {
        options.Authority = keycloakAuthority;
        options.Audience = keycloakAudience;
        options.MapInboundClaims = false;
        options.RequireHttpsMetadata = !builder.Environment.IsDevelopment();
    });
}

var app = builder.Build();
app.UseCors();
if (!string.IsNullOrWhiteSpace(keycloakAuthority) && !string.IsNullOrWhiteSpace(keycloakAudience))
{
    app.UseAuthentication();
    app.UseAuthorization();
}
if (!string.IsNullOrWhiteSpace(databaseUrl))
{
    await using var scope = app.Services.CreateAsyncScope();
    var database = scope.ServiceProvider.GetRequiredService<IDbContextFactory<ProgressDbContext>>();
    await using var context = await database.CreateDbContextAsync();
    await context.Database.EnsureCreatedAsync();
    await EnsureLearningExperienceSchema(context);
}
app.MapGet("/health", () => Results.Ok(new { status = "ok", courseVersion = Curriculum.Version }));
app.MapGet("/openapi/v1.json", () => Results.Ok(new { openapi = "3.0.3", info = new { title = "Pathway API", version = "v1" } }));
app.MapGet("/api/courses", () => Results.Ok(Curriculum.Catalog));
app.MapGet("/api/courses/{courseId}", (string courseId) => Curriculum.Courses.TryGetValue(courseId, out var course) ? Results.Ok(course) : Results.NotFound());
app.MapGet("/api/lessons/{slug}", (string slug) => Curriculum.BySlug.TryGetValue(slug, out var lesson) ? Results.Ok(lesson) : Results.NotFound());
var progressEndpoint = app.MapGet("/api/progress", async (HttpContext httpContext, IServiceProvider services, CancellationToken cancellationToken) =>
{
    var learnerId = await ResolveLearnerId(httpContext, services, cancellationToken);
    var factory = services.GetService<IDbContextFactory<ProgressDbContext>>();
    if (factory is null) return Results.Ok(new LearnerProgressResponse(learnerId, []));
    await using var database = await factory.CreateDbContextAsync(cancellationToken);
    var completed = await database.Progress.Where(item => item.LearnerId == learnerId).OrderBy(item => item.CompletedAt).Select(item => item.LessonSlug).ToArrayAsync(cancellationToken);
    return Results.Ok(new LearnerProgressResponse(learnerId, completed));
});
var submissionEndpoint = app.MapPost("/api/submissions/validate", async (Submission submission, HttpContext httpContext, IServiceProvider services, IHttpClientFactory httpClientFactory, IConfiguration configuration, IHostEnvironment environment, CancellationToken cancellationToken) =>
{
    if (!Curriculum.BySlug.TryGetValue(submission.LessonSlug, out var lesson)) return Results.NotFound();
    if (lesson.Exercise.Kind == ExerciseKind.Code && !string.IsNullOrWhiteSpace(configuration["EVALUATOR_URL"]))
    {
        var client = httpClientFactory.CreateClient();
        try
        {
            var runnerResponse = await client.PostAsJsonAsync($"{configuration["EVALUATOR_URL"]!.TrimEnd('/')}/evaluate", new EvaluatorRequest(submission.LessonSlug, submission.Code ?? string.Empty), cancellationToken);
            if (runnerResponse.IsSuccessStatusCode)
            {
                var evaluated = await runnerResponse.Content.ReadFromJsonAsync<ValidationResult>(cancellationToken: cancellationToken);
                if (evaluated is not null)
                {
                    var reviewed = evaluated with { CodeReview = evaluated.CodeReview ?? BuildCodeReview(lesson, submission.Code ?? string.Empty) };
                    await PersistSubmission(services, await ResolveLearnerId(httpContext, services, cancellationToken), submission, reviewed.Passed, cancellationToken);
                    return Results.Ok(reviewed);
                }
            }
            return Results.Problem("The code evaluator did not return a usable result.", statusCode: StatusCodes.Status503ServiceUnavailable);
        }
        catch (HttpRequestException)
        {
            return Results.Problem("The code evaluator is temporarily unavailable.", statusCode: StatusCodes.Status503ServiceUnavailable);
        }
    }
    // Development-only deterministic checks make local lesson authoring fast. In production,
    // set EVALUATOR_URL to a private sandbox worker; never execute learner code in this API.
    if (lesson.Exercise.Kind == ExerciseKind.Code && environment.IsProduction())
        return Results.Ok(new ValidationResult(false, 0, 0, "Automated execution is not configured yet. Your static code review is ready below; a sandbox evaluator is required before code can be marked complete.", null, BuildCodeReview(lesson, submission.Code ?? string.Empty)));
    var validation = lesson.Exercise.Kind switch
    {
        ExerciseKind.MultipleChoice => ValidateChoice(lesson, submission.Answer),
        ExerciseKind.Code => ValidateCode(lesson, submission.Code ?? string.Empty),
        _ => new ValidationResult(false, 0, 1, "This exercise type is not supported yet.", null)
    };
    await PersistSubmission(services, await ResolveLearnerId(httpContext, services, cancellationToken), submission, validation.Passed, cancellationToken);
    return Results.Ok(validation);
});
var experienceEndpoints = app.MapLearningExperienceEndpoints();
if (!string.IsNullOrWhiteSpace(keycloakAuthority) && !string.IsNullOrWhiteSpace(keycloakAudience)) { progressEndpoint.RequireAuthorization(); submissionEndpoint.RequireAuthorization(); experienceEndpoints.RequireAuthorization(); }
app.Run();

static Task<string> ResolveLearnerId(HttpContext context, IServiceProvider services, CancellationToken cancellationToken)
{
    var subject = context.User.FindFirstValue("sub");
    return Task.FromResult(!string.IsNullOrWhiteSpace(subject) ? $"keycloak:{subject}" : context.Request.Headers["X-Learner-Id"].FirstOrDefault() is { Length: > 0 and <= 100 } learnerId ? learnerId : "anonymous");
}

static async Task PersistSubmission(IServiceProvider services, string learnerId, Submission submission, bool passed, CancellationToken cancellationToken)
{
    var factory = services.GetService<IDbContextFactory<ProgressDbContext>>();
    if (factory is null) return;
    await using var database = await factory.CreateDbContextAsync(cancellationToken);
    database.Submissions.Add(new LearnerSubmission { LearnerId = learnerId, LessonSlug = submission.LessonSlug, Answer = submission.Answer, Code = submission.Code, Passed = passed });
    if (passed && !await database.Progress.AnyAsync(item => item.LearnerId == learnerId && item.LessonSlug == submission.LessonSlug, cancellationToken))
        database.Progress.Add(new LearnerProgress { LearnerId = learnerId, LessonSlug = submission.LessonSlug, CompletedAt = DateTimeOffset.UtcNow });
    if (passed)
    {
        var existingReview = await database.ReviewSchedules.SingleOrDefaultAsync(item => item.LearnerId == learnerId && item.LessonSlug == submission.LessonSlug, cancellationToken);
        if (existingReview is null)
            database.ReviewSchedules.Add(new ReviewSchedule { LearnerId = learnerId, LessonSlug = submission.LessonSlug, IntervalDays = 1, LastReviewedAt = DateTimeOffset.UtcNow, DueAt = DateTimeOffset.UtcNow.AddDays(1) });
        else
        {
            existingReview.IntervalDays = Math.Min(existingReview.IntervalDays * 2, 30);
            existingReview.LastReviewedAt = DateTimeOffset.UtcNow;
            existingReview.DueAt = DateTimeOffset.UtcNow.AddDays(existingReview.IntervalDays);
        }
    }
    await database.SaveChangesAsync(cancellationToken);
}

static string ToNpgsqlConnectionString(string value)
{
    if (!Uri.TryCreate(value, UriKind.Absolute, out var uri) || (uri.Scheme != "postgres" && uri.Scheme != "postgresql")) return value;
    var userInfo = uri.UserInfo.Split(':', 2);
    var builder = new Npgsql.NpgsqlConnectionStringBuilder { Host = uri.Host, Port = uri.Port, Database = uri.AbsolutePath.Trim('/'), Username = Uri.UnescapeDataString(userInfo[0]), Password = userInfo.Length > 1 ? Uri.UnescapeDataString(userInfo[1]) : string.Empty, SslMode = Npgsql.SslMode.Require };
    return builder.ConnectionString;
}

static async Task EnsureLearningExperienceSchema(ProgressDbContext database) => await database.Database.ExecuteSqlRawAsync("""
    CREATE TABLE IF NOT EXISTS workspace_projects (
        "Id" uuid PRIMARY KEY, "LearnerId" character varying(100) NOT NULL, "TemplateId" character varying(100) NOT NULL,
        "Title" character varying(160) NOT NULL, "UpdatedAt" timestamp with time zone NOT NULL);
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_workspace_projects_LearnerId_TemplateId" ON workspace_projects ("LearnerId", "TemplateId");
    CREATE TABLE IF NOT EXISTS workspace_files (
        "Id" uuid PRIMARY KEY, "ProjectId" uuid NOT NULL, "Path" character varying(260) NOT NULL,
        "Content" character varying(100000) NOT NULL, "UpdatedAt" timestamp with time zone NOT NULL);
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_workspace_files_ProjectId_Path" ON workspace_files ("ProjectId", "Path");
    CREATE TABLE IF NOT EXISTS review_schedules (
        "Id" uuid PRIMARY KEY, "LearnerId" character varying(100) NOT NULL, "LessonSlug" character varying(200) NOT NULL,
        "IntervalDays" integer NOT NULL, "DueAt" timestamp with time zone NOT NULL, "LastReviewedAt" timestamp with time zone NOT NULL);
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_review_schedules_LearnerId_LessonSlug" ON review_schedules ("LearnerId", "LessonSlug");
    CREATE TABLE IF NOT EXISTS community_posts (
        "Id" uuid PRIMARY KEY, "AuthorId" character varying(100) NOT NULL, "CourseId" character varying(100) NOT NULL,
        "Title" character varying(180) NOT NULL, "Body" character varying(10000) NOT NULL, "NeedsMentor" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL);
    CREATE INDEX IF NOT EXISTS "IX_community_posts_CourseId_CreatedAt" ON community_posts ("CourseId", "CreatedAt");
    CREATE TABLE IF NOT EXISTS community_replies (
        "Id" uuid PRIMARY KEY, "PostId" uuid NOT NULL, "AuthorId" character varying(100) NOT NULL,
        "Body" character varying(10000) NOT NULL, "IsMentor" boolean NOT NULL, "CreatedAt" timestamp with time zone NOT NULL);
    CREATE INDEX IF NOT EXISTS "IX_community_replies_PostId_CreatedAt" ON community_replies ("PostId", "CreatedAt");
    """);

static ValidationResult ValidateChoice(Lesson lesson, string? answer)
{
    var passed = string.Equals(answer, lesson.Exercise.CorrectAnswer, StringComparison.Ordinal);
    return new ValidationResult(passed, passed ? 1 : 0, 1, passed ? "That’s right. You’ve got the idea." : "Not quite—re-read the example and try again.", passed ? lesson.NextSlug : null);
}
static ValidationResult ValidateCode(Lesson lesson, string code)
{
    if (lesson.Slug.StartsWith("python-", StringComparison.Ordinal))
    {
        var pythonPassed = lesson.Slug switch
        {
            "python-functions" => code.Contains("def greet", StringComparison.Ordinal) && code.Contains("return", StringComparison.Ordinal),
            "python-fastapi-endpoint" => code.Contains("@app.get", StringComparison.Ordinal) && code.Contains("def", StringComparison.Ordinal),
            _ => false
        };
        return new ValidationResult(pythonPassed, pythonPassed ? 2 : 0, 2, pythonPassed ? "All tests passed. Your Python solution meets this lesson’s checks." : lesson.Exercise.Hint, pythonPassed ? lesson.NextSlug : null, BuildCodeReview(lesson, code));
    }
    var syntaxError = CSharpSyntaxTree.ParseText(code, new CSharpParseOptions(LanguageVersion.Preview))
        .GetDiagnostics()
        .FirstOrDefault(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    if (syntaxError is not null)
        return new ValidationResult(false, 0, 2, $"C# syntax error: {syntaxError.GetMessage()}", null, BuildCodeReview(lesson, code));
    var passed = lesson.Slug switch
    {
        "foundations-making-decisions" => code.Contains("if", StringComparison.Ordinal) && code.Contains("age >= 13", StringComparison.Ordinal) && code.Contains("You can watch!", StringComparison.Ordinal),
        "modern-csharp-records" => code.Contains("record", StringComparison.Ordinal) && code.Contains("Order", StringComparison.Ordinal),
        "web-api-sealed-services" => code.Contains("sealed class", StringComparison.Ordinal) && code.Contains("IOrderService", StringComparison.Ordinal) && code.Contains("CancellationToken", StringComparison.Ordinal),
        _ => false
    };
    var message = passed ? "All tests passed. Your solution meets this lesson’s checks." : lesson.Exercise.Hint;
    return new ValidationResult(passed, passed ? 2 : 0, 2, message, passed ? lesson.NextSlug : null, BuildCodeReview(lesson, code));
}

static CodeReview BuildCodeReview(Lesson lesson, string code)
{
    var suggestions = new List<string>();
    var lines = code.Split('\n');
    if (lines.Any(line => line.Length > 120)) suggestions.Add("Keep lines under roughly 120 characters where practical so code remains easy to scan in reviews and diffs.");

    if (lesson.Slug.StartsWith("python-", StringComparison.Ordinal))
    {
        if (code.Contains(" == True", StringComparison.Ordinal) || code.Contains(" == False", StringComparison.Ordinal)) suggestions.Add("Prefer direct truthiness (`if value:` or `if not value:`) over comparing a boolean to `True` or `False`.");
        if (code.Contains("except Exception", StringComparison.Ordinal)) suggestions.Add("Catch the narrowest exception you can handle; a broad `except Exception` can hide programming errors.");
        if (code.Contains(" + \"", StringComparison.Ordinal) || code.Contains("\" +", StringComparison.Ordinal)) suggestions.Add("For user-facing string composition, an f-string is usually clearer than chained `+` concatenation.");
        if (code.Contains("def ", StringComparison.Ordinal) && !code.Contains(" -> ", StringComparison.Ordinal)) suggestions.Add("Consider a return type annotation for public functions so readers and type checkers can verify the contract.");
    }
    else
    {
        if (code.Contains("string.Format(", StringComparison.Ordinal)) suggestions.Add("Prefer interpolated strings (`$\"...\"`) to `string.Format` when formatting a small, readable message.");
        if (code.Contains(" == null", StringComparison.Ordinal) || code.Contains(" != null", StringComparison.Ordinal)) suggestions.Add("Consider pattern matching (`is null` / `is not null`) for modern, intention-revealing null checks.");
        if (code.Contains(".Count() > 0", StringComparison.Ordinal)) suggestions.Add("Prefer `.Any()` when you only need to know whether an enumerable contains an item.");
        if (code.Contains("new List<", StringComparison.Ordinal) && code.Contains("{", StringComparison.Ordinal)) suggestions.Add("When targeting modern C#, consider a collection expression (`[]`) where it makes collection initialization simpler.");
    }

    var summary = suggestions.Count == 0
        ? "No readability or idiom concerns detected by the lightweight review. A human reviewer should still evaluate names, domain fit, and edge cases."
        : $"{suggestions.Count} focused suggestion{(suggestions.Count == 1 ? string.Empty : "s")} found. These are advisory and do not change your test result.";
    return new CodeReview(summary, suggestions.ToArray());
}

record CourseCatalogItem(string Id, string Title, string LanguageId, string LanguageVersion, string FrameworkVersion, bool Available);
record Course(string Id, string Title, string LanguageId, string LanguageVersion, string FrameworkVersion, string LastReviewed, IReadOnlyList<Module> Modules);
record Module(string Id, string Title, string Level, IReadOnlyList<LessonSummary> Lessons);
record LessonSummary(string Slug, string Title, int Order);
record Lesson(string Slug, string Module, int Order, string Title, string Subtitle, string Concept, string Body, string Example, Exercise Exercise, string? NextSlug, VersionStamp Version);
record VersionStamp(string Language, string Framework, string LastReviewed, string SourceUrl);
record Exercise(ExerciseKind Kind, string Title, string Prompt, string[] Requirements, string? StarterCode, string? CorrectAnswer, Choice[] Choices, string Hint, string[] Tests);
record Choice(string Id, string Text);
record Submission(string LessonSlug, string? Answer, string? Code);
record LearnerProgressResponse(string LearnerId, string[] CompletedLessonSlugs);
record EvaluatorRequest(string LessonSlug, string Code);
record CodeReview(string Summary, string[] Suggestions);
record ValidationResult(bool Passed, int PassingTests, int TotalTests, string Feedback, string? NextLessonSlug, CodeReview? CodeReview = null);
enum ExerciseKind { MultipleChoice, Code }

static class Curriculum
{
    public const string Version = "C# 14 / .NET 10";
    private static readonly VersionStamp Current = new("C# 14", ".NET 10", "2026-08-12", "https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-14");
    public static readonly Lesson[] Lessons =
    [
        new("foundations-how-code-works", "Foundations", 1, "How code works", "Give the computer one clear instruction at a time.", "A program is a precise sequence of instructions.", "C# programs run from top to bottom. `Console.WriteLine` asks the program to show a message.", "Console.WriteLine(\"Hello, Pathway!\");", new(ExerciseKind.MultipleChoice, "Read the program", "What does this line do?", ["Choose one answer"], null, "print", [new("store", "Stores a message for later"), new("print", "Prints a message to the console"), new("loop", "Repeats the message forever")], "Look at the word after the dot: `WriteLine`.", ["Identifies console output"]), "foundations-values", Current),
        new("foundations-values", "Foundations", 2, "Values & variables", "Name information so your program can use it.", "Variables give a value a meaningful name.", "Choose a type that describes the value. Use `string` for text and `int` for whole numbers.", "string learner = \"Alex\";\nint completedLessons = 4;", new(ExerciseKind.MultipleChoice, "Choose a type", "Which type is best for a whole-number lesson count?", ["Choose one answer"], null, "int", [new("string", "string"), new("int", "int"), new("bool", "bool")], "A lesson count has no decimal places.", ["Uses a whole-number type"]), "foundations-making-decisions", Current),
        new("foundations-making-decisions", "Foundations", 3, "Making decisions", "Use conditions to choose a path.", "A boolean expression evaluates to `true` or `false`.", "An `if` statement runs its body only when its condition is true. Read it like a sentence.", "if (age >= 13)\n{\n    Console.WriteLine(\"Welcome in!\");\n}", new(ExerciseKind.Code, "Movie night", "Print `You can watch!` only when `age` is 13 or above.", ["Use an `if` statement", "Use `age >= 13`", "Print the exact message"], "int age = 16;\n\n// Write your if statement below\n", null, [], "Check the condition uses `age >= 13`, then call `Console.WriteLine` inside the braces.", ["Prints message at 13", "Does not print under 13"]), "modern-csharp-records", Current),
        new("modern-csharp-records", "Modern C#", 4, "Model data with records", "Use value-based data types for immutable messages and responses.", "Records express data-focused types with value equality.", "A positional record is a concise choice for immutable request, response, and message DTOs. Use `with` to create a changed copy rather than mutating the original.", "public sealed record OrderResponse(Guid Id, string Status);\n\nvar shipped = order with { Status = \"Shipped\" };", new(ExerciseKind.Code, "Order response", "Declare an `Order` record with an `Id` and a `Status`.", ["Use the `record` keyword", "Name the type `Order`", "Include `Id` and `Status`"], "// Create a data-focused Order type\n", null, [], "Start with: `public sealed record Order(...)`. Choose suitable types for the two values.", ["Declares a record", "Uses the expected type name"]), "web-api-sealed-services", Current),
        new("web-api-sealed-services", "Web APIs", 5, "Design closed Web API types", "Default to closed concrete types; open types deliberately.", "`sealed` prevents unintended inheritance. Prefer composition and interfaces for variation.", "For a concrete application service or controller that is not designed as an extension point, `sealed` makes that decision explicit. It is not a universal rule: don’t seal framework extension points, deliberately extensible libraries, or types that must be proxied. Use constructor injection and accept `CancellationToken` at I/O boundaries.", "public sealed class OrdersController(IOrderService orders) : ControllerBase\n{\n    public async Task<OrderResponse> Get(Guid id, CancellationToken cancellationToken)\n        => await orders.GetAsync(id, cancellationToken);\n}", new(ExerciseKind.Code, "Close the service", "Create a sealed `OrderService` that implements `IOrderService` and accepts a `CancellationToken` in an async operation.", ["Declare a `sealed class`", "Implement `IOrderService`", "Accept `CancellationToken`"], "// Prefer composition over inheritance.\n", null, [], "Use `public sealed class OrderService : IOrderService`. Add an async method with a `CancellationToken` parameter.", ["Prevents inheritance", "Supports cancellation"]), "modern-csharp-switch-expressions", Current),
        new("modern-csharp-switch-expressions", "Modern C#", 6, "Express branches as values", "Use switch expressions when every case produces a value.", "A switch expression is compact and encourages exhaustive handling.", "When a decision maps an input to one result, a switch expression is often clearer than a multi-branch `if` chain. Add a discard arm when unknown values have a safe fallback.", "var label = status switch\n{\n    OrderStatus.Paid => \"Ready to ship\",\n    OrderStatus.Cancelled => \"Cancelled\",\n    _ => \"Pending\"\n};", new(ExerciseKind.MultipleChoice, "Pick the pattern", "When is a switch expression a strong fit?", ["Choose the best answer"], null, "maps", [new("maps", "When several input cases each produce one value"), new("sideeffects", "When each branch performs unrelated side effects"), new("inheritance", "When a class needs a base type")], "Look for a decision that returns a value for each input case.", ["Recognizes value mapping"]), "modern-csharp-primary-constructors", Current),
        new("modern-csharp-primary-constructors", "Modern C#", 7, "Use primary constructors deliberately", "Keep dependency declarations close to the type they support.", "Primary constructors reduce ceremony for types whose constructor parameters are used by instance members.", "In application services, primary constructors make injected dependencies visible at the type declaration. Avoid retaining inputs you do not need; use normal constructors when validation or construction logic is substantial.", "public sealed class PriceService(IExchangeRateClient rates)\n{\n    public Task<decimal> ConvertAsync(decimal amount, CancellationToken ct)\n        => rates.ConvertAsync(amount, ct);\n}", new(ExerciseKind.MultipleChoice, "Choose the fit", "When is a primary constructor most useful?", ["Choose the best answer"], null, "dependency", [new("dependency", "A small service stores and uses an injected dependency"), new("complex", "A type needs complex validation before any fields are assigned"), new("static", "A static helper has no instance state")], "Look for a compact type with straightforward dependencies.", ["Identifies a primary constructor use case"]), "modern-csharp-ranges", Current),
        new("modern-csharp-ranges", "Modern C#", 8, "Slice safely with ranges", "Use ranges to express positions and slices clearly.", "The range operator `..` describes a start and end; the index-from-end operator `^` counts backward.", "Ranges make intent clear for strings, arrays, and spans. For performance-sensitive work, understand whether an API allocates or returns a view; `Span<T>` and `ReadOnlySpan<T>` are central tools for efficient parsing.", "var lastFour = cardNumber[^4..];\nvar prefix = cardNumber[..4];", new(ExerciseKind.MultipleChoice, "Read the range", "What does `values[^2..]` select?", ["Choose one answer"], null, "last", [new("first", "The first two values"), new("last", "The final two values"), new("all", "Every value except the final two")], "`^2` means two positions from the end.", ["Reads from-end indexes"]), "web-api-minimal-or-controller", Current),
        new("web-api-minimal-or-controller", "Web APIs", 9, "Choose an HTTP endpoint style", "Use the simplest API style that preserves clarity.", "ASP.NET Core supports Minimal APIs and controller-based APIs.", "Minimal APIs are excellent for small, focused endpoints. Controllers can organize larger endpoint groups and cross-cutting conventions. Both should validate input, return appropriate HTTP semantics, honor cancellation, and keep business rules out of the endpoint.", "app.MapGet(\"/orders/{id:guid}\", async (Guid id, IOrderService orders, CancellationToken ct)\n    => await orders.GetAsync(id, ct) is { } order ? Results.Ok(order) : Results.NotFound());", new(ExerciseKind.MultipleChoice, "Choose the shape", "Which is a good reason to choose a controller?", ["Choose one answer"], null, "organization", [new("organization", "A large API benefits from grouped actions and shared conventions"), new("speed", "Controllers make all requests faster"), new("inheritance", "Every endpoint must inherit from a base controller")], "Think about organization and conventions, not a universal performance claim.", ["Selects an API style intentionally"]), "quality-tests", Current),
        new("quality-tests", "Engineering Practice", 10, "Prove behavior with tests", "Tests protect behavior, not implementation trivia.", "A useful test names a behavior and gives clear failure feedback.", "Write focused unit tests for domain logic and integration tests for behavior at boundaries—HTTP, databases, queues, and authentication. Test the observable contract; avoid coupling tests to private implementation details.", "[Fact]\npublic async Task Get_returns_404_when_order_is_missing()\n{\n    var response = await _client.GetAsync(\"/orders/not-found\");\n    response.StatusCode.Should().Be(HttpStatusCode.NotFound);\n}", new(ExerciseKind.MultipleChoice, "Test the contract", "What should an endpoint integration test assert first?", ["Choose one answer"], null, "observable", [new("observable", "The status code and response contract a client can observe"), new("private", "The endpoint’s private helper method order"), new("logging", "An exact timestamp in every log message")], "A client cannot rely on private implementation details.", ["Focuses on observable behavior"]), "reliability-cancellation", Current),
        new("reliability-cancellation", "Reliability", 11, "Propagate cancellation", "Stop work when the caller no longer needs it.", "`CancellationToken` is a cooperative signal, not an exception to ignore.", "Accept a token at request and job boundaries, then pass it to database, HTTP, and async APIs that support it. Don’t create a new token deep in the call chain. Treat cancellation as expected control flow, not an application error.", "public Task<Order?> GetAsync(Guid id, CancellationToken ct)\n    => _db.Orders.SingleOrDefaultAsync(x => x.Id == id, ct);", new(ExerciseKind.MultipleChoice, "Follow the token", "What should a request handler do with its cancellation token?", ["Choose one answer"], null, "propagate", [new("propagate", "Pass it to downstream async and I/O calls"), new("ignore", "Ignore it because the server can finish later"), new("replace", "Create a new token for every method")], "Cancellation only helps if work that can stop receives the token.", ["Propagates cancellation"]), "staff-architecture-decisions", Current),
        new("staff-architecture-decisions", "Staff Practice", 12, "Make architecture decisions legible", "A staff engineer turns ambiguity into reversible, evidence-backed decisions.", "An architecture decision record captures context, decision, consequences, and alternatives.", "At staff level, the job is not to choose the fanciest system. State the constraints, quantify trade-offs, design for operational ownership, and choose the smallest approach that can meet the real need. Make the decision easy to revisit when assumptions change.", "# ADR 012: process order events asynchronously\nContext: checkout p95 latency is rising.\nDecision: queue non-critical notifications.\nConsequences: eventual consistency; add retry and observability.", new(ExerciseKind.MultipleChoice, "Choose the staff move", "What is the strongest first step when a system needs to scale?", ["Choose one answer"], null, "constraints", [new("constraints", "Measure the bottleneck and state the product and operational constraints"), new("rewrite", "Rewrite every service into microservices"), new("cache", "Add a cache before observing the workload")], "Staff-level decisions begin with evidence and constraints.", ["Frames a decision with evidence"]), null, Current)
    ];
    private static readonly VersionStamp PythonCurrent = new("Python 3.14", "FastAPI / Flask / Django", "2026-08-13", "https://docs.python.org/3.14/whatsnew/");
    public static readonly Lesson[] PythonLessons =
    [
        new("python-values", "Python foundations", 1, "Values and variables", "Give values names that reveal their purpose.", "Python variables refer to objects; clear names beat clever abbreviations.", "Start with small, readable expressions. Use f-strings when formatting user-facing text.", "learner = \"Ada\"\ncompleted_lessons = 4\nprint(f\"{learner} has completed {completed_lessons} lessons.\")", new(ExerciseKind.MultipleChoice, "Read the value", "What is `completed_lessons` in this example?", ["Choose one answer"], null, "integer", [new("integer", "An integer value"), new("function", "A function declaration"), new("module", "An imported module")], "It is assigned the whole number 4.", ["Recognizes a basic value"]), "python-functions", PythonCurrent),
        new("python-functions", "Python foundations", 2, "Functions with clear contracts", "Turn repeated behavior into a named, testable unit.", "A function should have a focused purpose, explicit inputs, and a useful return value.", "Use type hints to communicate intent; validate input at boundaries rather than scattering checks throughout your code.", "def greet(name: str) -> str:\n    return f\"Hello, {name}!\"", new(ExerciseKind.Code, "Write a greeting", "Create `greet(name)` that returns a greeting string.", ["Define `greet`", "Accept `name`", "Return a value"], "def greet(name: str) -> str:\n    # return a greeting\n    pass\n", null, [], "Define `greet` and return an f-string instead of printing from the function.", ["Defines function", "Returns greeting"]), "python-data-models", PythonCurrent),
        new("python-data-models", "Python foundations", 3, "Model data deliberately", "Choose the simplest shape that preserves meaning.", "Dataclasses and typed models make domain data easier to understand and validate.", "Use `@dataclass(frozen=True)` for small immutable domain values; use Pydantic models at API boundaries where parsing and validation matter.", "from dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass Lesson:\n    title: str\n    minutes: int", new(ExerciseKind.MultipleChoice, "Choose the boundary", "Where is a Pydantic model most valuable?", ["Choose one answer"], null, "boundary", [new("boundary", "Parsing and validating external API input"), new("loop", "Replacing every loop"), new("inheritance", "Making every class extensible")], "Think about data that enters from outside your trusted code.", ["Recognizes boundary validation"]), "python-tests-errors", PythonCurrent),
        new("python-tests-errors", "Python foundations", 4, "Test behavior and handle errors", "Make failure modes explicit and observable.", "Tests describe the behavior a caller can rely on.", "Use pytest for focused behavior tests. Raise domain-specific exceptions only when callers can recover; translate them to HTTP responses at the API boundary.", "def test_greet_returns_name():\n    assert greet(\"Ada\") == \"Hello, Ada!\"", new(ExerciseKind.MultipleChoice, "Test the contract", "What should a unit test assert first?", ["Choose one answer"], null, "behavior", [new("behavior", "An observable result of the function"), new("private", "The exact private helper call order"), new("style", "Whitespace formatting")], "Test what consumers observe.", ["Tests observable behavior"]), "python-http", PythonCurrent),
        new("python-http", "Web foundations", 5, "Understand HTTP before frameworks", "HTTP semantics are part of your public contract.", "Methods, status codes, headers, and idempotency shape how clients safely interact with your service.", "Use GET for safe reads, POST for creating work, and meaningful 4xx/5xx responses. Validate request data and return stable response shapes.", "GET /lessons/42 HTTP/1.1\nAccept: application/json\n\nHTTP/1.1 200 OK\nContent-Type: application/json", new(ExerciseKind.MultipleChoice, "Choose the status", "Which status fits a successfully created resource?", ["Choose one answer"], null, "created", [new("created", "201 Created"), new("missing", "404 Not Found"), new("server", "500 Internal Server Error")], "Creation has its own success status.", ["Uses HTTP creation semantics"]), "python-framework-choice", PythonCurrent),
        new("python-framework-choice", "Web foundations", 6, "Choose a Python web framework", "Pick the smallest framework that fits your product and team.", "FastAPI, Flask, and Django optimize for different constraints.", "FastAPI is a strong default for typed async APIs, validation, and generated OpenAPI. Flask is minimal and flexible when you want to compose your own stack. Django is batteries-included: ORM, migrations, auth, admin, and templates—excellent when those conventions accelerate a data-heavy product. Avoid selecting by popularity alone; consider team experience, operational ownership, and the surrounding ecosystem.", "# FastAPI: typed API + validation\n# Flask: minimal WSGI composition\n# Django: integrated product framework", new(ExerciseKind.MultipleChoice, "Pick the tradeoff", "Which is the best reason to choose Django?", ["Choose one answer"], null, "django", [new("django", "You benefit from its ORM, migrations, auth, and admin conventions"), new("fast", "It makes every API request faster"), new("async", "It removes every async design decision")], "Choose based on the product capabilities its conventions provide.", ["Evaluates framework tradeoffs"]), "python-fastapi-endpoint", PythonCurrent),
        new("python-fastapi-endpoint", "API delivery", 7, "Build a typed FastAPI endpoint", "Use types and models to make an API contract executable.", "FastAPI turns annotations and Pydantic models into validation and OpenAPI documentation.", "Keep route handlers thin: parse input, call an application service, map expected failures to HTTP. Inject dependencies explicitly so tests can replace them.", "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get(\"/health\")\ndef health() -> dict[str, str]:\n    return {\"status\": \"ok\"}", new(ExerciseKind.Code, "Add a health endpoint", "Create a FastAPI GET endpoint using `@app.get`.", ["Use `@app.get`", "Define a function", "Return a value"], "from fastapi import FastAPI\n\napp = FastAPI()\n\n# add GET /health below\n", null, [], "Decorate a function with `@app.get(\"/health\")` and return a dictionary.", ["Declares route", "Returns response"]), "python-flask-composition", PythonCurrent),
        new("python-flask-composition", "API delivery", 8, "Compose a Flask service", "Flask gives you primitives; your architecture supplies the discipline.", "Application factories and blueprints keep a Flask codebase testable as it grows.", "Use an application factory to create configuration-specific apps. Group routes in blueprints, keep business rules outside views, and add extensions deliberately rather than globally by accident.", "def create_app() -> Flask:\n    app = Flask(__name__)\n    app.register_blueprint(health_bp)\n    return app", new(ExerciseKind.MultipleChoice, "Choose the Flask shape", "Why use an application factory?", ["Choose one answer"], null, "factory", [new("factory", "Create isolated app configurations for tests and environments"), new("global", "Avoid all configuration"), new("async", "Make every handler asynchronous")], "Think about test isolation and environment-specific configuration.", ["Uses application factory"]), "python-django-product", PythonCurrent),
        new("python-django-product", "API delivery", 9, "Use Django as a product framework", "Leverage conventions when the product needs them.", "Django’s ORM, migrations, admin, auth, and security defaults can shorten the path to a maintainable product.", "Keep models focused on persistence and invariants; place cross-aggregate workflows in services. Treat migrations as reviewed, deployable artifacts—not generated noise.", "class Lesson(models.Model):\n    title = models.CharField(max_length=200)\n    published_at = models.DateTimeField(null=True)", new(ExerciseKind.MultipleChoice, "Protect schema changes", "What belongs in code review with a model change?", ["Choose one answer"], null, "migration", [new("migration", "The generated migration and its rollout impact"), new("admin", "Only the admin page colors"), new("cache", "A cache added without measurement")], "Database changes are production changes.", ["Reviews migrations"]), "python-persistence", PythonCurrent),
        new("python-persistence", "Production systems", 10, "Design persistence and migrations", "A database is a shared, evolving contract.", "Schema changes must be backwards-compatible during rolling deployments.", "Use transactions around a single business operation, add indexes based on measured queries, and expand-then-contract destructive schema changes. Never run an irreversible data migration without a rollback or recovery plan.", "# expand: add nullable column\n# deploy code that writes both forms\n# backfill safely\n# contract: remove old column later", new(ExerciseKind.MultipleChoice, "Plan the rollout", "What is the safest first step for a breaking schema change?", ["Choose one answer"], null, "expand", [new("expand", "Add a backwards-compatible shape before removing the old one"), new("drop", "Drop the old column first"), new("freeze", "Stop all deploys permanently")], "Rolling deploys need old and new code to coexist.", ["Uses expand-contract"]), "python-concurrency", PythonCurrent),
        new("python-concurrency", "Production systems", 11, "Use concurrency intentionally", "Async I/O, workers, and processes solve different problems.", "Concurrency is a capacity and correctness decision, not a style preference.", "Use async for many waiting I/O operations when your dependencies support it. Move durable, retryable background work to a queue. Use processes or purpose-built compute infrastructure for CPU-bound work; measure saturation, queue delay, and failure behavior.", "async def fetch_profile(client: httpx.AsyncClient, user_id: str) -> Profile:\n    response = await client.get(f\"/profiles/{user_id}\")\n    response.raise_for_status()\n    return Profile.model_validate(response.json())", new(ExerciseKind.MultipleChoice, "Choose the tool", "Where should a retryable email send usually run?", ["Choose one answer"], null, "queue", [new("queue", "A durable background queue with retries and observability"), new("request", "Inside the user-facing request forever"), new("thread", "An untracked thread")], "Durable work needs durable ownership.", ["Uses durable background work"]), "python-security-observability", PythonCurrent),
        new("python-security-observability", "Production systems", 12, "Secure and observe the service", "Production quality is evidence, not hope.", "Security, structured logs, metrics, traces, and health signals are design constraints.", "Validate untrusted input, use parameterized queries, keep secrets out of source and logs, set timeouts on network calls, and emit structured events with correlation IDs. Define SLOs around user-visible behavior before choosing alerts.", "logger.info(\"order_created\", extra={\"order_id\": order.id, \"request_id\": request_id})", new(ExerciseKind.MultipleChoice, "Choose the signal", "What makes a useful operational alert?", ["Choose one answer"], null, "slo", [new("slo", "It indicates sustained user-impacting SLO risk"), new("noise", "It fires for every debug log"), new("secret", "It includes credentials for convenience")], "Alerts should prompt action, not create background noise.", ["Designs actionable alerts"]), "python-project-foundations", PythonCurrent),
        new("python-staff-architecture", "Staff practice", 33, "Lead Python systems at staff level", "Turn technical ambiguity into an operable decision.", "Staff engineers clarify constraints, make tradeoffs legible, and create leverage for teams.", "For a Python platform, make runtime versions, dependency policy, delivery standards, observability, and ownership explicit. Choose monolith, modular monolith, services, queues, or workflows based on measured constraints. Write decisions with context, alternatives, consequences, rollout, and reversal signals.", "# ADR: Extract notifications behind a queue\n# Context: checkout latency and retry ownership\n# Decision: asynchronous delivery with idempotency keys\n# Revisit when: queue delay exceeds SLO", new(ExerciseKind.MultipleChoice, "Make the staff move", "What should come before splitting a Python service?", ["Choose one answer"], null, "evidence", [new("evidence", "Measure the bottleneck, ownership boundaries, and operational tradeoffs"), new("rewrite", "Rewrite everything as microservices"), new("trend", "Copy the newest architecture trend")], "Staff decisions start with evidence and a reversible plan.", ["Frames an architecture decision"]), null, PythonCurrent)
    ];
    private static readonly VersionStamp PythonDocs = new("Python 3.14", "Standard library", "2026-08-13", "https://docs.python.org/3.14/");
    private static readonly VersionStamp FastApiDocs = new("Python 3.14", "FastAPI", "2026-08-13", "https://fastapi.tiangolo.com/");
    private static readonly VersionStamp FlaskDocs = new("Python 3.14", "Flask 3.1", "2026-08-13", "https://flask.palletsprojects.com/en/stable/");
    private static readonly VersionStamp DjangoDocs = new("Python 3.14", "Django 6.0", "2026-08-13", "https://docs.djangoproject.com/en/6.0/");
    private static readonly VersionStamp PytestDocs = new("Python 3.14", "pytest", "2026-08-13", "https://docs.pytest.org/en/stable/");
    public static readonly Lesson[] PythonProfessionalLessons =
    [
        new("python-project-foundations", "Project studio", 13, "Start a production-shaped project", "A clean project boundary makes every later decision cheaper.", "Separate application code, tests, configuration, and delivery concerns from the first commit.", "Create a small learning-service API and evolve it throughout the track. Keep source in a package, tests outside it, configuration in the environment, and dependencies declared in project metadata. A professional project is reproducible before it is clever.", "learning_service/\n  src/learning_service/\n  tests/\n  pyproject.toml", new(ExerciseKind.MultipleChoice, "Choose the boundary", "Which concern should not be hard-coded into application source?", ["Choose one answer"], null, "config", [new("config", "Deployment-specific configuration and secrets"), new("domain", "A domain rule expressed in code"), new("test", "A test case that documents behavior")], "Environment-specific values belong outside the source tree.", ["Separates configuration"]), "python-environments-packaging", PythonDocs),
        new("python-environments-packaging", "Project studio", 14, "Use environments and packages responsibly", "Reproducible dependencies are a delivery requirement.", "A virtual environment isolates a project’s installed packages from other projects and the system interpreter.", "Pin or constrain direct dependencies according to your team’s policy, review upgrades, and use a lock file when your toolchain supports one. Keep the supported Python range explicit in `pyproject.toml`; test it in CI. Do not install application dependencies globally.", "[project]\nname = \"learning-service\"\nrequires-python = \">=3.14\"\ndependencies = [\"fastapi\", \"uvicorn\"]", new(ExerciseKind.MultipleChoice, "Choose the safe setup", "Why create a virtual environment for a project?", ["Choose one answer"], null, "isolate", [new("isolate", "It isolates that project’s installed dependencies"), new("speed", "It makes Python syntax execute faster"), new("secret", "It encrypts environment variables")], "Think about dependency isolation, not security or performance.", ["Uses isolated dependencies"]), "python-control-flow-collections", PythonDocs),
        new("python-control-flow-collections", "Core Python", 15, "Control flow and collections", "Choose the collection that states the operation you need.", "Lists preserve order, dictionaries map keys to values, sets model uniqueness, and tuples model fixed positional values.", "Use `for` to iterate, `enumerate` when an index is truly meaningful, and comprehensions when they make a transformation clearer—not denser. Avoid modifying a collection while iterating over it. Prefer a direct loop when a comprehension gains multiple conditions or side effects.", "active_names = [user.name for user in users if user.active]\nby_id = {user.id: user for user in users}", new(ExerciseKind.MultipleChoice, "Pick the collection", "Which type best represents unique permission names?", ["Choose one answer"], null, "set", [new("set", "A set"), new("list", "A list because it always prevents duplicates"), new("tuple", "A tuple because it is mutable")], "Uniqueness is the key requirement here.", ["Selects a collection by semantics"]), "python-modules-imports", PythonDocs),
        new("python-modules-imports", "Core Python", 16, "Modules, imports, and package boundaries", "Imports form an architectural dependency graph.", "A module is a namespace; a package groups related modules into a distributable unit.", "Keep imports explicit and acyclic. Put stable domain concepts near the center of the dependency graph; adapters such as HTTP, database, and framework code should depend inward, not the reverse. Avoid executable work at import time because imports also run in tests and tooling.", "# application/services/enroll.py\nfrom application.domain.lesson import Lesson\n\ndef enroll(lesson: Lesson) -> None:\n    ...", new(ExerciseKind.MultipleChoice, "Protect the graph", "What is the best reason to avoid side effects at import time?", ["Choose one answer"], null, "predictable", [new("predictable", "Imports remain predictable for tests, tools, and callers"), new("faster", "It makes every import asynchronous"), new("private", "It hides modules from other packages")], "Importing should primarily define names, not start application work.", ["Designs predictable imports"]), "python-objects-protocols", PythonDocs),
        new("python-objects-protocols", "Core Python", 17, "Objects, protocols, and composition", "Model behavior through small interfaces and composition.", "Protocols describe the operations a collaborator must support without forcing inheritance.", "Use classes where state and behavior belong together, dataclasses for simple value objects, and `Protocol` for structural contracts at seams. Prefer composition over inheritance: inject a clock, repository, or sender rather than deriving from a deep base class.", "from typing import Protocol\n\nclass LessonRepository(Protocol):\n    def get(self, lesson_id: str) -> Lesson | None: ...", new(ExerciseKind.MultipleChoice, "Choose the seam", "What does a Protocol help you express?", ["Choose one answer"], null, "behavior", [new("behavior", "The behavior a collaborator must provide"), new("database", "A database schema migration"), new("runtime", "A mandatory runtime inheritance tree")], "Protocols support structural, behavior-oriented boundaries.", ["Uses composition seams"]), "python-errors-resources", PythonDocs),
        new("python-errors-resources", "Core Python", 18, "Exceptions and resource safety", "Handle errors where you can add context or recover.", "`with` guarantees cleanup for context-managed resources, even when an exception is raised.", "Catch specific exceptions at boundaries. Preserve the original exception as the cause when translating it. Use `finally` or a context manager for cleanup; do not catch `Exception` merely to log and continue. For an API, map known domain failures to intentional client responses and let unexpected failures reach centralized handling.", "try:\n    with open(path, encoding=\"utf-8\") as file:\n        return file.read()\nexcept OSError as error:\n    raise ConfigurationError(path) from error", new(ExerciseKind.MultipleChoice, "Keep the cause", "What does `raise NewError(...) from error` preserve?", ["Choose one answer"], null, "chain", [new("chain", "The causal exception chain for debugging"), new("retry", "An automatic network retry"), new("type", "Runtime type enforcement")], "The original cause remains visible in the traceback.", ["Preserves failure context"]), "python-testing-pytest", PytestDocs),
        new("python-testing-pytest", "Quality engineering", 19, "Test with pytest and a deliberate pyramid", "Tests should make change safer and feedback faster.", "Unit tests protect local rules; integration tests prove behavior at real boundaries; a few end-to-end tests protect the critical journey.", "Name tests after behavior, arrange only the required state, and assert the observable result. Use fixtures for explicit setup, factories for readable domain data, and fakes at your own ports. Mock third-party boundaries sparingly; tests coupled to call order make refactoring expensive.", "def test_enroll_rejects_an_archived_lesson() -> None:\n    result = enroll(archived_lesson)\n    assert result.is_error", new(ExerciseKind.MultipleChoice, "Choose the assertion", "What should an HTTP integration test primarily assert?", ["Choose one answer"], null, "contract", [new("contract", "The observable status and response contract"), new("private", "The internal helper call order"), new("time", "An exact timestamp in every response")], "Test what an API client can rely on.", ["Tests observable contracts"]), "python-http-clients", PytestDocs),
        new("python-http-clients", "Web foundations", 20, "Call HTTP services resiliently", "Every network call needs a bounded failure policy.", "Timeouts, retries, idempotency, and error classification are part of a client contract.", "Set connect and read timeouts deliberately. Retry only transient failures and only when the operation is safe or protected by an idempotency key. Bound retry attempts with backoff and jitter; report dependency failures with enough context to diagnose them without leaking sensitive data.", "async with httpx.AsyncClient(timeout=5.0) as client:\n    response = await client.get(url)\n    response.raise_for_status()", new(ExerciseKind.MultipleChoice, "Retry safely", "When is an automatic retry most defensible?", ["Choose one answer"], null, "idempotent", [new("idempotent", "A transient failure on an idempotent request with a bounded policy"), new("invalid", "A validation error from the caller"), new("payment", "A payment POST without idempotency protection")], "Retries can duplicate effects when operations are not idempotent.", ["Designs bounded retries"]), "python-api-contracts", FastApiDocs),
        new("python-api-contracts", "API delivery", 21, "Design API contracts before handlers", "A stable contract lets clients and teams evolve independently.", "A resource shape, status code, error format, pagination contract, and idempotency policy are all API design.", "Write examples for success and failure before implementation. Validate at the boundary, use consistent error envelopes, return `201 Created` with a location or representation when creating a resource, and define cursor semantics before large collections need them. Version only when you cannot evolve compatibly.", "POST /v1/enrollments\nIdempotency-Key: 7fd...\n\n201 Created\nLocation: /v1/enrollments/42", new(ExerciseKind.MultipleChoice, "Choose compatibility", "What is the least disruptive way to evolve a response?", ["Choose one answer"], null, "additive", [new("additive", "Add an optional field with documented semantics"), new("rename", "Rename a required field without a migration"), new("status", "Change successful requests from 200 to 500")], "Additive changes preserve existing clients more often.", ["Designs compatible contracts"]), "python-fastapi-architecture", FastApiDocs),
        new("python-fastapi-architecture", "API delivery", 22, "Structure a FastAPI application", "Framework code should compose the application; it should not become the application.", "FastAPI dependency injection is useful at the delivery boundary, while services and domain rules remain ordinary Python.", "Group routers by capability, keep Pydantic request and response models at the API edge, and inject repositories or services through explicit providers. Use lifespan handling for shared clients and connections. Generate OpenAPI from a truthful contract; do not expose internal implementation shapes by accident.", "router = APIRouter(prefix=\"/lessons\")\n\n@router.get(\"/{lesson_id}\", response_model=LessonResponse)\ndef get_lesson(lesson_id: str, service: LessonServiceDep) -> LessonResponse:\n    return service.get(lesson_id)", new(ExerciseKind.MultipleChoice, "Place the rule", "Where should a business rule about enrollment eligibility live?", ["Choose one answer"], null, "service", [new("service", "In a domain or application service, independent of the route"), new("router", "Only in an HTTP router"), new("schema", "Only in the OpenAPI document")], "The rule should remain usable outside HTTP delivery.", ["Separates delivery from business rules"]), "python-async-correctness", FastApiDocs),
        new("python-async-correctness", "API delivery", 23, "Async without accidental blocking", "Async improves waiting efficiency only when the whole call path cooperates.", "An `async def` endpoint should await non-blocking I/O; CPU-bound or blocking work needs a different execution strategy.", "Use async-compatible libraries for network and database I/O. Do not call blocking file, database, or CPU-heavy operations directly in the event loop. Bound concurrent fan-out, propagate cancellation, and measure queueing and latency before adding concurrency.", "async def lesson(lesson_id: str, client: httpx.AsyncClient) -> Lesson:\n    response = await client.get(f\"/lessons/{lesson_id}\")\n    return Lesson.model_validate(response.json())", new(ExerciseKind.MultipleChoice, "Protect the event loop", "What should happen to CPU-bound report generation?", ["Choose one answer"], null, "worker", [new("worker", "Run it in a worker process or purpose-built compute system"), new("await", "Add `await` to make CPU work non-blocking"), new("route", "Keep it in the request path with no timeout")], "Awaiting does not make CPU work asynchronous.", ["Avoids event-loop blocking"]), "python-database-sqlalchemy", DjangoDocs),
        new("python-database-sqlalchemy", "Data and state", 24, "Persist state with transactions", "The database is a concurrent, durable collaborator.", "A transaction defines the all-or-nothing unit of a business operation.", "Use a mature data-access approach consistently—Django ORM for Django, or SQLAlchemy with an explicit unit-of-work/repository boundary where appropriate. Parameterize queries, select only necessary columns, design indexes from measured access patterns, and keep transaction scope short. Treat migrations as reviewed release artifacts.", "with session.begin():\n    enrollment = Enrollment.create(user_id=user_id, lesson_id=lesson_id)\n    outbox.add(EnrollmentCreated(enrollment.id))", new(ExerciseKind.MultipleChoice, "Protect atomicity", "What belongs in the same transaction as recording an enrollment?", ["Choose one answer"], null, "outbox", [new("outbox", "An outbox event that must not be lost relative to the enrollment"), new("email", "A slow remote email call"), new("cache", "An unrelated cache warm-up")], "The outbox pattern links durable state and durable intent.", ["Defines transactional boundaries"]), "python-auth-security", DjangoDocs),
        new("python-auth-security", "Data and state", 25, "Authenticate, authorize, and defend boundaries", "Authentication identifies; authorization decides.", "Input validation, least privilege, safe session/token handling, and secure defaults are product requirements.", "Use a well-reviewed identity provider rather than inventing password storage. Authorize every protected action against the current principal and resource. Keep secrets in the environment or a managed secret store, use parameterized queries, set secure cookie and CORS policies deliberately, and make abuse controls part of endpoint design.", "def can_edit_lesson(actor: User, lesson: Lesson) -> bool:\n    return actor.organization_id == lesson.organization_id and actor.has_role(\"editor\")", new(ExerciseKind.MultipleChoice, "Authorize the action", "What must an API check before updating a lesson?", ["Choose one answer"], null, "resource", [new("resource", "The caller’s permission for that specific resource and action"), new("ui", "Whether the UI hid the edit button"), new("token", "Only whether a token exists")], "A valid identity alone does not grant every action.", ["Separates authn and authz"]), "python-flask-production", FlaskDocs),
        new("python-flask-production", "Framework practice", 26, "Build Flask with explicit composition", "Flask stays maintainable when the application owns its wiring.", "Application factories, blueprints, and extension initialization make Flask configuration testable.", "Create the app from configuration, register blueprints and error handlers in one composition root, and initialize extensions with `init_app`. Keep request handlers thin. Use a production WSGI server and set proxy, session, and configuration behavior intentionally; the built-in development server is not the production deployment model.", "def create_app(config: Config) -> Flask:\n    app = Flask(__name__)\n    app.config.from_mapping(config.as_dict())\n    db.init_app(app)\n    app.register_blueprint(lessons_bp)\n    return app", new(ExerciseKind.MultipleChoice, "Choose the composition root", "Where should Flask extensions be connected to a specific app?", ["Choose one answer"], null, "init", [new("init", "During application creation with explicit configuration"), new("import", "As irreversible side effects during every import"), new("view", "Inside each individual view function")], "Application creation makes wiring visible and testable.", ["Composes a Flask application"]), "python-django-production", DjangoDocs),
        new("python-django-production", "Framework practice", 27, "Ship Django safely", "Django conventions accelerate teams when they remain visible and reviewed.", "Django provides robust primitives, but settings, migrations, permissions, and queries still require engineering judgment.", "Use settings modules or environment-driven configuration, run migration checks in delivery pipelines, protect admin access, and write ORM queries with query counts and indexes in mind. Use `transaction.atomic()` around a cohesive operation and defer external side effects until the transaction is committed.", "with transaction.atomic():\n    enrollment = Enrollment.objects.create(user=user, lesson=lesson)\n    transaction.on_commit(lambda: publish_enrolled(enrollment.pk))", new(ExerciseKind.MultipleChoice, "Time the side effect", "When should a message about a database change be published?", ["Choose one answer"], null, "commit", [new("commit", "After the database transaction successfully commits"), new("before", "Before attempting the database write"), new("template", "Only when an HTML template renders")], "Publishing before commit can advertise state that never persisted.", ["Coordinates transaction side effects"]), "python-background-work", DjangoDocs),
        new("python-background-work", "Production systems", 28, "Design durable background work", "A queue moves work; it does not remove failure modes.", "Idempotency, retries, visibility, and ownership make asynchronous work reliable.", "Use background jobs for durable, slow, or retryable work. Give each job a stable idempotency key, make handlers safe to retry, configure bounded retries and dead-letter handling, and measure age, failures, and throughput. Use an outbox or equivalent when an event must correspond to committed state.", "def send_completion_email(enrollment_id: str) -> None:\n    if delivery_log.exists(enrollment_id):\n        return\n    # send, then record delivery atomically where possible", new(ExerciseKind.MultipleChoice, "Make retries safe", "What makes a job safe to retry?", ["Choose one answer"], null, "idempotent", [new("idempotent", "Repeated processing does not create an unintended extra effect"), new("fast", "It completes in under one second"), new("async", "It is declared with `async def`")], "Retries are normal in distributed systems; effects must tolerate them.", ["Designs idempotent jobs"]), "python-performance-caching", PythonDocs),
        new("python-performance-caching", "Production systems", 29, "Measure performance and cache deliberately", "A faster-looking system can be less correct.", "Profiling and production telemetry identify the constraint; caching adds invalidation and consistency obligations.", "Start with a user-visible objective such as p95 latency or throughput. Measure application time, database queries, dependency time, and saturation. Fix clear waste first; cache only a stable, read-heavy result with an explicit key, TTL, invalidation story, failure behavior, and observability.", "cache_key = f\"lesson:{lesson_id}:v{lesson.version}\"\nvalue = await cache.get(cache_key)\nif value is None:\n    value = await repository.get(lesson_id)\n    await cache.set(cache_key, value, ttl=300)", new(ExerciseKind.MultipleChoice, "Choose the first move", "What should happen before adding a cache for a slow endpoint?", ["Choose one answer"], null, "measure", [new("measure", "Measure where time is spent and define the desired outcome"), new("global", "Cache every response globally"), new("ttl", "Pick a random TTL")], "A cache is a tradeoff, not a diagnosis.", ["Uses evidence for performance work"]), "python-delivery-containers", FastApiDocs),
        new("python-delivery-containers", "Production systems", 30, "Deliver a Python service", "A deployable service has explicit runtime behavior.", "Build once, configure at runtime, expose health signals, and run a supported server process.", "Use a small, reproducible image or platform build, run as a non-root user where possible, declare the Python and dependency versions, and pass configuration through the environment. Distinguish liveness from readiness, run database migrations with an intentional release process, and ensure shutdown gives in-flight work a bounded chance to finish.", "CMD [\"uvicorn\", \"learning_service.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8080\"]", new(ExerciseKind.MultipleChoice, "Choose the release step", "What should a readiness check answer?", ["Choose one answer"], null, "ready", [new("ready", "Whether this instance can safely receive traffic now"), new("syntax", "Whether Python source parses"), new("future", "Whether every future dependency call will succeed")], "Readiness is about receiving work safely at this moment.", ["Defines operational health"]), "python-reliability-design", FastApiDocs),
        new("python-reliability-design", "Production systems", 31, "Operate with reliability objectives", "Reliability becomes actionable when it is tied to user experience.", "SLIs measure a service quality signal; SLOs set the target; an error budget makes tradeoffs visible.", "Define a small set of user-centered SLIs: successful request rate, latency, freshness, or job completion delay. Instrument structured logs, metrics, and traces with correlation identifiers. Alert on sustained budget burn and route ownership clearly. Test recovery paths such as dependency failure, overload, and rollback.", "SLI: 99.9% of lesson reads succeed\nSLO: 99.9% over 30 days\nAlert: burn rate threatens the monthly error budget", new(ExerciseKind.MultipleChoice, "Choose the alert", "Which alert is most likely to be actionable?", ["Choose one answer"], null, "burn", [new("burn", "Sustained error-budget burn for a user-facing SLO"), new("debug", "Every debug log message"), new("cpu", "Any brief CPU increase with no user impact")], "Actionable alerts connect a symptom, impact, and owner.", ["Uses SLO-driven operations"]), "python-system-design", PythonDocs),
        new("python-system-design", "Staff practice", 32, "Design systems through constraints", "Architecture is a sequence of tested hypotheses, not a diagram.", "Staff engineers turn product goals, load, data, failure modes, and team ownership into an operable design.", "For the capstone, design a multi-tenant learning platform: state assumptions, define boundaries and contracts, select storage and asynchronous workflows, identify consistency requirements, model failure and recovery, estimate capacity, define SLOs, and write an ADR with a reversible rollout. Review it with the teams who must build and operate it.", "Context: 10M learners, global reads, regional writes\nDecision: modular monolith + read cache + durable job queue\nRevisit: when team ownership or write contention changes", new(ExerciseKind.MultipleChoice, "Frame the design", "What is the strongest first artifact for a staff-level design?", ["Choose one answer"], null, "constraints", [new("constraints", "Explicit goals, constraints, risks, and measurable success criteria"), new("diagram", "A detailed diagram with no stated problem"), new("micro", "A decision to use microservices by default")], "A diagram becomes useful only when it answers real constraints.", ["Frames architecture with evidence"]), "python-staff-architecture", PythonDocs)
    ];
    public static readonly Lesson[] PythonAllLessons = PythonLessons.Concat(PythonProfessionalLessons).ToArray();
    public static readonly Dictionary<string, Lesson> BySlug = Lessons.Concat(PythonAllLessons).ToDictionary(lesson => lesson.Slug, StringComparer.Ordinal);
    public static readonly Course Course = BuildCourse("csharp-dotnet", "C# / .NET: zero to staff", "csharp", "C# 14", ".NET 10", "2026-08-12", Lessons);
    public static readonly Course PythonCourse = BuildCourse("python-web", "Python Web: zero to staff", "python", "Python 3.14", "FastAPI · Flask · Django", "2026-08-13", PythonAllLessons);
    public static readonly IReadOnlyDictionary<string, Course> Courses = new Dictionary<string, Course>(StringComparer.Ordinal)
    {
        [Course.Id] = Course,
        [PythonCourse.Id] = PythonCourse
    };
    public static readonly IReadOnlyList<CourseCatalogItem> Catalog =
    [
        new(Course.Id, Course.Title, Course.LanguageId, Course.LanguageVersion, Course.FrameworkVersion, true),
        new(PythonCourse.Id, PythonCourse.Title, PythonCourse.LanguageId, PythonCourse.LanguageVersion, PythonCourse.FrameworkVersion, true)
    ];

    private static Course BuildCourse(string id, string title, string languageId, string languageVersion, string frameworkVersion, string reviewed, Lesson[] lessons) => new(id, title, languageId, languageVersion, frameworkVersion, reviewed,
        lessons.GroupBy(lesson => lesson.Module).OrderBy(group => group.Min(lesson => lesson.Order)).Select(group => new Module(group.Key.ToLowerInvariant().Replace(' ', '-'), group.Key, group.Key.Contains("foundations", StringComparison.OrdinalIgnoreCase) ? "Beginner" : group.Key.Contains("staff", StringComparison.OrdinalIgnoreCase) ? "Staff" : "Professional", group.OrderBy(lesson => lesson.Order).Select(l => new LessonSummary(l.Slug, l.Title, l.Order)).ToArray())).ToArray());
}
