static partial class Curriculum
{
    public static Lesson[] BuildReactLiteCourseLessons() => NormalizeLessons(
    [
        new(
            "react-lite-vite-bootstrap",
            "Project setup",
            1,
            "Bootstrap a modern React application",
            "A toolchain is the set of development tools used to create, check, run, and build an application. Start with a small toolchain where each piece has one clear responsibility.",
            "React is a UI (user-interface) library: reusable code for describing interactive screens. TypeScript is JavaScript plus optional type syntax checked during development; those type annotations are removed before browsers run the resulting JavaScript. Vite is a build tool that provides a local development server and creates production-ready browser files. npm is the package manager used here: a package is reusable code published for installation, and a dependency is a package this project relies on.",
            "To scaffold means to generate the starter files/configuration for a project. npm create vite scaffolds the project; npm install downloads dependencies listed in package.json, the project's package metadata/configuration file; npm run dev runs the named dev script. The react-ts template is Vite's React + TypeScript starter. Source code lives under src, public holds files copied as-is, index.html is the browser's initial HTML document, and main.tsx is the TypeScript/JSX entry file that starts React. A production build creates optimized browser assets (deployable HTML, JavaScript, CSS, and related files).",
            "npm create vite@latest admin-dashboard -- --template react-ts\ncd admin-dashboard\nnpm install\nnpm run dev",
            ReactChoice(
                "Understand TypeScript's role",
                "What does TypeScript add before the browser runs the application?",
                "checks",
                [new("checks", "Compile-time type checks plus stronger editor and refactoring support"), new("runtime", "A new browser runtime that replaces JavaScript"), new("database", "Automatic database validation")],
                "TypeScript helps catch mismatched values while developing; the browser ultimately runs JavaScript.",
                "Explains why TypeScript is useful"),
            null,
            ViteReactDocs),
        new(
            "react-lite-router-tailwind",
            "Project setup",
            2,
            "Install React Router and Tailwind CSS",
            "Routing gives application screens stable URLs; styling controls how those screens are presented.",
            "React Router maps URLs to page components and can associate data work with those routes. Tailwind CSS provides utility classes for normal CSS properties such as spacing, layout, typography, states, and responsive breakpoints.",
            "Install react-router plus tailwindcss and @tailwindcss/vite. Configure the Tailwind Vite plugin and import Tailwind from the main stylesheet. Keep router setup near application startup and styling setup near the build/style entry points.",
            "npm i react-router\nnpm i tailwindcss @tailwindcss/vite",
            ReactChoice(
                "Name the responsibilities",
                "Which tool decides what page a URL displays?",
                "router",
                [new("router", "React Router"), new("tailwind", "Tailwind CSS"), new("vite", "Vite alone")],
                "React Router owns application routing.",
                "Adds the shared routing and styling stack"),
            null,
            ReactRouterDocs),
        new(
            "react-lite-devtools-project-files",
            "Project setup",
            3,
            "Use browser DevTools and read the project",
            "Knowing where to look when something breaks is a core web-development skill.",
            "Browser DevTools exposes the Elements, Console, Network, Sources, and Storage views; Vite reports module/build errors in the terminal and browser.",
            "Use Console for JavaScript errors, Network for requests, Elements for rendered HTML/CSS, and Application/Storage when checking browser persistence. Read errors from the top-most useful message instead of guessing.",
            "Console -> runtime error\nNetwork -> request/response\nElements -> HTML and CSS",
            ReactChoice(
                "Debug a failed request",
                "Which DevTools panel should you inspect first when an API call returns 500?",
                "network",
                [new("network", "Network"), new("elements", "Elements only"), new("fonts", "Fonts")],
                "The Network panel shows request and response details.",
                "Uses browser debugging tools"),
            null,
            ViteReactDocs),
        new(
            "react-lite-folder-structure",
            "Project setup",
            4,
            "Start with a folder structure that can grow",
            "A first project should be understandable without copying a huge enterprise architecture.",
            "Use routes/pages for screens, components for reusable UI, layouts for shared page chrome, services for the API wrapper, and types for shared data shapes.",
            "A practical small-application structure is src/app for startup/configuration, src/pages for route screens, src/components for reusable UI, src/layouts for shared page chrome, src/services for external data access, src/types for shared data shapes, and src/styles for global styling. Split further only when a real ownership boundary appears.",
            "src/\n  app/\n  pages/\n  components/\n  layouts/\n  services/\n  types/\n  styles/",
            ReactChoice(
                "Place the API wrapper",
                "Which folder should own the dummy users API wrapper?",
                "services",
                [new("services", "services"), new("styles", "styles"), new("public", "public")],
                "External-data boundaries belong in services.",
                "Uses a simple scalable project structure"),
            null,
            ReactDocs),

        new(
            "react-lite-jsx-rendering",
            "React foundations",
            5,
            "Understand JSX and rendering",
            "JSX is syntax for describing UI from JavaScript values.",
            "A React component returns elements. Curly braces insert JavaScript expressions into JSX, and React renders the resulting tree.",
            "JSX looks like HTML but follows JavaScript rules. Use className instead of class, close tags, and return one enclosing tree. Keep rendering free of irreversible side effects.",
            "function Welcome() { return <h1 className='text-2xl'>Admin dashboard</h1> }",
            ReactCode(
                "Render a dashboard heading",
                "Export DashboardHeading. Give it a title string prop and render that title in an h1.",
                "type Props = { title: string };\n\nexport function DashboardHeading({ title }: Props) {\n  return null;\n}",
                "Return an h1 and place title inside curly braces.",
                "Exports DashboardHeading",
                "Renders the title prop"),
            null,
            ReactDocs),
        new(
            "react-lite-components-props",
            "React foundations",
            6,
            "Break a page into components and props",
            "Components are reusable UI functions; props are their inputs.",
            "A useful component has a focused job and a clear typed prop contract.",
            "Start by extracting repeated or meaningful UI: PageHeader, StatCard, UserTable, StatusBadge, and FormField. Do not split every div into a separate component.",
            "function StatCard({ label, value }: { label: string; value: number }) { return <section><span>{label}</span><strong>{value}</strong></section> }",
            ReactCode(
                "Build a stat card",
                "Export StatCard with label:string and value:number props. Render both values.",
                "type Props = { label: string; value: number };\n\nexport function StatCard({ label, value }: Props) {\n  return null;\n}",
                "A simple section containing label and value is enough.",
                "Defines typed component props",
                "Renders both values"),
            null,
            ReactDocs),
        new(
            "react-lite-events",
            "React foundations",
            7,
            "Respond to user events",
            "Event handlers connect user actions to application behavior.",
            "Pass a function to onClick, onChange, and onSubmit rather than calling the function while rendering.",
            "Name handlers after user intent such as handleAddUser or handleSearchChange. Events are the right place for work caused by a user action.",
            "<button onClick={handleAddUser}>Add user</button>",
            ReactChoice(
                "Wire a click",
                "Which expression passes a click handler without calling it during render?",
                "handler",
                [new("handler", "onClick={handleSave}"), new("call", "onClick={handleSave()}"), new("string", "onClick='handleSave'")],
                "Pass the function itself.",
                "Handles user events correctly"),
            null,
            ReactDocs),
        new(
            "react-lite-state",
            "React foundations",
            8,
            "Store interactive state with useState",
            "State represents information that changes and should cause the UI to render again.",
            "useState returns the current render's value and a setter that schedules another render.",
            "Use local state for UI concerns such as search text, whether a form is open, and an editable draft. Do not mutate state objects or arrays directly.",
            "const [query, setQuery] = useState('')",
            ReactCode(
                "Build a search box",
                "Export UserSearch using useState(''). Render an input whose value is query and whose onChange updates query.",
                "import { useState } from 'react';\n\nexport function UserSearch() {\n  return null;\n}",
                "Create query state, then connect value and onChange.",
                "Uses useState",
                "Creates a controlled input"),
            null,
            ReactHooksDocs),
        new(
            "react-lite-conditionals-derived-data",
            "React foundations",
            9,
            "Render conditions and derive values",
            "Not every value needs its own state variable.",
            "Use normal JavaScript expressions to derive counts, labels, and filtered arrays from existing props/state.",
            "If activeUsers can be calculated from users, calculate it instead of storing another synchronized state variable. Use && or a ternary for conditional UI.",
            "const activeCount = users.filter(user => user.status === 'active').length",
            ReactChoice(
                "Choose derived data",
                "Should activeCount normally be a second useState value when it can be calculated from users?",
                "no",
                [new("no", "No, derive it from users"), new("yes", "Yes, always duplicate it"), new("ref", "Store it only in a ref")],
                "Derived values usually do not need separate state.",
                "Avoids duplicated state"),
            null,
            ReactHooksDocs),
        new(
            "react-lite-lists-keys",
            "React foundations",
            10,
            "Render lists with stable keys",
            "Dashboards render tables, menus, cards, and select options from arrays constantly.",
            "map turns data into elements; key gives each sibling stable identity between renders.",
            "Use a real record ID as the key. This matters when rows are edited, removed, or reordered.",
            "{users.map(user => <UserRow key={user.id} user={user} />)}",
            ReactChoice(
                "Choose a row key",
                "What is the best key for user rows that can be deleted or reordered?",
                "id",
                [new("id", "user.id"), new("index", "array index"), new("random", "Math.random()")],
                "Stable business identity is best.",
                "Renders changing lists safely"),
            null,
            ReactDocs),
        new(
            "react-lite-forms",
            "React foundations",
            11,
            "Build forms with controlled fields",
            "Admin applications spend a lot of time collecting and validating structured input.",
            "Controlled inputs keep a field's visible value in React state; form onSubmit represents the save action.",
            "Use labels, suitable input types, required attributes, and a submit button. Prevent the browser's default navigation when handling the form locally. Start with required fields and a few readable validation rules; add complexity only when the requirements justify it.",
            "<form onSubmit={handleSubmit}><label>Email <input type='email' value={email} onChange={...} /></label></form>",
            ReactCode(
                "Build a user form",
                "Export UserForm with name and email state. Render labeled controlled inputs and a submit button.",
                "import { useState } from 'react';\n\nexport function UserForm() {\n  return null;\n}",
                "For a small form, one state value per field keeps the data flow easy to follow.",
                "Uses controlled name and email inputs",
                "Provides a submit control"),
            null,
            ReactHooksDocs),
        new(
            "react-lite-effects",
            "React foundations",
            12,
            "Know when useEffect is appropriate",
            "Effects synchronize React with something outside the render calculation.",
            "useEffect runs after React commits and can clean up subscriptions, timers, browser APIs, or manually managed async synchronization.",
            "Do not use an Effect merely to calculate filteredUsers or activeCount; derive those values during render. Prefer route loaders for data required by a routed page. Use Effects when React must synchronize with something outside its render calculation, such as document APIs, timers, or subscriptions.",
            "useEffect(() => { document.title = title }, [title])",
            ReactChoice(
                "Choose an Effect",
                "Which task is a reasonable useEffect example?",
                "external",
                [new("external", "Synchronize document.title"), new("derived", "Calculate users.length"), new("jsx", "Choose whether to render a button")],
                "Effects synchronize external systems.",
                "Understands the basic Effect boundary"),
            null,
            ReactHooksDocs),

        new(
            "react-lite-router-pages",
            "Dashboard building",
            13,
            "Create pages with React Router",
            "A dashboard becomes easier to reason about when URLs map to page components.",
            "createBrowserRouter describes routes and RouterProvider activates the router.",
            "Create /, /users, and /users/:userId routes. Keep page components focused on assembling the data and UI needed for one screen.",
            "const router = createBrowserRouter([{ path: '/', Component: DashboardPage }, { path: '/users', Component: UsersPage }])",
            ReactCode(
                "Create dashboard routes",
                "Export router from createBrowserRouter with / and /users routes.",
                "import { createBrowserRouter } from 'react-router';\n\nfunction DashboardPage() { return <h1>Dashboard</h1>; }\nfunction UsersPage() { return <h1>Users</h1>; }\n\nexport const router = null;",
                "Pass an array of route objects to createBrowserRouter.",
                "Creates / and /users routes",
                "Exports the router"),
            null,
            ReactRouterDocs),
        new(
            "react-lite-layout-nav",
            "Dashboard building",
            14,
            "Build the dashboard shell",
            "Shared navigation and page chrome should live in one layout instead of being copied into every page.",
            "A parent route can render Sidebar, Header, and Outlet; Link or NavLink performs client-side navigation.",
            "Build a responsive shell with a sidebar on wider screens, top navigation, and a main content region. Keep the layout visual; page-specific data belongs in pages/components.",
            "<div className='grid min-h-screen md:grid-cols-[16rem_1fr]'><Sidebar /><main><Outlet /></main></div>",
            ReactCode(
                "Create an app layout",
                "Export AppLayout that renders a nav with Links to / and /users and an Outlet inside main.",
                "import { Link, Outlet } from 'react-router';\n\nexport function AppLayout() {\n  return null;\n}",
                "Render Link components in nav and Outlet in main.",
                "Provides navigation links",
                "Renders Outlet"),
            null,
            ReactRouterDocs),
        new(
            "react-lite-tailwind-dashboard",
            "Dashboard building",
            15,
            "Style a dashboard with Tailwind",
            "Utility classes let you move quickly while still applying normal CSS layout principles.",
            "Compose spacing, sizing, typography, borders, responsive breakpoints, flex/grid, hover, focus, and color utilities directly in JSX.",
            "Aim for visual hierarchy rather than decoration: consistent spacing, readable text, obvious actions, useful empty states, and responsive layouts. Extract repeated class combinations when they represent a real reusable UI pattern.",
            "<section className='grid gap-4 sm:grid-cols-2 xl:grid-cols-4'>...</section>",
            ReactChoice(
                "Create responsive cards",
                "Which Tailwind pattern changes the number of columns at larger breakpoints?",
                "responsive",
                [new("responsive", "grid sm:grid-cols-2 xl:grid-cols-4"), new("fixed", "text-sm only"), new("hidden", "hidden only")],
                "Breakpoint-prefixed utilities make responsive changes.",
                "Uses responsive Tailwind layout"),
            null,
            TailwindDocs),
        new(
            "react-lite-stat-cards",
            "Dashboard building",
            16,
            "Build reusable dashboard summary cards",
            "A dashboard often starts by summarizing important values before showing detailed data.",
            "Reusable presentational components receive values as props and stay independent from where the data came from.",
            "Build stat cards for total users, active users, disabled users, and administrators. The page calculates those numbers and passes them to StatCard.",
            "<StatCard label='Active users' value={activeCount} />",
            ReactChoice(
                "Keep a presentational component simple",
                "What should StatCard normally receive?",
                "props",
                [new("props", "A label/value through props"), new("database", "A direct database connection"), new("router", "The entire router instance")],
                "Presentational components work well with focused props.",
                "Composes dashboard summaries"),
            null,
            ReactDocs),
        new(
            "react-lite-table-filter-sort",
            "Dashboard building",
            17,
            "Build a searchable sortable data table",
            "Tables are a core admin-dashboard interaction.",
            "Search, filter, and sort should be derived from the original user array and current UI controls.",
            "Create a query field, status filter, and sort selection. Chain filter and a copied sort operation before mapping rows. Show a useful empty state when there are no matches.",
            "const visibleUsers = users.filter(...).toSorted((a, b) => a.name.localeCompare(b.name))",
            ReactCode(
                "Filter users",
                "Export filterUsers(users, query). Return users whose name or email includes query case-insensitively.",
                "type User = { id: string; name: string; email: string };\n\nexport function filterUsers(users: User[], query: string): User[] {\n  return [];\n}",
                "Lowercase query, name, and email and use filter.",
                "Filters by name",
                "Filters by email"),
            null,
            TypeScriptDocs),
        new(
            "react-lite-dummy-api-read",
            "Dashboard building",
            18,
            "Build a dummy API wrapper for reads",
            "Components should consume an API-shaped boundary even before a real backend exists.",
            "An async service wrapper lets the dashboard practice realistic loading and data ownership without requiring a server.",
            "Create usersApi.list and usersApi.get. They should return Promises, simulate a short delay, and return copied data rather than exposing the module's mutable array. Because components depend on the wrapper instead of its storage mechanism, the implementation can be replaced with fetch without rewriting the UI.",
            "export const usersApi = { async list(): Promise<User[]> { await delay(150); return users.map(user => ({ ...user })) } }",
            ReactCode(
                "Create the read wrapper",
                "Define and export usersApi with async list(): Promise<User[]> that returns a copy of seedUsers.",
                "type User = { id: string; name: string; email: string };\nconst seedUsers: User[] = [{ id: '1', name: 'Ada', email: 'ada@example.test' }];\n\nexport const usersApi = {\n};",
                "Add an async list method and return a copied array.",
                "Defines async list",
                "Returns copied user data"),
            null,
            ReactRouterDocs),
        new(
            "react-lite-router-loader",
            "Dashboard building",
            19,
            "Load dashboard data through the router",
            "Route-owned page data can be loaded before the page renders.",
            "A React Router loader calls the service wrapper; useLoaderData reads the returned value inside the page.",
            "The /users loader calls usersApi.list, and the page consumes the returned array. This ties data loading to navigation and keeps the page component focused on rendering.",
            "export async function usersLoader() { return usersApi.list() }",
            ReactCode(
                "Create a users loader",
                "Export async usersLoader that returns usersApi.list().",
                "type User = { id: string; name: string };\ndeclare const usersApi: { list(): Promise<User[]> };\n\nexport async function usersLoader() {\n}",
                "Return the Promise from usersApi.list.",
                "Uses the API wrapper",
                "Returns loader data"),
            null,
            ReactRouterDocs),
        new(
            "react-lite-loading-errors-empty",
            "Dashboard building",
            20,
            "Design loading, error, and empty states",
            "A functional application explains what is happening when data is not in the happy path.",
            "Users need distinct feedback for waiting, failure, an empty collection, and a filtered collection with no matches.",
            "Use router pending/error facilities where they naturally fit and simple conditional rendering inside components. Never leave a blank screen when an operation takes time or fails.",
            "if (!users.length) return <EmptyState title='No users yet' />",
            ReactChoice(
                "Show an empty state",
                "What should a users page display when a successful request returns an empty array?",
                "empty",
                [new("empty", "A deliberate empty-state message/action"), new("error", "A server error"), new("blank", "Nothing at all")],
                "Empty is a valid result, not necessarily an error.",
                "Handles non-happy-path UI"),
            null,
            ReactRouterDocs),
        new(
            "react-lite-dummy-api-write",
            "Dashboard building",
            21,
            "Add create, update, and delete to the dummy API",
            "The wrapper can simulate the same CRUD calls the real API will eventually expose.",
            "Mutation methods accept typed inputs, update the module-owned collection, and return Promises.",
            "Implement create, update, and remove. Generate IDs in the dummy layer, not in the form component. Keep the service methods small and predictable so a real HTTP implementation can preserve the same component-facing contract.",
            "await usersApi.create({ name, email, role: 'user', status: 'active' })",
            ReactCode(
                "Create a dummy create method",
                "Add async create(input) that creates a User with an id, pushes it into users, and returns a copy.",
                "type User = { id: string; name: string; email: string };\ntype NewUser = Omit<User, 'id'>;\nconst users: User[] = [];\n\nexport const usersApi = {\n};",
                "Generate an id, create a User, add it to users, then return a copy.",
                "Defines async create",
                "Creates and stores a user"),
            null,
            ReactRouterDocs),
        new(
            "react-lite-router-action-crud",
            "Dashboard building",
            22,
            "Connect form writes through a route action",
            "A route action gives create/update/delete operations one clear mutation boundary.",
            "Form submits to an action; the action reads FormData and calls the dummy API wrapper.",
            "For create-user, read name and email from FormData, validate required values, call usersApi.create, and redirect or return a useful result. Keep mutation logic at the route/action boundary instead of embedding it in presentational components.",
            "export async function createUserAction({ request }: ActionFunctionArgs) { const data = await request.formData(); return usersApi.create(...) }",
            ReactCode(
                "Create a user action",
                "Export createUserAction({ request }) that reads name and email from request.formData() and calls usersApi.create({ name, email }).",
                "import type { ActionFunctionArgs } from 'react-router';\ntype NewUser = { name: string; email: string };\ndeclare const usersApi: { create(input: NewUser): Promise<unknown> };\n\nexport async function createUserAction({ request }: ActionFunctionArgs) {\n}",
                "Await request.formData, read name/email as strings, then call usersApi.create.",
                "Reads FormData",
                "Calls the dummy API create method"),
            null,
            ReactRouterDocs),
        new(
            "react-lite-edit-delete-ui",
            "Dashboard building",
            23,
            "Finish the CRUD experience",
            "A usable admin dashboard needs clear edit/delete flows rather than only a Create button.",
            "Edit screens reuse typed form concepts; destructive actions need explicit wording and confirmation.",
            "Build an edit page or dialog that loads one user, pre-populates fields, and calls update. Add a delete action with confirmation and return the user to the list. Prefer a clear confirmed mutation before adding speculative or optimistic UI behavior.",
            "<button type='button' onClick={() => confirm('Delete this user?') && onDelete(user.id)}>Delete</button>",
            ReactChoice(
                "Handle deletion",
                "What should a destructive Delete User action include?",
                "confirm",
                [new("confirm", "Clear destructive wording and confirmation"), new("hidden", "A hidden unlabeled icon only"), new("automatic", "Delete on row hover")],
                "Destructive actions should be deliberate.",
                "Completes understandable CRUD interactions"),
            null,
            ReactDocs),
        new(
            "react-lite-persistence",
            "Dashboard building",
            24,
            "Optionally persist the dummy API in localStorage",
            "Browser storage can make the fake backend feel persistent across refreshes while remaining clearly separate from a real server.",
            "localStorage stores strings per browser origin; serialize the dummy collection to JSON and parse it when the service initializes.",
            "Use localStorage only inside the dummy service, not scattered across components. That keeps the service replaceable when a real API arrives. Explain that localStorage is not shared, trusted, secure backend storage.",
            "localStorage.setItem('admin-users', JSON.stringify(users))",
            ReactChoice(
                "Choose the boundary",
                "Where should localStorage persistence live when it is only an implementation detail of the fake backend?",
                "service",
                [new("service", "Inside the dummy API/service layer"), new("every", "Inside every row component"), new("css", "Inside Tailwind config")],
                "Keep persistence behind the API-shaped wrapper.",
                "Keeps fake persistence replaceable"),
            null,
            ReactDocs),

        new(
            "react-lite-basic-testing",
            "Finishing the application",
            25,
            "Add a few high-value tests",
            "A small application benefits from a few tests that protect important behavior without duplicating implementation details.",
            "Vitest and Testing Library can verify user-visible component behavior and pure helpers.",
            "Test filterUsers, one reusable component, and one important form interaction. Query by role or label where possible so tests describe behavior a user can observe.",
            "expect(filterUsers(users, 'ada')).toHaveLength(1)",
            ReactCode(
                "Test a filter helper",
                "Write a Vitest test that calls filterUsers and expects one match for 'ada'.",
                "import { expect, it } from 'vitest';\n\ntype User = { id: string; name: string; email: string };\nfunction filterUsers(users: User[], query: string) { return users.filter(user => user.name.toLowerCase().includes(query.toLowerCase())); }\n",
                "Create a users array, call filterUsers, and assert length is 1.",
                "Uses Vitest",
                "Asserts the visible filtering behavior"),
            null,
            ViteReactDocs),
        new(
            "react-lite-polish-accessibility",
            "Finishing the application",
            26,
            "Polish responsiveness and accessibility",
            "A functional dashboard should work with a keyboard, readable labels, and common screen sizes.",
            "Semantic elements, labels, focus styles, responsive Tailwind utilities, and sensible empty/error messages cover a large portion of first-project accessibility.",
            "Tab through the whole application. Ensure buttons and links have visible focus, inputs have labels, tables have headings, and mobile layouts do not force unusable horizontal navigation.",
            "<label htmlFor='email'>Email</label><input id='email' type='email' />",
            ReactChoice(
                "Label a form control",
                "What is the strongest default way to give an email input an accessible name?",
                "label",
                [new("label", "Associate a visible label with it"), new("placeholder", "Use placeholder text only"), new("none", "Rely on position")],
                "Visible labels are clear and accessible.",
                "Applies basic accessibility checks"),
            null,
            ReactDocs),
        new(
            "react-lite-capstone",
            "Finishing the application",
            27,
            "Ship your first React admin dashboard",
            "A useful first dashboard should be coherent enough to explain, debug, and extend without rewriting its foundations.",
            "A complete dashboard combines routes, layout, components, typed data models, Tailwind styling, an async API boundary, CRUD forms, filtering, state, and focused tests.",
            "Build an Admin Dashboard with Dashboard, Users, User Details/Edit, and Add User pages. Show summary cards and a searchable/filterable table. Put all simulated reads/writes behind usersApi. Include loading/error/empty states, responsive navigation, accessible forms, and a few focused tests. A future real API should be swappable into the service layer without rewriting the UI.",
            "Vite + React + TypeScript + React Router + Tailwind -> pages -> components -> usersApi -> CRUD dashboard",
            ReactCode(
                "Compose the dashboard page",
                "Export DashboardPage with users:User[] props. Render at least one StatCard and a UserTable using the provided users.",
                "type User = { id: string; name: string; email: string; status: 'active' | 'disabled' };\n\nfunction StatCard({ label, value }: { label: string; value: number }) { return <section><span>{label}</span><strong>{value}</strong></section>; }\nfunction UserTable({ users }: { users: User[] }) { return <div>{users.length} users</div>; }\n\nexport function DashboardPage() {\n  return null;\n}",
                "Give DashboardPage a users prop, derive a count, then compose StatCard and UserTable.",
                "Composes StatCard",
                "Composes UserTable"),
            null,
            ReactDocs)
    ]);
}
