static partial class Curriculum
{
    private static VersionStamp ReactDocs => new(
        "React 19.3",
        "React",
        "2026-09-26",
        "https://react.dev/reference/react");

    private static VersionStamp ReactHooksDocs => new(
        "React 19.3",
        "Hooks",
        "2026-09-26",
        "https://react.dev/reference/react/hooks");

    private static VersionStamp ViteReactDocs => new(
        "React 19.3 / TypeScript 6",
        "Vite 8.1",
        "2026-09-26",
        "https://vite.dev/guide/");

    private static VersionStamp ReactRouterDocs => new(
        "React Router 8",
        "Data Mode",
        "2026-09-26",
        "https://reactrouter.com/start/data/installation");

    private static VersionStamp TailwindDocs => new(
        "Tailwind CSS 4.3",
        "Vite",
        "2026-09-26",
        "https://tailwindcss.com/docs/installation/using-vite");

    private static VersionStamp TypeScriptDocs => new(
        "TypeScript 6.0",
        "Strict ESM",
        "2026-09-26",
        "https://www.typescriptlang.org/docs/handbook/release-notes/typescript-6-0.html");

    private static Exercise ReactChoice(
        string title,
        string prompt,
        string correct,
        Choice[] choices,
        string hint,
        params string[] tests) =>
        new(
            ExerciseKind.MultipleChoice,
            title,
            prompt,
            ["Choose the best answer"],
            null,
            correct,
            choices,
            hint,
            tests);

    private static Exercise ReactCode(
        string title,
        string prompt,
        string starter,
        string hint,
        params string[] tests) =>
        new(
            ExerciseKind.Code,
            title,
            prompt,
            [
                "Write TypeScript/TSX that satisfies the requested behavior",
                "Prefer explicit domain types and readable component boundaries",
                "The isolated evaluator type-checks the submission before applying lesson-specific checks"
            ],
            starter,
            null,
            [],
            hint,
            tests);

    public static Lesson[] BuildReactCourseLessons() => NormalizeLessons(
    [
        new(
            "react-vite-bootstrap",
            "React project foundations",
            1,
            "Bootstrap React with Vite and TypeScript",
            "Start from a modern, boring toolchain that is fast locally and unsurprising in CI.",
            "Vite owns the development/build pipeline; React owns UI rendering; TypeScript proves contracts before runtime.",
            "For a greenfield enterprise SPA, start with Vite's React + TypeScript template, enable strict type checking, and keep the application entry point tiny. Build tooling belongs at the edge of the application, not inside domain features.",
            "npm create vite@latest acme-portal -- --template react-ts\ncd acme-portal\nnpm install",
            ReactChoice(
                "Pick the bootstrap boundary",
                "Which tool should own the dev server and production bundle in this course?",
                "vite",
                [new("vite", "Vite"), new("react", "React itself"), new("router", "React Router")],
                "React renders UI; Vite is the build tool.",
                "Separates build tooling from UI runtime responsibilities"),
            null,
            ViteReactDocs),
        new(
            "react-router-tailwind-baseline",
            "React project foundations",
            2,
            "Add React Router and Tailwind CSS",
            "Install routing and styling deliberately instead of turning the app entry point into a dependency pile.",
            "React Router Data Mode owns URL-driven data and mutations; Tailwind's Vite plugin supplies zero-runtime utility CSS.",
            "Install react-router and use createBrowserRouter with RouterProvider for enterprise SPA routing. Install tailwindcss plus @tailwindcss/vite, add the Vite plugin, and import Tailwind once from the application stylesheet. Keep these integrations in the composition/build layer.",
            "npm i react-router\nnpm i tailwindcss @tailwindcss/vite",
            ReactChoice(
                "Choose the router mode",
                "Which React Router mode does this course use as the enterprise SPA default?",
                "data",
                [new("data", "Data Mode"), new("declarative", "Declarative mode only"), new("none", "No router")],
                "Data Mode adds loaders, actions, pending states, and fetchers while preserving SPA architectural control.",
                "Chooses a routing model that centralizes route data and mutations"),
            null,
            ReactRouterDocs),
        new(
            "react-typescript-strict",
            "React project foundations",
            3,
            "Use strict TypeScript as a design tool",
            "TypeScript should make invalid business states harder to express, not just silence editor warnings.",
            "Strict types, discriminated unions, readonly data, and narrow boundary parsing turn domain assumptions into executable documentation.",
            "Keep strict mode enabled. Model IDs, statuses, commands, and API results deliberately. Prefer unknown over any at trust boundaries and narrow it before it enters feature code. Keep transport DTOs separate from richer UI/domain models when their responsibilities differ.",
            "type OrderStatus = 'draft' | 'submitted' | 'approved'\ntype Order = Readonly<{ id: string; status: OrderStatus }>",
            ReactChoice(
                "Model a business status",
                "Which TypeScript shape best prevents an arbitrary string from becoming an order status?",
                "union",
                [new("union", "A string-literal union"), new("string", "Plain string"), new("any", "any")],
                "A narrow union encodes the allowed states.",
                "Uses the type system to constrain domain state"),
            null,
            TypeScriptDocs),
        new(
            "react-enterprise-folders",
            "React project foundations",
            4,
            "Organize by application and business boundaries",
            "A folder structure is useful only when it communicates ownership and dependency direction.",
            "Use app for composition, routes for URL/page boundaries, features for business capabilities, components/ui for reusable primitives, services for external boundaries, and lib/types for truly shared infrastructure.",
            "A durable starting structure is src/app, src/routes, src/features, src/components/ui, src/components/layout, src/services/api, src/hooks, src/lib, src/types, and src/test. Feature code may depend on shared UI/lib/services, but shared primitives should not import business features. Avoid a giant undifferentiated components folder.",
            "src/\n  app/\n  routes/\n  features/orders/\n  components/ui/\n  components/layout/\n  services/api/\n  hooks/\n  lib/\n  types/\n  test/",
            ReactChoice(
                "Place domain behavior",
                "Where should order approval UI and order-specific hooks normally live?",
                "feature",
                [new("feature", "features/orders"), new("ui", "components/ui"), new("app", "app")],
                "Business-specific code belongs with the business capability.",
                "Separates business capabilities from reusable primitives"),
            null,
            ReactDocs),
        new(
            "react-composition-root",
            "React project foundations",
            5,
            "Build a thin application composition root",
            "Top-level providers and infrastructure should be assembled once rather than recreated inside feature code.",
            "The composition root wires RouterProvider, global error handling, external-store providers, feature flags, telemetry, and other app-wide dependencies.",
            "Keep main.tsx and App providers boring. Instantiate long-lived infrastructure outside render where appropriate. Feature modules should consume interfaces/hooks exposed by providers instead of constructing API clients, routers, or telemetry SDKs during rendering.",
            "createRoot(document.getElementById('root')!).render(<AppProviders><RouterProvider router={router} /></AppProviders>)",
            ReactCode(
                "Compose the application",
                "Write an AppRoot component that renders RouterProvider with a router prop inside an AppProviders component.",
                "import type { ReactNode } from 'react';\nimport { createBrowserRouter } from 'react-router';\nimport { RouterProvider } from 'react-router/dom';\n\ntype Props = { router: ReturnType<typeof createBrowserRouter> };\n\nexport function AppRoot({ router }: Props) {\n  return null;\n}\n\nfunction AppProviders({ children }: { children: ReactNode }) {\n  return <>{children}</>;\n}",
                "Return AppProviders containing RouterProvider and pass router through explicitly.",
                "Preserves a thin composition root",
                "Keeps router infrastructure above business features"),
            null,
            ReactDocs),

        new(
            "react-create-root-render-tree",
            "React rendering model",
            6,
            "Understand createRoot and the React tree",
            "React manages a tree of component output and commits the minimum DOM work needed to reflect state.",
            "createRoot creates a client root; render describes the desired tree; React reconciles that description with the previous render.",
            "Rendering a component calls its function to produce React elements. React may render more than once before committing. Rendering must therefore be pure: no network calls, DOM mutation, or irreversible work in the component body.",
            "const root = createRoot(document.getElementById('root')!)\nroot.render(<App />)",
            ReactChoice(
                "Place a side effect",
                "Where should a network subscription be started rather than during component rendering?",
                "effect",
                [new("effect", "An Effect or external data layer"), new("render", "Directly in the component body"), new("jsx", "Inside JSX")],
                "Render must stay pure because React can call it repeatedly.",
                "Distinguishes render from commit/effect work"),
            null,
            ReactDocs),
        new(
            "react-jsx-purity",
            "React rendering model",
            7,
            "Treat components as pure render functions",
            "React can schedule, restart, and discard renders only if components behave predictably.",
            "Given the same props, state, and context, a component's render output should be deterministic.",
            "Do not mutate module state, props, or objects owned by another component during render. Derive values directly when possible. Use event handlers for user-triggered work and Effects only for synchronization with external systems.",
            "function Total({ lines }: { lines: Line[] }) { return <strong>{lines.reduce((sum, line) => sum + line.amount, 0)}</strong> }",
            ReactChoice(
                "Keep render pure",
                "Which operation is safe during render?",
                "derive",
                [new("derive", "Deriving a total from props"), new("fetch", "Starting a fetch for every render"), new("mutate", "Mutating a prop array")],
                "Pure derivation is safe; effects and mutation are not.",
                "Applies component purity rules"),
            null,
            ReactDocs),
        new(
            "react-props-composition",
            "React rendering model",
            8,
            "Design components with props and composition",
            "Enterprise components should expose stable intent rather than leaking internal markup.",
            "Props are inputs; children and render composition let parents control structure without turning every component into a configuration object.",
            "Prefer focused props such as status, onApprove, and children. Avoid boolean explosions that create dozens of invalid combinations. Split components when different modes have meaningfully different responsibilities.",
            "type StatusBadgeProps = { status: 'draft' | 'approved' }",
            ReactCode(
                "Build a typed status component",
                "Create and export OrderStatusBadge with a status prop limited to draft, submitted, or approved. Render the status in a span.",
                "type OrderStatus = 'draft' | 'submitted' | 'approved';\n\nexport function OrderStatusBadge() {\n  return null;\n}",
                "Give the component a typed props object and return a span that renders status.",
                "Uses a narrow domain prop",
                "Renders data instead of duplicating state"),
            null,
            ReactDocs),
        new(
            "react-state-snapshots-batching",
            "React rendering model",
            9,
            "Understand state snapshots and batching",
            "State belongs to a render snapshot; setting state schedules another render rather than changing the current variable.",
            "React batches related updates and computes the next render from queued state transitions.",
            "If the next state depends on the previous state, use a functional updater. Do not read a state variable immediately after setting it and assume it changed in the same render. This mental model prevents stale updates and race-like UI bugs.",
            "setCount(value => value + 1)",
            ReactChoice(
                "Update from previous state",
                "Which update is safest when the next value depends on the previous value?",
                "functional",
                [new("functional", "setCount(current => current + 1)"), new("snapshot", "setCount(count + 1) repeated several times"), new("mutation", "count++")],
                "Functional updates compose correctly with queued updates.",
                "Understands state snapshots and queued updates"),
            null,
            ReactDocs),
        new(
            "react-events-controlled-inputs",
            "React rendering model",
            10,
            "Handle events and form inputs deliberately",
            "Event handlers represent user intent; controlled state is useful when the application must own a field's current value.",
            "React event handlers run in response to interactions. Inputs may be controlled by state or left uncontrolled and read at submission time.",
            "Use controlled fields when live validation, dependent UI, or centralized state requires it. Prefer native form behavior and FormData when full keystroke-by-keystroke control adds no value. Avoid mirroring every DOM value into React state by reflex.",
            "<input value={query} onChange={event => setQuery(event.target.value)} />",
            ReactChoice(
                "Choose state ownership",
                "When is a controlled input most justified?",
                "live",
                [new("live", "The UI must react to each value change"), new("always", "Every input regardless of need"), new("never", "Controlled inputs should never be used")],
                "Control should serve a behavior requirement.",
                "Chooses appropriate form state ownership"),
            null,
            ReactDocs),
        new(
            "react-lists-keys-reconciliation",
            "React rendering model",
            11,
            "Use stable keys to preserve identity",
            "Keys tell React which sibling is which across renders.",
            "Reconciliation uses element type and key to determine whether stateful subtrees are preserved, moved, or replaced.",
            "Use stable business identifiers as keys. Array indexes are risky when items can be inserted, removed, or reordered because component state may follow position instead of the business entity.",
            "{orders.map(order => <OrderRow key={order.id} order={order} />)}",
            ReactChoice(
                "Choose a list key",
                "Which key is best for reorderable order rows?",
                "id",
                [new("id", "order.id"), new("index", "The array index"), new("random", "Math.random()")],
                "Stable domain identity is the right key.",
                "Preserves component identity through list changes"),
            null,
            ReactDocs),

        new(
            "react-use-state",
            "Hooks and state",
            12,
            "Use useState for local independent state",
            "Local UI state belongs near the component that owns the interaction.",
            "useState stores one value across renders and returns the current snapshot plus a setter.",
            "Use useState for focused local concerns such as disclosure, selection, or editable draft values. If multiple fields change together under named business events, a reducer often expresses the state machine more clearly.",
            "const [open, setOpen] = useState(false)",
            ReactCode(
                "Implement local disclosure state",
                "Create an OrderDetails component using useState(false). Render a button that toggles details and conditionally render a section.",
                "import { useState } from 'react';\n\nexport function OrderDetails() {\n  return null;\n}",
                "Use a boolean state value, a button onClick handler, and conditional JSX.",
                "Uses useState for local UI state",
                "Uses functional or explicit state updates"),
            null,
            ReactHooksDocs),
        new(
            "react-use-reducer",
            "Hooks and state",
            13,
            "Model complex state transitions with useReducer",
            "Reducers make multi-step UI state transitions explicit and testable.",
            "useReducer centralizes state transition logic around actions rather than scattering related setters.",
            "Use discriminated action unions for business-like transitions such as started, succeeded, failed, and reset. Reducers must stay pure. Server data still belongs in route loaders or a server-state cache rather than being moved into a reducer just because the state is complex.",
            "type Action = { type: 'submitted' } | { type: 'approved' }",
            ReactCode(
                "Build a reducer state machine",
                "Define a reducer for draft -> submitted -> approved and export OrderWorkflow using useReducer. Use a discriminated Action union.",
                "import { useReducer } from 'react';\n\ntype State = { status: 'draft' | 'submitted' | 'approved' };\ntype Action = never;\n\nexport function OrderWorkflow() {\n  return null;\n}",
                "Give Action named variants, keep reducer pure, and call useReducer from the component.",
                "Models transitions with explicit actions",
                "Keeps reducer logic pure"),
            null,
            ReactHooksDocs),
        new(
            "react-refs-fragments-imperative",
            "Hooks and state",
            14,
            "Use refs as an escape hatch",
            "Refs hold values that do not participate in rendering and can point at DOM or imperative APIs.",
            "useRef preserves a mutable value without re-rendering; refs can be passed as props in modern React; useImperativeHandle narrows an exposed imperative surface.",
            "Use refs for focus, measurement, timer handles, third-party widgets, and similar escape hatches. Do not use a ref when the value should update the UI. React 19.3 also supports refs on Fragments for controlled access to a group of sibling DOM nodes.",
            "const inputRef = useRef<HTMLInputElement>(null)",
            ReactChoice(
                "Choose ref or state",
                "Which value belongs in a ref rather than state?",
                "timer",
                [new("timer", "A timeout handle that should not render"), new("status", "The visible order status"), new("error", "A validation message shown to the user")],
                "Refs are for mutable information that does not drive rendering.",
                "Uses refs only for non-render state and imperative integration"),
            null,
            ReactHooksDocs),
        new(
            "react-effects-synchronization",
            "Hooks and state",
            15,
            "Use Effects only to synchronize external systems",
            "Effects are for synchronization, not for ordinary data derivation.",
            "useEffect runs after commit to connect React state to systems outside React and can return cleanup logic.",
            "Good Effects subscribe/unsubscribe, synchronize browser APIs, or integrate imperative libraries. Do not use Effects to derive state from props, sequence normal event logic, or fetch route data that a router loader already owns. Every dependency read by reactive Effect logic belongs in the dependency list.",
            "useEffect(() => { const controller = new AbortController(); return () => controller.abort(); }, [])",
            ReactCode(
                "Synchronize and clean up",
                "Write useOrderStream(orderId) with useEffect. Call subscribeToOrder(orderId, callback) and return the unsubscribe function.",
                "import { useEffect } from 'react';\n\ndeclare function subscribeToOrder(id: string, listener: () => void): () => void;\n\nexport function useOrderStream(orderId: string) {\n}",
                "Call subscribeToOrder inside the Effect and return its cleanup. orderId must be a dependency.",
                "Creates and cleans up an external subscription",
                "Declares the reactive dependency"),
            null,
            ReactHooksDocs),
        new(
            "react-effect-event-layout-insertion",
            "Hooks and state",
            16,
            "Know the specialized Effect hooks",
            "Most application synchronization uses useEffect; the specialized variants solve narrower timing problems.",
            "useEffectEvent separates non-reactive Effect event logic, useLayoutEffect runs before paint for layout-sensitive work, and useInsertionEffect exists primarily for CSS-in-JS library insertion.",
            "Use useEffectEvent when Effect logic needs latest values without making those values re-connect the external system. Use useLayoutEffect only when measuring or mutating layout before paint is necessary. Application feature code should almost never need useInsertionEffect.",
            "const onConnected = useEffectEvent(() => notify(theme))",
            ReactChoice(
                "Avoid restarting a subscription",
                "Which API can read the latest theme from Effect logic without making theme reconnect the subscription?",
                "effectevent",
                [new("effectevent", "useEffectEvent"), new("memo", "useMemo"), new("insertion", "useInsertionEffect")],
                "Effect Events separate non-reactive logic from Effect dependencies.",
                "Distinguishes specialized Effect semantics"),
            null,
            ReactHooksDocs),
        new(
            "react-context-provider-boundaries",
            "Hooks and state",
            17,
            "Use context for ambient dependencies",
            "Context solves distant dependency propagation, not every shared-state problem.",
            "createContext defines an ambient value and useContext subscribes a component to the nearest provider value.",
            "Use context for stable cross-cutting concerns such as current tenant, locale, theme, or dependency interfaces. Keep provider values focused and split unrelated contexts to avoid broad re-render fanout. Server state should not automatically be pushed into one global context.",
            "const TenantContext = createContext<TenantContextValue | null>(null)",
            ReactCode(
                "Create a required tenant context",
                "Create TenantContext, TenantProvider, and useTenant. useTenant should throw when called outside the provider.",
                "import { createContext, useContext, type ReactNode } from 'react';\n\ntype Tenant = { id: string; name: string };\n",
                "Create a nullable context, provide the tenant, and enforce provider presence in the custom hook.",
                "Creates a focused context",
                "Encapsulates null checking in a custom hook"),
            null,
            ReactHooksDocs),
        new(
            "react-memo-compiler",
            "Hooks and state",
            18,
            "Understand memoization and React Compiler",
            "Performance work should follow evidence, and modern React can automate much of the memoization people previously wrote by hand.",
            "React Compiler performs build-time memoization; memo, useMemo, and useCallback remain available when precise identity control matters.",
            "Do not reflexively wrap every component and callback. Profile first. With React Compiler enabled, trust it for ordinary memoization and retain manual memoization when identity is semantically significant, expensive work is proven, or an Effect dependency requires precise stability.",
            "const filtered = useMemo(() => expensiveFilter(rows, query), [rows, query])",
            ReactChoice(
                "Choose an optimization strategy",
                "What is the recommended first step before adding manual memoization?",
                "profile",
                [new("profile", "Measure/profile the actual render cost"), new("memoall", "Wrap every function in useCallback"), new("global", "Move all state global")],
                "Optimization should be evidence-driven.",
                "Understands compiler-era memoization strategy"),
            null,
            ReactHooksDocs),
        new(
            "react-transitions-deferred",
            "Hooks and state",
            19,
            "Separate urgent and non-urgent rendering",
            "Concurrent rendering APIs let responsive interactions stay urgent while heavier UI catches up.",
            "startTransition/useTransition mark non-urgent state updates; useDeferredValue lets a slower subtree lag behind a rapidly changing value.",
            "Typing into an input is urgent. Re-rendering an expensive result grid from that query may be non-urgent. Transitions do not make computation cheaper; they change scheduling priority and let React interrupt/restart work.",
            "const [isPending, startTransition] = useTransition()",
            ReactChoice(
                "Schedule result rendering",
                "Which update should usually remain urgent?",
                "input",
                [new("input", "The controlled text input value"), new("grid", "A large derived result grid"), new("report", "A background report view")],
                "Direct interaction feedback should remain urgent.",
                "Distinguishes urgent and transition work"),
            null,
            ReactHooksDocs),
        new(
            "react-external-store-custom-hooks",
            "Hooks and state",
            20,
            "Integrate external stores and package reusable logic",
            "React exposes explicit hooks for subscribing to state React does not own.",
            "useSyncExternalStore safely subscribes to external stores; useDebugValue improves custom-hook DevTools labels; custom hooks package reusable stateful logic while obeying the Rules of Hooks.",
            "Use useSyncExternalStore for browser or third-party stores that need consistent snapshots across concurrent rendering. Custom hooks should express a coherent capability such as useTenantPermissions, not merely hide arbitrary lines of code.",
            "const value = useSyncExternalStore(store.subscribe, store.getSnapshot)",
            ReactChoice(
                "Subscribe to an external store",
                "Which hook is designed for concurrency-safe external store subscriptions?",
                "external",
                [new("external", "useSyncExternalStore"), new("effect", "useEffect alone"), new("ref", "useRef")],
                "React provides a dedicated external-store subscription contract.",
                "Chooses the supported external store integration"),
            null,
            ReactHooksDocs),
        new(
            "react-actions-optimistic-use",
            "Hooks and state",
            21,
            "Use Actions and optimistic UI",
            "Modern React includes primitives for mutation state, optimistic values, and async resource consumption.",
            "useActionState manages action result/pending state, useOptimistic represents temporary UI, useFormStatus exposes parent form submission status, and use can read supported async/context resources while suspending when necessary.",
            "Use these APIs when they simplify a mutation flow, but keep server authority clear. Optimistic state must reconcile with the server result. A pending button using useFormStatus must be rendered inside the form it observes.",
            "const [state, submitAction, isPending] = useActionState(saveOrder, initialState)",
            ReactCode(
                "Model an action-driven form",
                "Create SaveButton using useFormStatus and OrderForm using useActionState(saveOrder, initialState). The form action should be the action returned by useActionState.",
                "import { useActionState } from 'react';\nimport { useFormStatus } from 'react-dom';\n\ntype State = { error?: string };\nconst initialState: State = {};\ndeclare function saveOrder(state: State, data: FormData): Promise<State>;\n",
                "SaveButton must read pending from useFormStatus. OrderForm should pass the returned action to form action.",
                "Uses action state for mutation lifecycle",
                "Exposes pending form state to the submit control"),
            null,
            ReactHooksDocs),
        new(
            "react-suspense-lazy-errors",
            "Hooks and state",
            22,
            "Coordinate async rendering with Suspense and error boundaries",
            "Suspense describes a loading boundary while error boundaries isolate render failures.",
            "lazy defers component code loading; Suspense renders a fallback while a child suspends; error boundaries contain render/lifecycle failures.",
            "Place boundaries around meaningful product regions rather than wrapping every leaf. Suspense is not a generic replacement for all loading state. Router pending UI and data-library semantics may provide better ownership depending on where the async work originates.",
            "<Suspense fallback={<PageSkeleton />}><LazyReport /></Suspense>",
            ReactChoice(
                "Place a boundary",
                "Where is a Suspense boundary most useful?",
                "region",
                [new("region", "Around a meaningful async product region"), new("every", "Around every span"), new("none", "Suspense should never be used")],
                "Boundaries should correspond to meaningful user-visible loading regions.",
                "Uses async boundaries intentionally"),
            null,
            ReactDocs),
        new(
            "react-dom-escape-hatches",
            "Hooks and state",
            23,
            "Know the React DOM escape hatches",
            "React DOM exposes imperative APIs for cases where normal tree composition cannot express the requirement.",
            "createPortal renders children into another DOM location while preserving React parentage; flushSync forces a synchronous commit and should be rare; createRoot/hydrateRoot own root lifecycle.",
            "Use portals for modals, tooltips, and layered UI that must escape DOM clipping or stacking contexts. Use flushSync only when an external imperative API truly requires the DOM to be updated before the next line runs.",
            "createPortal(<Dialog />, document.body)",
            ReactChoice(
                "Render a modal layer",
                "Which API renders React children elsewhere in the DOM while preserving React context/event relationships?",
                "portal",
                [new("portal", "createPortal"), new("root", "A second createRoot by default"), new("flush", "flushSync")],
                "Portals preserve the React tree while changing DOM placement.",
                "Chooses the correct DOM escape hatch"),
            null,
            ReactDocs),
        new(
            "react-view-transitions",
            "Hooks and state",
            24,
            "Use React 19.3 View Transitions",
            "View transitions can make route and state changes feel continuous without hand-managing the browser transition lifecycle.",
            "ViewTransition participates when React updates occur through transitions, Suspense reveals, or deferred values.",
            "Use ViewTransition as progressive enhancement around meaningful visual changes. Keep accessibility and reduced-motion behavior in mind. The animation should support orientation, not mask slow application work.",
            "<ViewTransition><OrderPage /></ViewTransition>",
            ReactChoice(
                "Trigger a React view transition",
                "Which update is eligible to participate in a React ViewTransition?",
                "transition",
                [new("transition", "An update scheduled with startTransition"), new("urgent", "Every urgent keystroke automatically"), new("mutation", "Direct DOM mutation outside React")],
                "React coordinates ViewTransition with transition-class updates and Suspense/deferred reveals.",
                "Connects scheduling to visual transitions"),
            null,
            ReactDocs),

        new(
            "react-id-imperative-handle",
            "Hooks and state",
            24,
            "Use IDs and imperative handles deliberately",
            "React exposes escape hatches for accessibility identity and narrowly scoped imperative behavior.",
            "useId creates stable IDs for accessibility relationships; useImperativeHandle lets a component expose a constrained ref API instead of its raw DOM implementation.",
            "Use useId to connect labels, descriptions, and controls when a reusable component cannot rely on a caller-supplied ID. Use imperative handles sparingly for capabilities such as focus or reset. Prefer declarative props/state when the behavior can be expressed through normal rendering.",
            "const descriptionId = useId()",
            ReactChoice(
                "Connect an accessible description",
                "Which hook creates a stable identifier suitable for linking aria-describedby to reusable component content?",
                "id",
                [new("id", "useId"), new("ref", "useRef"), new("memo", "useMemo")],
                "useId provides hydration-safe identifiers for accessibility relationships.",
                "Uses identity and imperative APIs for their intended narrow roles"),
            null,
            ReactHooksDocs),
        new(
            "react-strictmode-profiler-activity",
            "Hooks and state",
            24,
            "Diagnose lifecycle assumptions with StrictMode, Profiler, and Activity",
            "React includes components that expose unsafe lifecycle assumptions, measure rendering, and control background UI lifecycle.",
            "StrictMode adds development checks, Profiler measures render work, and Activity can hide a subtree while preserving its state for later restoration.",
            "Keep StrictMode enabled in development so impure rendering and missing cleanup surface early. Use Profiler around a meaningful product region while investigating performance. Use Activity when retaining hidden UI state has real product value; hidden UI still has lifecycle and resource implications, so it is not a substitute for architecture.",
            "<StrictMode><Profiler id='orders' onRender={onRender}><App /></Profiler></StrictMode>",
            ReactChoice(
                "Investigate duplicate development behavior",
                "A subscription appears twice only in development under StrictMode. What should you inspect first?",
                "cleanup",
                [new("cleanup", "Render purity and Effect cleanup"), new("disable", "Disable StrictMode permanently"), new("memo", "Memoize every component")],
                "StrictMode deliberately probes assumptions that often reveal missing cleanup or impure code.",
                "Uses React diagnostics instead of hiding lifecycle bugs"),
            null,
            ReactDocs),

        new(
            "react-router-data-mode",
            "Routing and page data",
            25,
            "Create a Data Mode router",
            "Route configuration should sit outside the render tree and describe page hierarchy, data, mutations, and error boundaries.",
            "createBrowserRouter creates a Data Router; RouterProvider renders it and enables loaders, actions, pending navigation, and fetchers.",
            "Create the router once outside component rendering. Treat routes as application boundaries that map URLs to page orchestration. Reusable feature components should not need to know the entire route tree.",
            "const router = createBrowserRouter([{ path: '/', Component: RootLayout }])",
            ReactCode(
                "Create the router",
                "Export a router from createBrowserRouter with a root path and an orders child path. The child should render OrdersPage.",
                "import { createBrowserRouter } from 'react-router';\n\nfunction RootLayout() { return <div />; }\nfunction OrdersPage() { return <h1>Orders</h1>; }\n\nexport const router = null;",
                "Call createBrowserRouter with nested route objects.",
                "Creates the router outside React state",
                "Models a nested page boundary"),
            null,
            ReactRouterDocs),
        new(
            "react-router-layouts-outlet",
            "Routing and page data",
            26,
            "Compose nested layouts and pages",
            "Nested routes let shared application chrome and feature layouts remain mounted while child content changes.",
            "Outlet renders the matched child route inside a parent layout.",
            "Use layouts for persistent navigation, tenant chrome, or domain shells. Pages/routes orchestrate data and features; they should not become a dumping ground for reusable controls.",
            "<main><Outlet /></main>",
            ReactChoice(
                "Render a nested route",
                "Which component renders the active child route inside a parent route component?",
                "outlet",
                [new("outlet", "Outlet"), new("link", "Link"), new("navigate", "Navigate")],
                "Outlet is the nested route placeholder.",
                "Uses route layouts as composition boundaries"),
            null,
            ReactRouterDocs),
        new(
            "react-router-loaders-params-search",
            "Routing and page data",
            27,
            "Load page data from URL state",
            "URL params and search params are application state that can be shared, bookmarked, refreshed, and navigated.",
            "Route loaders run before rendering the route and receive request/params; useLoaderData reads the resolved data.",
            "Put page-entry reads in loaders when the URL determines the resource. Parse and validate params/search values at the route boundary. Return typed domain/DTO data rather than making child components parse window.location.",
            "export async function loader({ params }: LoaderFunctionArgs) { return getOrder(params.orderId!) }",
            ReactCode(
                "Load an order route",
                "Export an async loader that reads params.orderId, throws when it is missing, and returns getOrder(orderId).",
                "import type { LoaderFunctionArgs } from 'react-router';\n\ndeclare function getOrder(id: string): Promise<{ id: string }>;\n\nexport async function loader({ params }: LoaderFunctionArgs) {\n}",
                "Validate orderId before calling getOrder.",
                "Loads URL-owned page data at the route boundary",
                "Validates required params"),
            null,
            ReactRouterDocs),
        new(
            "react-router-actions-navigation",
            "Routing and page data",
            28,
            "Mutate through route actions and expose navigation state",
            "Mutations should have a deliberate boundary and a user-visible pending/error lifecycle.",
            "Route actions handle submissions; Form integrates navigation with actions; useNavigation reports the active navigation/submission state.",
            "Use actions for page-level mutations tied to navigation semantics. Let the router revalidate loader data after successful mutations rather than manually synchronizing multiple copies of the same server data.",
            "<Form method='post'><button>Approve</button></Form>",
            ReactCode(
                "Create an approval action",
                "Export an async action that reads orderId from params and calls approveOrder(orderId). Also export ApproveForm using Form method='post'.",
                "import { Form, type ActionFunctionArgs } from 'react-router';\n\ndeclare function approveOrder(id: string): Promise<void>;\n",
                "Validate the route param, call approveOrder, and render a post Form.",
                "Keeps mutation semantics at the route boundary",
                "Uses router-native form submission"),
            null,
            ReactRouterDocs),
        new(
            "react-router-fetcher",
            "Routing and page data",
            29,
            "Use fetchers for non-navigation mutations",
            "Some route actions should run without changing the current location.",
            "useFetcher loads/submits against route actions and exposes its own idle/submitting/loading lifecycle.",
            "Use fetchers for inline toggles, row actions, autosave, and similar interactions where navigation would be disruptive. Keep optimistic UI and duplicate-submission behavior deliberate.",
            "const fetcher = useFetcher()",
            ReactChoice(
                "Approve from a table row",
                "Which router API best fits an inline row mutation that should not navigate away?",
                "fetcher",
                [new("fetcher", "useFetcher"), new("navigate", "Always navigate to a new page"), new("effect", "A useEffect watching a boolean")],
                "A fetcher owns non-navigation router submissions.",
                "Chooses navigation vs non-navigation mutation semantics"),
            null,
            ReactRouterDocs),
        new(
            "react-router-errors-lazy",
            "Routing and page data",
            30,
            "Design route errors and code splitting",
            "Failure and loading boundaries should align with route ownership.",
            "Route error elements/useRouteError isolate loader/action/render failures; lazy route modules split page code from the initial bundle.",
            "Give users actionable route-level error states and log technical details centrally. Split by page or large business capability, not every tiny component. Keep a small critical shell eagerly loaded.",
            "lazy: () => import('./routes/orders')",
            ReactChoice(
                "Choose a split boundary",
                "Which code-splitting boundary is usually most maintainable?",
                "route",
                [new("route", "A substantial route/business capability"), new("span", "Every individual UI primitive"), new("random", "Random files")],
                "Route/capability boundaries align bundle ownership with product structure.",
                "Aligns failure and loading boundaries with route ownership"),
            null,
            ReactRouterDocs),

        new(
            "react-api-client-boundary",
            "Enterprise application patterns",
            31,
            "Build a typed API boundary",
            "Components should not each reinvent fetch, base URLs, auth headers, error parsing, cancellation, and DTO mapping.",
            "A focused API layer owns transport concerns and returns typed results or throws known application errors.",
            "Centralize request construction, credentials, correlation IDs, cancellation, and response normalization. Keep endpoint functions domain-oriented such as getOrder and approveOrder. Do not create a generic mega-client that hides every HTTP semantic behind one untyped method.",
            "export async function getOrder(id: string, signal?: AbortSignal): Promise<OrderDto>",
            ReactCode(
                "Write a cancellable API function",
                "Implement getOrder(id, signal) using fetch('/api/orders/' + encodeURIComponent(id), { signal }). Throw on a non-ok response and return parsed JSON.",
                "type OrderDto = { id: string; status: string };\n\nexport async function getOrder(id: string, signal?: AbortSignal): Promise<OrderDto> {\n  throw new Error('todo');\n}",
                "Use encodeURIComponent, pass signal to fetch, check response.ok, then parse JSON.",
                "Centralizes HTTP failure handling",
                "Supports cancellation"),
            null,
            ReactDocs),
        new(
            "react-state-ownership-server-client",
            "Enterprise application patterns",
            32,
            "Separate server, URL, global, and local UI state",
            "Most React state problems are ownership problems.",
            "Server state is remote authority; URL state belongs in the URL; global ambient state should be rare; ephemeral interaction state belongs near the owning component.",
            "Prefer router loaders/actions for route-owned server data. A server-state library can add caching/background refresh where needed. Do not copy server data into local state just to read it. Do not put every value into one global store.",
            "URL -> loader data; server cache -> remote authority; useState -> local interaction",
            ReactChoice(
                "Own filter state",
                "A filter must survive refresh and be shareable by URL. Where should it live?",
                "url",
                [new("url", "Search params"), new("local", "Only component state"), new("global", "A global store regardless of need")],
                "Shareable navigable state belongs in the URL.",
                "Assigns state to the correct authority"),
            null,
            ReactDocs),
        new(
            "react-domain-forms-validation",
            "Enterprise application patterns",
            33,
            "Treat forms as domain commands",
            "Enterprise forms represent business intent, validation, and failure—not just bags of inputs.",
            "Native form semantics, FormData, route actions, field errors, and domain validation create a resilient mutation boundary.",
            "Separate syntactic field validation from business rules enforced by the server. Preserve user input on validation failure, announce errors accessibly, and map server field/global errors into a stable form result model.",
            "type SaveOrderResult = { fieldErrors?: Record<string, string>; formError?: string }",
            ReactChoice(
                "Place authorization validation",
                "Where must an authorization rule be enforced even if the React form hides the forbidden action?",
                "server",
                [new("server", "The server/API boundary"), new("client", "Only the browser"), new("css", "A disabled CSS class")],
                "Client validation improves UX but cannot enforce trust.",
                "Separates UX validation from authoritative business rules"),
            null,
            ReactDocs),
        new(
            "react-tailwind-design-system",
            "Enterprise application patterns",
            34,
            "Build a Tailwind 4 design system",
            "Utility CSS scales when teams share tokens, variants, primitives, and composition rules.",
            "Tailwind 4 uses CSS-first configuration and the Vite plugin; design tokens should represent product semantics rather than one-off magic values.",
            "Define theme tokens centrally, build reusable primitives for buttons/fields/panels, and keep business components responsible for business composition. Use responsive/container variants deliberately and avoid copy-pasting giant class strings across features.",
            "@import 'tailwindcss';",
            ReactCode(
                "Build a reusable button primitive",
                "Export Button with variant 'primary' | 'secondary', children, and standard button props. Compose a shared base class with variant classes.",
                "import type { ButtonHTMLAttributes, ReactNode } from 'react';\n\ntype Props = ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary'; children: ReactNode };\n\nexport function Button(props: Props) {\n  return null;\n}",
                "Destructure variant/children/className/rest, compose the classes, and spread remaining button props.",
                "Creates a typed UI primitive",
                "Keeps domain behavior out of reusable UI"),
            null,
            TailwindDocs),
        new(
            "react-accessible-components",
            "Enterprise application patterns",
            35,
            "Make accessibility part of the component contract",
            "Keyboard, focus, names, semantics, and announcements are correctness requirements for business software.",
            "Prefer semantic HTML first; manage focus only when interaction patterns require it; preserve accessible names and visible focus.",
            "Buttons should be buttons, links should navigate, labels should label controls, and dialogs need deliberate focus behavior. Reusable components must not make accessibility optional through careless prop APIs.",
            "<button type='button'>Approve order</button>",
            ReactChoice(
                "Choose a semantic element",
                "Which element should trigger an in-page approve action?",
                "button",
                [new("button", "button"), new("link", "a without an href"), new("div", "clickable div")],
                "Use the native element that expresses the interaction.",
                "Treats semantic accessibility as correctness"),
            null,
            ReactDocs),

        new(
            "react-testing-vitest-rtl",
            "Testing and production",
            36,
            "Test component behavior with Vitest and Testing Library",
            "Tests should observe what users can see and do rather than reaching into component implementation details.",
            "Vitest runs fast unit/component tests in a Vite-friendly environment; Testing Library queries the DOM through accessible/user-facing semantics.",
            "Prefer role/label/text queries and user-event interactions. Test business behavior and boundary states. Avoid asserting internal hook calls or component instance details that users cannot observe.",
            "render(<ApproveButton />); expect(screen.getByRole('button', { name: /approve/i })).toBeEnabled()",
            ReactCode(
                "Write a behavior-focused component test",
                "Write a Vitest/Testing Library test that renders <SaveButton /> and asserts a button named Save exists.",
                "import { render, screen } from '@testing-library/react';\nimport { describe, expect, it } from 'vitest';\n\nfunction SaveButton() { return <button>Save</button>; }\n",
                "Render the component and query it by role and accessible name.",
                "Tests observable behavior",
                "Uses accessible queries"),
            null,
            ViteReactDocs),
        new(
            "react-testing-network-contract",
            "Testing and production",
            37,
            "Test network boundaries without coupling to implementation",
            "Component tests need deterministic HTTP behavior while integration tests still need confidence in the real contract.",
            "Use a request mocking layer such as MSW for browser-like network interception and add contract/integration coverage at the API boundary.",
            "Mock the network, not the API client function internals, when the goal is to prove loading/success/error UI behavior. Keep a smaller set of real boundary tests to catch drift between frontend assumptions and backend contracts.",
            "server.use(http.get('/api/orders/:id', () => HttpResponse.json(order)))",
            ReactChoice(
                "Choose the test seam",
                "For a component that fetches /api/orders/42, what is the strongest component-test seam?",
                "network",
                [new("network", "Intercept the HTTP request at the network boundary"), new("hook", "Mock every internal hook"), new("dom", "Set component state by hand")],
                "A network seam preserves more of the real application stack.",
                "Tests behavior across the client boundary"),
            null,
            ReactDocs),
        new(
            "react-testing-playwright",
            "Testing and production",
            38,
            "Use Playwright for critical user journeys",
            "Browser tests should prove a small number of high-value flows across routing, rendering, network, and accessibility behavior.",
            "Playwright drives the real browser and is appropriate for login, navigation, business-critical mutations, and deployment smoke coverage.",
            "Keep E2E tests deterministic and focused on critical journeys. Use stable accessible locators. Do not duplicate every component test at the browser layer.",
            "await page.getByRole('button', { name: 'Approve' }).click()",
            ReactChoice(
                "Choose E2E scope",
                "Which flow most deserves Playwright coverage?",
                "critical",
                [new("critical", "A critical order-approval journey"), new("all", "Every prop combination of every button"), new("none", "No browser behavior")],
                "E2E tests are most valuable for high-risk user journeys.",
                "Balances test pyramid cost and confidence"),
            null,
            ReactDocs),
        new(
            "react-performance-profiler-compiler",
            "Testing and production",
            39,
            "Profile before optimizing",
            "Fast React apps come from good state ownership, small render surfaces, sensible bundles, and measured optimization.",
            "React DevTools Profiler identifies expensive commits; React Compiler automates memoization; lazy route boundaries cut initial JavaScript; virtualization handles truly large visible lists.",
            "Measure render frequency and duration before changing code. Fix broad context/state ownership first. Then optimize proven hot paths. A fast micro-component does not matter if the app downloads a huge initial bundle or refetches the same data repeatedly.",
            "profile -> locate bottleneck -> change one cause -> measure again",
            ReactChoice(
                "Fix a slow grid",
                "What should you do before adding useMemo/useCallback throughout a slow page?",
                "measure",
                [new("measure", "Profile and identify the actual bottleneck"), new("memo", "Memoize everything"), new("global", "Move all state into context")],
                "Evidence determines the optimization.",
                "Uses profiling and compiler-aware optimization"),
            null,
            ReactDocs),
        new(
            "react-feature-architecture",
            "Testing and production",
            40,
            "Enforce domain-oriented dependency boundaries",
            "A large React codebase stays maintainable when ownership is visible and dependency direction is constrained.",
            "Routes orchestrate; features own business behavior; shared UI/lib stay domain-agnostic; services own external I/O; app wires infrastructure.",
            "A feature folder may contain components, hooks, domain types, adapters, and tests that change together. Export a deliberate public surface from the feature instead of allowing cross-feature deep imports. Avoid both giant horizontal layer folders and a hyper-fragmented file-per-function maze.",
            "features/orders/index.ts -> deliberate public feature API",
            ReactChoice(
                "Prevent coupling",
                "Which import should normally be rejected?",
                "deep",
                [new("deep", "features/billing importing features/orders/internal/OrderReducer"), new("public", "A route importing from features/orders public index"), new("ui", "A feature importing a shared Button primitive")],
                "Cross-feature deep imports bypass ownership boundaries.",
                "Maintains feature encapsulation"),
            null,
            ReactDocs),
        new(
            "react-auth-security",
            "Testing and production",
            41,
            "Design frontend auth without confusing it for authorization",
            "The client can represent identity and permissions, but the server remains the trust boundary.",
            "React route guards improve UX; access tokens/cookies require secure lifecycle handling; backend authorization must validate every protected operation.",
            "Do not put secrets into VITE_ environment variables because client build values are public. Prefer secure cookie/token patterns appropriate to the backend. Render permission-aware UI from claims/capabilities, but expect the API to reject unauthorized requests.",
            "if (!permissions.canApproveOrder) return null;",
            ReactChoice(
                "Protect an operation",
                "What ultimately protects an approve-order API call?",
                "api",
                [new("api", "Server-side authorization"), new("guard", "A React route guard alone"), new("hidden", "Hiding the button")],
                "The browser is not a trust boundary.",
                "Separates UI authorization hints from server enforcement"),
            null,
            ReactDocs),
        new(
            "react-observability-errors",
            "Testing and production",
            42,
            "Instrument user-visible failures",
            "Frontend observability connects browser failures to user journeys, releases, and backend traces.",
            "Global and route error boundaries capture failures; telemetry should record release, route, correlation IDs, and useful context without leaking secrets or personal data.",
            "Log unexpected errors once at the correct boundary. Distinguish expected validation/business failures from crashes. Propagate correlation IDs when the backend supports them and measure web vitals or product-specific responsiveness where they matter.",
            "error boundary -> telemetry -> correlation -> actionable diagnosis",
            ReactChoice(
                "Capture a render crash",
                "Where should an unexpected route render failure be converted into user fallback UI and telemetry?",
                "boundary",
                [new("boundary", "A route/error boundary"), new("every", "A try/catch around every JSX expression"), new("ignore", "Nowhere")],
                "Boundaries localize failures and preserve usable parts of the app.",
                "Designs an observable failure boundary"),
            null,
            ReactDocs),
        new(
            "react-ssr-hydration",
            "Testing and production",
            43,
            "Understand SPA rendering versus SSR and hydration",
            "Enterprise applications should choose rendering strategy from product constraints rather than framework fashion.",
            "createRoot starts a client-rendered tree; hydrateRoot attaches React to server-rendered HTML.",
            "Internal authenticated apps often work well as SPAs. Public content may benefit from SSR/static rendering for startup or indexing. If HTML came from React on the server, hydrate it instead of replacing it with createRoot. Hydration mismatches are bugs, not harmless warnings.",
            "hydrateRoot(document.getElementById('root')!, <App />)",
            ReactChoice(
                "Attach to server HTML",
                "Which API should initialize React over HTML already rendered by React on the server?",
                "hydrate",
                [new("hydrate", "hydrateRoot"), new("create", "createRoot"), new("portal", "createPortal")],
                "Hydration reuses the server-generated DOM.",
                "Chooses the correct root lifecycle"),
            null,
            ReactDocs),
        new(
            "react-delivery-env-upgrades",
            "Testing and production",
            44,
            "Ship and upgrade safely",
            "A production React application is a compiled asset plus runtime API dependencies, browser constraints, observability, and operational policy.",
            "Vite environment variables are build-time client values; CI should type-check, test, build, and smoke-test; upgrades should be incremental and evidence-backed.",
            "Keep environment-specific secrets on the server. Validate required public configuration at startup. Record browser support requirements, pin/lock dependencies, review release notes, and use a dependency update cadence rather than letting the frontend fossilize.",
            "npm run typecheck && npm test && npm run build",
            ReactChoice(
                "Store a secret",
                "Where should a private API secret live?",
                "server",
                [new("server", "Server-side secret storage"), new("vite", "VITE_PRIVATE_SECRET"), new("bundle", "Hard-coded in the React bundle")],
                "Anything shipped to the browser is observable by the user.",
                "Separates public build configuration from secrets"),
            null,
            ViteReactDocs),
        new(
            "react-enterprise-capstone",
            "Testing and production",
            45,
            "Design an enterprise React feature end to end",
            "The final skill is making boundaries reinforce each other: route ownership, domain types, mutation semantics, test seams, accessibility, observability, and delivery.",
            "A production feature is more than a component: it has a URL/data boundary, domain behavior, reusable primitives, API contracts, failure states, tests, and operational evidence.",
            "Build an Order Approval workspace with nested routes, loader-owned order data, a fetcher/action mutation, permission-aware UI, an accessible confirmation flow, typed API functions, component/network/E2E tests, and telemetry for unexpected failures. Organize it under a feature boundary and document why each state lives where it does.",
            "route -> loader -> feature -> API boundary -> action/fetcher -> revalidation -> tests -> telemetry",
            ReactCode(
                "Sketch the feature boundary",
                "Export OrderApprovalPage. It must render OrderSummary and ApproveOrderForm using an order prop, and keep both components typed. This capstone code slice represents the page-to-feature composition boundary.",
                "type Order = { id: string; number: string; status: 'submitted' | 'approved' };\n\nfunction OrderSummary({ order }: { order: Order }) {\n  return <h2>{order.number}</h2>;\n}\n\nfunction ApproveOrderForm({ orderId }: { orderId: string }) {\n  return <form method='post'><button>Approve</button></form>;\n}\n\nexport function OrderApprovalPage() {\n  return null;\n}",
                "Give OrderApprovalPage an order prop and compose both child components from it.",
                "Composes route-level feature UI from typed boundaries",
                "Keeps reusable pieces focused"),
            null,
            ReactDocs)
    ]);
}
