static partial class Curriculum
{
    private static VersionStamp SQLiteDocs => new(
        "SQLite 3.53.4",
        "sqlite3 CLI · DB Browser for SQLite 3.13.1",
        "2026-09-26",
        "https://sqlite.org/docs.html");

    private static Exercise SqliteChoice(
        string title,
        string prompt,
        string correct,
        Choice[] choices,
        string hint,
        params string[] tests) =>
        new(
            ExerciseKind.MultipleChoice,
            title,
            prompt,
            ["Choose the best answer"],
            null,
            correct,
            choices,
            hint,
            tests);

    private static Exercise SqliteCode(
        string title,
        string prompt,
        string starter,
        string hint,
        params string[] tests) =>
        new(
            ExerciseKind.Code,
            title,
            prompt,
            [
                "Write SQLite SQL that satisfies the requested behavior",
                "The submission runs against a disposable, network-isolated SQLite database",
                "The evaluator verifies database state or query results after the SQL executes"
            ],
            starter,
            null,
            [],
            hint,
            tests);

    public static Lesson[] BuildSQLiteLessons() => NormalizeLessons(
    [
        new(
            "sqlite-what-it-is",
            "SQLite foundations",
            1,
            "Understand what SQLite is",
            "SQLite is an embedded relational database engine: the application reads and writes a database file through a library instead of talking to a separate database server.",
            "SQLite provides SQL tables, indexes, transactions, constraints, views, triggers, JSON functions, full-text extensions, and a mature storage engine without requiring a server process.",
            "A SQLite database is usually one portable file. That makes it excellent for desktop/mobile applications, local tools, caches, tests, edge workloads, and many small-to-medium services. It is not a drop-in replacement for a client/server database when many machines need high-write concurrency or centralized operational controls.",
            "application -> SQLite library -> app.db",
            SqliteChoice(
                "Choose the architecture",
                "What is the defining deployment difference between SQLite and a typical client/server database?",
                "embedded",
                [new("embedded", "SQLite runs in the application process and usually stores data in a local database file"), new("network", "SQLite requires a separate database server over TCP"), new("memory", "SQLite can only store data in memory")],
                "SQLite is an embedded database engine.",
                "Distinguishes embedded from client/server databases"),
            null,
            SQLiteDocs),
        new(
            "sqlite-cli-db-browser",
            "SQLite foundations",
            2,
            "Use the sqlite3 command-line shell",
            "The CLI makes database behavior explicit and gives you a scriptable way to inspect or change a database.",
            "The sqlite3 command-line shell can create/open databases, run SQL, inspect schema, change output modes, import/export data, and perform backups.",
            "Run sqlite3 followed by a file path to open that database. Dot commands such as .help, .databases, .tables, and .schema control or inspect the shell; SQL statements query and modify the database itself. Use the CLI for reproducible terminal work, scripts, diagnostics, and learning what the engine is actually doing.",
            "sqlite3 app.db\n.tables\n.schema\n.quit",
            SqliteChoice(
                "Pick the diagnostic tool",
                "Which SQLite tool is easiest to script in CI or a terminal when you need to inspect a database?",
                "cli",
                [new("cli", "The sqlite3 CLI"), new("browser", "A GUI-only workflow"), new("ssms", "SQL Server Management Studio")],
                "The sqlite3 shell is scriptable and works well in terminal workflows.",
                "Understands CLI and GUI responsibilities"),
            null,
            SQLiteDocs),
        new(
            "sqlite-db-browser",
            "SQLite foundations",
            3,
            "Inspect a database with DB Browser for SQLite",
            "A visual database tool is most useful when it reveals the same schema, rows, and SQL you could inspect from the command line.",
            "DB Browser for SQLite opens SQLite database files directly. Database Structure shows tables, columns, indexes, views, and triggers; Browse Data lets you inspect/edit rows; Execute SQL runs statements and shows result grids.",
            "Open the same .db file used by the CLI. Use Database Structure to verify the schema before editing data. Use Browse Data for quick row inspection, and Execute SQL for repeatable queries. GUI edits are staged until you choose Write Changes; Revert Changes abandons pending GUI edits. Keep a SQL migration or script as the durable source of truth for important schema changes instead of relying only on clicks.",
            "DB Browser workflow:\n1. Open Database -> app.db\n2. Database Structure -> inspect schema\n3. Browse Data -> inspect rows\n4. Execute SQL -> run a query\n5. Write Changes or Revert Changes",
            SqliteChoice(
                "Commit GUI edits deliberately",
                "After editing rows in DB Browser for SQLite, which action persists the pending GUI changes to the database file?",
                "write",
                [new("write", "Write Changes"), new("browse", "Switch to Browse Data"), new("close", "Only close the SQL editor tab")],
                "DB Browser separates pending edits from writing them to the database file.",
                "Uses DB Browser's change workflow deliberately"),
            null,
            SQLiteDocs),
        new(
            "sqlite-open-inspect",
            "SQLite foundations",
            4,
            "Create a database and inspect its schema",
            "Opening a file with sqlite3 creates a database when the file does not exist; dot commands inspect the shell and database rather than executing SQL.",
            ".databases shows attached databases, .tables lists tables and views, .schema prints DDL, .headers and .mode control result formatting, and .help documents shell commands.",
            "Dot commands are sqlite3 shell commands, not SQL statements, so they do not end with semicolons. SQL does. Learning the distinction prevents confusion when moving between the CLI, DB Browser, and application code.",
            "sqlite3 inventory.db\n.databases\n.tables\n.schema",
            SqliteCode(
                "Create the first table",
                "Create a products table with id INTEGER PRIMARY KEY and name TEXT NOT NULL.",
                "-- Create products with an integer primary key and required name\n",
                "Use CREATE TABLE with INTEGER PRIMARY KEY and NOT NULL.",
                "products table exists",
                "id is the integer primary key",
                "name is required"),
            null,
            SQLiteDocs),
        new(
            "sqlite-storage-types-affinity",
            "Schema design",
            5,
            "Understand storage classes and type affinity",
            "SQLite is dynamically typed, but declared column types still influence how values are converted and compared.",
            "SQLite values have storage classes NULL, INTEGER, REAL, TEXT, and BLOB. Column declarations map to type affinities such as INTEGER, TEXT, REAL, NUMERIC, or BLOB.",
            "A column declared INTEGER prefers integer storage but SQLite can often store another storage class unless STRICT tables or constraints prevent it. Do not confuse flexibility with having no data model: choose deliberate types and constraints, especially for identifiers, money, timestamps, and booleans.",
            "CREATE TABLE readings (\n  id INTEGER PRIMARY KEY,\n  label TEXT NOT NULL,\n  value REAL NOT NULL\n);",
            SqliteChoice(
                "Reason about affinity",
                "What does a declared SQLite column type primarily provide in a normal table?",
                "affinity",
                [new("affinity", "A type affinity that influences storage conversions and comparisons"), new("hard", "A universal hard runtime type restriction identical to every client/server engine"), new("none", "No behavior at all")],
                "Normal SQLite tables use type affinity; STRICT tables add stronger enforcement.",
                "Explains SQLite typing accurately"),
            null,
            SQLiteDocs),
        new(
            "sqlite-strict-tables",
            "Schema design",
            6,
            "Use STRICT tables when stronger typing helps",
            "STRICT tables keep SQLite's embedded model while rejecting values that cannot be losslessly converted to the declared type.",
            "A STRICT table limits declared types to SQLite's supported strict type names and performs stronger type checking on inserts and updates.",
            "STRICT is valuable when application data contracts should fail close to the database boundary. It does not replace CHECK, UNIQUE, FOREIGN KEY, or application validation; each constraint protects a different invariant.",
            "CREATE TABLE users (\n  id INTEGER PRIMARY KEY,\n  email TEXT NOT NULL\n) STRICT;",
            SqliteCode(
                "Create a STRICT table",
                "Create a STRICT users table with id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, and active INTEGER NOT NULL DEFAULT 1.",
                "-- Create a strongly constrained users table\n",
                "Put STRICT after the closing parenthesis and add the requested column constraints.",
                "users is STRICT",
                "email is required and unique",
                "active defaults to 1"),
            null,
            SQLiteDocs),
        new(
            "sqlite-constraints",
            "Schema design",
            7,
            "Protect invariants with constraints",
            "Constraints reject invalid database states even when a bug or another tool bypasses application-level validation.",
            "PRIMARY KEY identifies rows, NOT NULL rejects missing values, UNIQUE prevents duplicates, CHECK enforces expressions, and DEFAULT supplies omitted values.",
            "Put invariants in the database when they must always hold. A CHECK such as quantity >= 0 is stronger than hoping every caller remembers the same rule. Give constraints a clear purpose and test their failure behavior.",
            "CREATE TABLE inventory (\n  sku TEXT PRIMARY KEY,\n  quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),\n  location TEXT NOT NULL\n);",
            SqliteCode(
                "Constrain inventory",
                "Create inventory with sku TEXT PRIMARY KEY, quantity INTEGER NOT NULL DEFAULT 0 CHECK(quantity >= 0), and location TEXT NOT NULL.",
                "-- Define inventory so invalid negative stock cannot be stored\n",
                "Use a CHECK constraint on quantity.",
                "inventory schema is valid",
                "negative quantity is rejected",
                "default quantity is zero"),
            null,
            SQLiteDocs),
        new(
            "sqlite-crud",
            "Data manipulation",
            8,
            "Insert, update, and delete rows",
            "CRUD writes change persistent database state; WHERE clauses decide which rows are affected.",
            "INSERT adds rows, UPDATE changes matching rows, and DELETE removes matching rows. SQLite supports multi-row INSERT and RETURNING for write statements that need to return affected values.",
            "Before running UPDATE or DELETE, first run the equivalent SELECT with the same WHERE clause when the scope is not obvious. In application code, parameterize values rather than concatenating SQL strings.",
            "INSERT INTO users (email) VALUES ('ada@example.test');\nUPDATE users SET active = 0 WHERE email = 'ada@example.test';\nDELETE FROM users WHERE id = 42;",
            SqliteCode(
                "Perform CRUD safely",
                "Insert Ada and Grace into the prepared users table, deactivate Grace, and delete the row whose email is temp@example.test.",
                "-- users(id, email, active) already exists\n",
                "Use INSERT, a targeted UPDATE, and a targeted DELETE.",
                "Ada and Grace exist",
                "Grace is inactive",
                "temporary user is removed"),
            null,
            SQLiteDocs),
        new(
            "sqlite-select-filter-sort",
            "Querying data",
            9,
            "Select, filter, sort, and limit results",
            "A useful query states exactly which rows and columns are needed.",
            "SELECT chooses expressions, WHERE filters rows, ORDER BY defines result order, and LIMIT bounds result count.",
            "Avoid SELECT * in durable application queries when the contract matters. Explicit columns make schema dependencies visible and reduce unnecessary data transfer. Ordering is not guaranteed unless ORDER BY says what order you need.",
            "SELECT id, email\nFROM users\nWHERE active = 1\nORDER BY email\nLIMIT 20;",
            SqliteCode(
                "Query active users",
                "Return email and created_at for active users, newest first, limited to 5 rows.",
                "-- users(email, active, created_at) is preloaded\nSELECT\n",
                "Filter active = 1, order created_at descending, and LIMIT 5.",
                "query returns the requested columns",
                "only active users are returned",
                "results are newest-first and limited"),
            null,
            SQLiteDocs),
        new(
            "sqlite-null-expressions-functions",
            "Querying data",
            10,
            "Handle NULL and expressions deliberately",
            "NULL means missing or unknown; it is not equal to anything, including another NULL.",
            "Use IS NULL and IS NOT NULL for null checks. COALESCE supplies a fallback, CASE expresses branching, and built-in scalar functions transform values.",
            "SQL uses three-valued logic, so comparisons involving NULL can evaluate to unknown and disappear from WHERE results. Model optional data intentionally and avoid magic sentinel values such as empty strings when absence is what you mean.",
            "SELECT name, COALESCE(phone, 'No phone') AS phone_display\nFROM customers\nWHERE deleted_at IS NULL;",
            SqliteChoice(
                "Check missing data",
                "Which predicate correctly finds rows where deleted_at has no value?",
                "is-null",
                [new("is-null", "deleted_at IS NULL"), new("equals", "deleted_at = NULL"), new("empty", "deleted_at = ''")],
                "NULL uses IS NULL / IS NOT NULL.",
                "Handles SQL NULL semantics"),
            null,
            SQLiteDocs),
        new(
            "sqlite-joins",
            "Relational queries",
            11,
            "Join related tables",
            "Joins reconstruct related data using keys instead of duplicating whole records.",
            "INNER JOIN returns matching rows; LEFT JOIN preserves every row from the left side and supplies NULLs when no right-side match exists.",
            "Join on columns that express a real relationship, usually a foreign key to a primary/unique key. Qualify ambiguous column names and select only what the consumer needs.",
            "SELECT o.id, c.name, o.total\nFROM orders AS o\nJOIN customers AS c ON c.id = o.customer_id\nORDER BY o.id;",
            SqliteCode(
                "Join orders to customers",
                "Return order id, customer name, and total for every order using the prepared customers and orders tables.",
                "-- customers(id, name); orders(id, customer_id, total)\nSELECT\n",
                "Join orders.customer_id to customers.id.",
                "query returns each order",
                "customer names come from customers",
                "totals come from orders"),
            null,
            SQLiteDocs),
        new(
            "sqlite-aggregates-group-having",
            "Relational queries",
            12,
            "Aggregate data with GROUP BY and HAVING",
            "Aggregates collapse rows into summaries; GROUP BY defines the groups and HAVING filters those groups.",
            "COUNT, SUM, AVG, MIN, and MAX summarize data. WHERE filters source rows before grouping; HAVING filters aggregate groups afterward.",
            "Group by the dimensions you actually want in the result. Be cautious about selecting non-aggregated columns that are not part of the grouping contract, even where SQLite permits convenient extensions.",
            "SELECT customer_id, COUNT(*) AS order_count, SUM(total) AS spend\nFROM orders\nGROUP BY customer_id\nHAVING COUNT(*) >= 2;",
            SqliteCode(
                "Summarize order totals",
                "Return customer_id, order_count, and total_spend for customers with at least 2 orders.",
                "-- orders(customer_id, total) is preloaded\nSELECT\n",
                "GROUP BY customer_id and use HAVING for the aggregate threshold.",
                "groups by customer",
                "counts and sums orders",
                "filters to at least two orders"),
            null,
            SQLiteDocs),
        new(
            "sqlite-ctes-subqueries",
            "Relational queries",
            13,
            "Use subqueries and common table expressions",
            "Break a complex query into named relational steps instead of forcing everything into one unreadable expression.",
            "A subquery nests a query inside another statement. WITH defines a common table expression (CTE) that can make transformations easier to read and reuse within one statement.",
            "Use CTEs to make intent obvious, not automatically for every query. SQLite can also use WITH RECURSIVE for hierarchical or iterative queries.",
            "WITH customer_spend AS (\n  SELECT customer_id, SUM(total) AS total_spend\n  FROM orders\n  GROUP BY customer_id\n)\nSELECT * FROM customer_spend WHERE total_spend >= 1000;",
            SqliteCode(
                "Build a summary CTE",
                "Create a CTE named active_counts that counts active users by role, then return only roles with a count of at least 2.",
                "-- users(role, active) is preloaded\nWITH\n",
                "Filter active rows inside the CTE, group by role, then filter the CTE result.",
                "uses active_counts CTE",
                "counts active users per role",
                "returns groups of at least two"),
            null,
            SQLiteDocs),
        new(
            "sqlite-json-date-time",
            "Relational queries",
            14,
            "Work with JSON and date/time values",
            "SQLite stores application-friendly text values but also provides functions for querying JSON and manipulating dates and times.",
            "JSON functions such as json_extract and ->/->> read structured JSON values. Date/time functions such as datetime, date, unixepoch, and strftime operate on supported time representations.",
            "Prefer ordinary relational columns for fields you consistently filter, join, constrain, or index. JSON is useful for genuinely flexible payloads, not as an excuse to avoid schema design. Store timestamps consistently, commonly as ISO-8601 UTC text or Unix time.",
            "SELECT json_extract(metadata, '$.source') AS source,\n       datetime(created_at) AS created_utc\nFROM events;",
            SqliteChoice(
                "Choose relational vs JSON storage",
                "A field is required, frequently filtered, and participates in joins. Where should it usually live?",
                "column",
                [new("column", "In a normal constrained column"), new("json", "Only inside an opaque JSON blob"), new("filename", "Encoded in the database filename")],
                "Stable relational data belongs in normal columns.",
                "Chooses schema based on query and integrity needs"),
            null,
            SQLiteDocs),
        new(
            "sqlite-transactions",
            "Integrity and transactions",
            15,
            "Make multi-step writes atomic with transactions",
            "A transaction makes a group of statements succeed or fail as one database change.",
            "BEGIN starts a transaction, COMMIT makes it durable, and ROLLBACK abandons the uncommitted changes. SQLite transactions provide ACID guarantees within the engine's locking model.",
            "Transactions should match a business invariant. If an order insert and inventory decrement must agree, put them in one transaction. Keep write transactions short so other writers are not blocked longer than necessary.",
            "BEGIN;\nUPDATE inventory SET quantity = quantity - 1 WHERE sku = 'A-100' AND quantity > 0;\nINSERT INTO orders (sku, quantity) VALUES ('A-100', 1);\nCOMMIT;",
            SqliteCode(
                "Make a transfer atomic",
                "In one transaction, subtract 25 from account 1 and add 25 to account 2.",
                "-- accounts(id, balance) is preloaded\n",
                "Use BEGIN, two targeted UPDATE statements, and COMMIT.",
                "transaction boundaries exist",
                "account 1 loses 25",
                "account 2 gains 25"),
            null,
            SQLiteDocs),
        new(
            "sqlite-foreign-keys",
            "Integrity and transactions",
            16,
            "Enforce relationships with foreign keys",
            "Foreign keys prevent child rows from referring to nonexistent parent rows when foreign-key enforcement is enabled.",
            "REFERENCES defines the relationship. ON DELETE and ON UPDATE actions describe what happens when the referenced key changes. PRAGMA foreign_keys = ON enables enforcement for a connection where it is not already enabled by the host environment.",
            "Always know whether your application's SQLite connection enables foreign keys. Choose CASCADE, RESTRICT, SET NULL, or NO ACTION based on domain ownership rather than convenience.",
            "PRAGMA foreign_keys = ON;\nCREATE TABLE orders (\n  id INTEGER PRIMARY KEY,\n  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE RESTRICT\n);",
            SqliteCode(
                "Protect order ownership",
                "Enable foreign keys and create orders with customer_id referencing customers(id) using ON DELETE RESTRICT.",
                "-- customers(id INTEGER PRIMARY KEY) already exists\n",
                "Enable PRAGMA foreign_keys and add a REFERENCES clause.",
                "foreign keys are enabled",
                "orders references customers",
                "missing customers are rejected"),
            null,
            SQLiteDocs),
        new(
            "sqlite-indexes",
            "Performance",
            17,
            "Create indexes for actual query patterns",
            "An index trades storage and write cost for faster lookups and ordered access.",
            "CREATE INDEX builds an ordered structure over one or more expressions/columns. UNIQUE indexes also enforce uniqueness. Column order matters in multi-column indexes.",
            "Index columns because a real query filters, joins, or orders on them—not because the column looks important. Every extra index has write and maintenance cost. Prefer a small set of indexes supported by query plans.",
            "CREATE INDEX idx_orders_customer_created\nON orders(customer_id, created_at DESC);",
            SqliteCode(
                "Index a dashboard query",
                "Create idx_orders_customer_created on orders(customer_id, created_at DESC).",
                "-- Add the composite index used by customer history queries\n",
                "Use CREATE INDEX with customer_id first and created_at DESC second.",
                "index exists",
                "index columns are ordered correctly",
                "index is not unique"),
            null,
            SQLiteDocs),
        new(
            "sqlite-query-planner",
            "Performance",
            18,
            "Read EXPLAIN QUERY PLAN",
            "Performance work starts by asking the query planner what access path it chose.",
            "EXPLAIN QUERY PLAN describes table scans, index searches, join loops, and temporary structures used by a statement.",
            "A full table scan is not automatically bad—small tables are cheap to scan. Look for expensive scans on large selective queries, missing useful indexes, unnecessary sorts, and query shapes that prevent index use.",
            "EXPLAIN QUERY PLAN\nSELECT id, total\nFROM orders\nWHERE customer_id = 42\nORDER BY created_at DESC;",
            SqliteChoice(
                "Interpret a plan",
                "What should you do after seeing a full table scan in EXPLAIN QUERY PLAN?",
                "context",
                [new("context", "Check table size, selectivity, and the query pattern before deciding an index is needed"), new("always", "Always add an index immediately"), new("ignore", "Ignore query plans entirely")],
                "A scan is evidence to interpret, not automatically a bug.",
                "Uses plans instead of index folklore"),
            null,
            SQLiteDocs),
        new(
            "sqlite-rowid-primary-key",
            "SQLite-specific behavior",
            19,
            "Understand rowid and INTEGER PRIMARY KEY",
            "Most ordinary SQLite tables have a hidden 64-bit rowid; an INTEGER PRIMARY KEY column aliases that rowid.",
            "INTEGER PRIMARY KEY gets SQLite's rowid behavior. AUTOINCREMENT changes rowid reuse rules and adds overhead; it is not required merely to generate increasing integer keys.",
            "Use AUTOINCREMENT only when you specifically require a previously used rowid never to be reused. For many application tables, INTEGER PRIMARY KEY provides the desired generated identifier behavior without it.",
            "CREATE TABLE notes (\n  id INTEGER PRIMARY KEY,\n  body TEXT NOT NULL\n);",
            SqliteChoice(
                "Choose an integer key",
                "You need a generated integer identifier but do not care if deleted historical values are ever reused. What is the usual SQLite choice?",
                "ipk",
                [new("ipk", "INTEGER PRIMARY KEY"), new("auto", "AUTOINCREMENT is mandatory"), new("text", "A TEXT column with no constraint")],
                "INTEGER PRIMARY KEY already aliases the rowid and generates keys.",
                "Avoids unnecessary AUTOINCREMENT"),
            null,
            SQLiteDocs),
        new(
            "sqlite-schema-migrations",
            "SQLite-specific behavior",
            20,
            "Evolve schema with deliberate migrations",
            "Schema changes are production data changes, not just edits to CREATE TABLE source.",
            "ALTER TABLE supports common rename/add/drop operations, with SQLite version-specific capabilities. More complex transformations use a create-copy-drop-rename migration inside a transaction.",
            "Treat migrations as ordered, reviewed artifacts. Back up important databases, test migrations against representative data, preserve constraints/indexes/triggers, and verify both schema and data after the change.",
            "BEGIN;\nALTER TABLE users ADD COLUMN display_name TEXT;\nCOMMIT;",
            SqliteCode(
                "Add a constrained column safely",
                "Add a nullable display_name TEXT column to the prepared users table without rebuilding it.",
                "-- users already exists\n",
                "Use ALTER TABLE users ADD COLUMN.",
                "display_name exists",
                "existing rows remain",
                "column is TEXT"),
            null,
            SQLiteDocs),
        new(
            "sqlite-views-triggers",
            "SQLite-specific behavior",
            21,
            "Use views and triggers sparingly",
            "Views package reusable queries; triggers execute database-side actions when rows change.",
            "CREATE VIEW exposes a named SELECT. CREATE TRIGGER can run SQL BEFORE, AFTER, or INSTEAD OF supported changes.",
            "Views can simplify read contracts. Triggers can protect or automate invariants but also hide write behavior from application code. Keep triggers small, documented, and tested so a write's side effects remain understandable.",
            "CREATE VIEW active_users AS\nSELECT id, email FROM users WHERE active = 1;",
            SqliteCode(
                "Create a read view",
                "Create active_users exposing id and email only for rows where active = 1.",
                "-- users(id, email, active) is preloaded\n",
                "Use CREATE VIEW ... AS SELECT.",
                "active_users view exists",
                "view exposes id and email",
                "inactive users are excluded"),
            null,
            SQLiteDocs),
        new(
            "sqlite-wal-locking",
            "Concurrency and reliability",
            22,
            "Understand WAL, locking, and busy handling",
            "SQLite supports many readers but serializes writes; journal mode changes how readers and writers interact.",
            "WAL mode writes committed changes to a write-ahead log and commonly allows readers to continue while a writer is active. PRAGMA busy_timeout can wait briefly for a lock instead of failing immediately.",
            "WAL improves many concurrent application workloads but it does not turn SQLite into a multi-writer server database. Keep write transactions short, configure busy handling intentionally, and test the real deployment filesystem/concurrency pattern.",
            "PRAGMA journal_mode = WAL;\nPRAGMA busy_timeout = 5000;",
            SqliteChoice(
                "Reason about concurrency",
                "What limitation remains true when WAL mode is enabled?",
                "writer",
                [new("writer", "SQLite still serializes database writers"), new("reader", "Only one reader can exist"), new("network", "Every query requires a database server")],
                "WAL improves reader/writer overlap, but writes are still serialized.",
                "Understands SQLite concurrency boundaries"),
            null,
            SQLiteDocs),
        new(
            "sqlite-parameters",
            "Application integration",
            23,
            "Parameterize SQL instead of concatenating values",
            "SQL text and untrusted data are different things; parameters preserve that boundary.",
            "SQLite supports positional and named parameters such as ?, ?1, :email, @email, and $email through host-language APIs.",
            "Bind values through your language's SQLite driver. Parameters prevent data from changing SQL structure, handle quoting correctly, and can help statement reuse. Parameters cannot stand in for arbitrary identifiers such as a column name; allow-list those separately.",
            "SELECT id, email FROM users WHERE email = :email;",
            SqliteChoice(
                "Protect query structure",
                "How should an application pass a user-supplied email into a SQLite WHERE clause?",
                "parameter",
                [new("parameter", "Bind it as a SQL parameter"), new("concat", "Concatenate it directly into the SQL string"), new("escape-html", "HTML-encode it and concatenate")],
                "Bind values with the SQLite driver.",
                "Separates SQL structure from data"),
            null,
            SQLiteDocs),
        new(
            "sqlite-backup-export-import",
            "Operations",
            24,
            "Back up, dump, import, and copy databases",
            "A database file is convenient, but safe backup still needs SQLite-aware operations when the database may be active.",
            "The sqlite3 CLI provides .backup and .dump; VACUUM INTO creates a compact database copy; .import can load delimited data after you deliberately define the destination schema.",
            "Do not blindly copy an actively written database together with an uncertain journal state. Use supported backup mechanisms. Test restore procedures, because a backup that has never been restored is only an assumption.",
            "sqlite3 app.db ".backup 'app-backup.db'"\nsqlite3 app.db ".dump" > app.sql",
            SqliteChoice(
                "Choose a live backup approach",
                "Which approach is designed to create a consistent SQLite backup while the database may be in use?",
                "backup",
                [new("backup", "Use SQLite's backup mechanism such as .backup / the backup API"), new("copy", "Blindly copy arbitrary files mid-write"), new("screenshot", "Export screenshots from a GUI")],
                "Use a SQLite-aware backup mechanism.",
                "Treats backup as a consistency operation"),
            null,
            SQLiteDocs),
        new(
            "sqlite-integrity-maintenance",
            "Operations",
            25,
            "Check integrity and maintain statistics",
            "SQLite exposes diagnostics and maintenance commands so you can verify the file and help the planner make informed choices.",
            "PRAGMA integrity_check validates database structure. ANALYZE records planner statistics. PRAGMA optimize performs recommended targeted optimization work. VACUUM rebuilds the database file and can reclaim free space.",
            "Do not run maintenance commands by superstition. Understand the cost and reason: integrity checks verify structure; optimizer statistics support planning; VACUUM rewrites the file and can require substantial temporary disk space.",
            "PRAGMA integrity_check;\nPRAGMA optimize;",
            SqliteChoice(
                "Check database structure",
                "Which command asks SQLite to verify database structural integrity?",
                "integrity",
                [new("integrity", "PRAGMA integrity_check"), new("vacuum", "VACUUM only"), new("explain", "EXPLAIN QUERY PLAN")],
                "PRAGMA integrity_check performs database integrity diagnostics.",
                "Chooses the right maintenance operation"),
            null,
            SQLiteDocs),
        new(
            "sqlite-capstone",
            "Capstone",
            26,
            "Build a production-minded local database",
            "A useful SQLite design combines relational modeling, constraints, queries, transactions, indexes, and operational checks.",
            "The capstone models a small issue tracker with projects, users, issues, and comments. The database should reject broken relationships, support dashboard queries, and survive realistic write workflows.",
            "Create projects, users, issues, and comments with primary keys, required fields, foreign keys, status constraints, and timestamps. Add an index that supports listing a project's open issues newest-first. Add an open_issue_summary view. Use a transaction to create an issue and its first comment. The evaluator verifies schema, constraints, index, view, data, and integrity.",
            "PRAGMA foreign_keys = ON;\n\n-- Build the issue-tracker schema and seed one valid issue workflow.",
            SqliteCode(
                "Build the issue-tracker database",
                "Create the requested projects, users, issues, and comments schema; add idx_issues_project_status_created; create open_issue_summary; and insert a project, user, open issue, and first comment in a transaction.",
                "PRAGMA foreign_keys = ON;\n\n-- Create the schema, index, view, and one transactional workflow\n",
                "Start with parent tables, then child tables. Add foreign keys and a CHECK for issue status before creating the index and view.",
                "schema and constraints are correct",
                "dashboard index and view exist",
                "transactional seed data passes integrity checks"),
            null,
            SQLiteDocs)
    ]);
}
