static partial class Curriculum
{
    private static VersionStamp WebBasicsDocs => new(
        "Web Platform 2026",
        "HTML · CSS · JavaScript · TypeScript · HTTP",
        "2026-09-26",
        "https://developer.mozilla.org/en-US/docs/Learn_web_development");

    public static Lesson[] BuildWebBasicsLessons() => NormalizeLessons(
    [
        new(
            "web-basics-browser-server",
            "How the web works",
            1,
            "How a web application fits together",
            "Understand the browser/server model before choosing a frontend framework.",
            "The browser renders HTML/CSS, executes JavaScript, sends HTTP requests, and receives resources or data from servers.",
            "When you open a web application, the browser resolves an address, makes requests, receives files/data, and runs the client-side code. A backend API owns trusted operations and shared data; frontend code runs on the user's machine and must be treated accordingly.",
            "browser -> HTTP request -> server/API -> response -> browser",
            ReactChoice(
                "Place the responsibility",
                "Where does client-side JavaScript normally execute?",
                "browser",
                [new("browser", "In the user's browser"), new("database", "Inside the database"), new("switch", "Inside an Ethernet switch")],
                "Client-side JavaScript is downloaded and executed by the browser.",
                "Understands the browser/server boundary"),
            null,
            WebBasicsDocs),
        new(
            "web-basics-html",
            "HTML",
            2,
            "Structure pages with semantic HTML",
            "HTML describes what content and controls mean.",
            "Headings, navigation, main content, sections, tables, forms, labels, inputs, buttons, and links provide the document structure browsers and assistive technology understand.",
            "Use buttons for actions, links for navigation, labels for form controls, and table markup for tabular data. Start with the correct element before reaching for CSS or JavaScript.",
            "<main><h1>Users</h1><button type='button'>Add user</button></main>",
            ReactChoice(
                "Choose a semantic element",
                "Which element should trigger an in-page Save action?",
                "button",
                [new("button", "button"), new("anchor", "a without href"), new("div", "div with a click handler")],
                "Buttons represent actions.",
                "Uses semantic HTML controls"),
            null,
            WebBasicsDocs),
        new(
            "web-basics-forms",
            "HTML",
            3,
            "Build accessible forms",
            "Forms collect structured user input and already provide useful browser behavior.",
            "label, input, select, textarea, button, fieldset, input types, required, and native validation cover many common form needs.",
            "Associate visible labels with controls. Use meaningful input types such as email and number. A submit button submits the form; JavaScript can intercept the submit event when building a client application.",
            "<label for='email'>Email</label><input id='email' name='email' type='email' required>",
            ReactChoice(
                "Name a form control",
                "What is the strongest default way to give an email field an accessible name?",
                "label",
                [new("label", "Associate a visible label"), new("placeholder", "Placeholder text only"), new("position", "Rely on visual position")],
                "Visible labels remain available while the user types and work well with assistive technology.",
                "Builds accessible form markup"),
            null,
            WebBasicsDocs),
        new(
            "web-basics-css-box-layout",
            "CSS",
            4,
            "Understand the box model and layout",
            "CSS controls presentation; layout becomes much easier once the box model, Flexbox, and Grid are familiar.",
            "Content, padding, border, and margin form the box model. Flexbox lays items out primarily along one axis; Grid handles rows and columns.",
            "Learn display, width/max-width, margin, padding, border, gap, flex/grid, alignment, and overflow before memorizing framework utilities. Utility CSS libraries such as Tailwind are convenient names for CSS behavior, not a replacement for understanding it.",
            ".shell { display: grid; grid-template-columns: 16rem 1fr; gap: 1rem; }",
            ReactChoice(
                "Choose a layout",
                "Which CSS system naturally fits a fixed sidebar beside a flexible main column?",
                "grid",
                [new("grid", "CSS Grid"), new("font", "font-weight"), new("shadow", "box-shadow")],
                "Grid directly models columns.",
                "Understands common CSS layout primitives"),
            null,
            WebBasicsDocs),
        new(
            "web-basics-css-responsive",
            "CSS",
            5,
            "Build responsive interfaces",
            "Web layouts must adapt instead of assuming one screen size.",
            "Relative sizing, min/max widths, wrapping, media queries, and fluid layouts let the same interface work across viewports.",
            "Design from available space rather than named devices. Let content wrap, avoid unnecessary fixed widths, and use breakpoints when the layout itself needs to change.",
            "@media (min-width: 768px) { .shell { grid-template-columns: 16rem 1fr; } }",
            ReactChoice(
                "Fix a narrow layout",
                "What should usually happen to a two-column admin layout when the viewport becomes too narrow?",
                "adapt",
                [new("adapt", "Adapt or stack the layout"), new("overflow", "Require horizontal scrolling for the entire page"), new("shrink", "Shrink all text until it fits")],
                "Responsive layouts adapt to available space.",
                "Applies responsive layout thinking"),
            null,
            WebBasicsDocs),
        new(
            "web-basics-javascript",
            "JavaScript",
            6,
            "Use modern JavaScript for application logic",
            "Frontend frameworks are built on JavaScript, so arrays, objects, functions, modules, and async work are foundational.",
            "const/let, objects, arrays, destructuring, spread, map, filter, find, functions, import/export, Promise, and async/await appear constantly in frontend work.",
            "Prefer creating new arrays/objects when transforming data rather than unexpectedly mutating values another part of the UI may be using. Learn to read small callback functions and chained array operations.",
            "const activeNames = users.filter(user => user.active).map(user => user.name)",
            ReactChoice(
                "Filter an array",
                "Which method returns a new array containing only matching entries?",
                "filter",
                [new("filter", "filter"), new("push", "push"), new("await", "await")],
                "filter selects matching elements into a new array.",
                "Uses common JavaScript collection operations"),
            null,
            WebBasicsDocs),
        new(
            "web-basics-typescript",
            "JavaScript and TypeScript",
            7,
            "Understand what TypeScript adds to JavaScript",
            "TypeScript is JavaScript with a compile-time type system. Browsers do not run TypeScript directly; the toolchain removes the type syntax and emits JavaScript.",
            "Types catch many mistakes before the code reaches a browser, improve autocomplete and refactoring, and document the shape of application data. They do not validate untrusted runtime data by themselves. Object types describe records, unions constrain known values, function signatures describe inputs and outputs, and unknown is safer than any when a value has not been checked.",
            "Type the data crossing important boundaries first: component props, API request/response shapes, form values, and function parameters. The benefit is earlier feedback when code passes the wrong shape or uses a value incorrectly. Keep runtime validation where data enters from users, storage, or APIs because TypeScript's checks disappear at runtime.",
            "type UserStatus = 'active' | 'disabled';\ntype User = { id: string; name: string; status: UserStatus };",
            ReactChoice(
                "Constrain a status",
                "Which type prevents unrelated strings from being accepted as UserStatus?",
                "union",
                [new("union", "'active' | 'disabled'"), new("string", "string"), new("any", "any")],
                "A string-literal union represents the known allowed values.",
                "Uses TypeScript for useful application contracts"),
            null,
            WebBasicsDocs),
        new(
            "web-basics-http-json",
            "HTTP and APIs",
            8,
            "Understand HTTP and JSON APIs",
            "Most frontend applications communicate with backend systems through HTTP.",
            "GET reads, POST creates or submits work, PUT/PATCH update, DELETE removes, status codes describe outcomes, headers carry metadata, and JSON commonly represents data.",
            "A frontend API call is asynchronous. Check whether a response succeeded, understand common 2xx/4xx/5xx categories, and keep in mind that hiding an operation in the browser does not secure the backend.",
            "GET /api/users -> 200 [{ \"id\": \"1\", \"name\": \"Ada\" }]",
            ReactChoice(
                "Recognize a server failure",
                "Which status-code family represents server errors?",
                "5xx",
                [new("5xx", "5xx"), new("2xx", "2xx"), new("3xx", "3xx")],
                "5xx responses indicate server-side failure.",
                "Understands basic HTTP semantics"),
            null,
            WebBasicsDocs),
        new(
            "web-basics-fetch-async",
            "HTTP and APIs",
            9,
            "Read JSON with fetch and async/await",
            "fetch is the browser's basic HTTP API and returns Promises.",
            "Await the response, check response.ok, then parse JSON. Catch or surface failures where the application can present meaningful feedback.",
            "Keep the network call in a function rather than scattering fetch throughout markup. Separating data access from rendering makes failures easier to handle and lets the calling code decide when the request should run.",
            "const response = await fetch('/api/users'); if (!response.ok) throw new Error('Request failed'); const users = await response.json();",
            ReactChoice(
                "Check a response",
                "What should happen before treating response.json() as successful API data?",
                "ok",
                [new("ok", "Check response.ok or status"), new("ignore", "Ignore the HTTP status"), new("reload", "Reload the page every time")],
                "fetch resolves even for many HTTP error responses, so inspect the response.",
                "Uses the browser fetch API safely"),
            null,
            WebBasicsDocs),
        new(
            "web-basics-devtools",
            "Debugging",
            10,
            "Debug with browser DevTools",
            "The browser already provides the most important tools for understanding frontend failures.",
            "Elements shows DOM/CSS, Console shows JavaScript errors/logs, Network shows requests and responses, Sources supports debugging, and Application/Storage shows browser persistence.",
            "When an API call fails, inspect Network. When layout looks wrong, inspect Elements and computed CSS. When code throws, start with the Console stack trace. Debug from evidence instead of changing random code.",
            "Console -> runtime error\nNetwork -> requests\nElements -> DOM and CSS",
            ReactChoice(
                "Inspect a 500 response",
                "Which DevTools panel should you open first when an API request returns HTTP 500?",
                "network",
                [new("network", "Network"), new("elements", "Elements"), new("fonts", "Fonts")],
                "Network shows the request, response status, headers, and body.",
                "Uses browser debugging evidence"),
            null,
            WebBasicsDocs),
        new(
            "web-basics-accessibility",
            "Web quality",
            11,
            "Build for keyboard and assistive technology",
            "Accessibility starts with normal web semantics rather than a special framework.",
            "Semantic controls, headings, form labels, keyboard access, visible focus, alternative text, and sufficient information outside color cover many foundational requirements.",
            "Try the page using only the keyboard. Interactive controls should be reachable and understandable. Prefer native browser controls because they already include behavior custom div-based controls would have to recreate.",
            "<button type='button'>Open menu</button>",
            ReactChoice(
                "Choose a custom control strategy",
                "What should you prefer before building a clickable div from scratch?",
                "native",
                [new("native", "A native semantic element"), new("div", "A div plus several ARIA attributes"), new("mouse", "Mouse-only interaction")],
                "Native elements provide semantics and keyboard behavior by default.",
                "Applies basic accessibility principles"),
            null,
            WebBasicsDocs),
        new(
            "web-basics-capstone",
            "Web quality",
            12,
            "Trace a small web feature end to end",
            "Bring structure, styling, browser logic, and HTTP together in one small feature.",
            "A small web feature combines semantic HTML, responsive CSS, JavaScript data handling, an asynchronous API-shaped call, and debugging.",
            "Sketch a Users page with a heading, Add User form, responsive list/table, and a loadUsers function. Keep it framework-neutral. Be able to explain what runs in the browser, what belongs on the server, how JSON moves across HTTP, and how browser DevTools would expose a failed request.",
            "HTML structure + CSS layout + JS behavior + HTTP data -> functional web page",
            ReactChoice(
                "Choose the right abstraction",
                "Which tool is responsible for organizing browser UI into reusable components when building the dashboard version of this feature?",
                "react",
                [new("react", "React"), new("http", "HTTP"), new("css", "CSS alone")],
                "React organizes UI into reusable components; HTTP moves data and CSS controls presentation.",
                "Connects web fundamentals to component-based UI"),
            null,
            WebBasicsDocs)
    ]);
}
