import { useEffect, useMemo, useState } from 'react'
import Editor from '@monaco-editor/react'
import { Check, MessageCircle, Save, Send, Sparkles } from 'lucide-react'
import { keycloak } from './keycloak'

type Course = { id: string; title: string; languageId: string; modules: { title: string; lessons: { slug: string; title: string }[] }[] }
type View = 'dashboard' | 'projects' | 'community' | 'coach'
type Dashboard = { completedLessons: number; totalLessons: number; currentStreakDays: number; projectCount: number; dueReviewLessonSlugs: string[]; recentCompletions: { lessonSlug: string; completedAt: string }[] }
type Review = { lessonSlug: string; title: string; dueAt: string; intervalDays: number }
type Assessment = { courseId: string; moduleId: string; title: string; questions: { id: string; prompt: string; choices: string[] }[] }
type AssessmentResult = { passed: boolean; correctAnswers: number; totalQuestions: number; recommendedReviewLessonSlugs: string[]; feedback: string }
type Template = { id: string; title: string; description: string; language: string; files: { path: string; content: string }[] }
type Project = { id: string; templateId: string; title: string; updatedAt: string; files: { path: string; content: string }[] }
type CommunityPost = { id: string; title: string; body: string; needsMentor: boolean; createdAt: string; replies: { id: string; body: string; isMentor: boolean; createdAt: string }[] }

const baseUrl = import.meta.env.VITE_API_BASE_URL ?? ''
const headers = (): Record<string, string> => keycloak?.token ? { 'content-type': 'application/json', Authorization: `Bearer ${keycloak.token}` } : { 'content-type': 'application/json', 'X-Learner-Id': localStorage.getItem('pathway-learner-id') ?? 'guest' }
const fallbackTemplates: Template[] = [
  { id: 'python-learning-api', title: 'Learning API', description: 'Build a typed FastAPI service with tests.', language: 'python', files: [{ path: 'src/learning_service/main.py', content: 'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/health")\ndef health() -> dict[str, str]:\n    return {"status": "ok"}\n' }, { path: 'tests/test_health.py', content: 'def test_health() -> None:\n    assert True\n' }] },
  { id: 'python-event-pipeline', title: 'Event pipeline', description: 'Design idempotent processing with retries and operational signals.', language: 'python', files: [{ path: 'src/pipeline/consumer.py', content: 'def process_event(event_id: str, payload: dict[str, object]) -> None:\n    raise NotImplementedError\n' }, { path: 'README.md', content: '# Event pipeline\n\nDocument delivery semantics and recovery.\n' }] },
  { id: 'csharp-learning-api', title: 'Learning API', description: 'Build a modern .NET API with a clear contract.', language: 'csharp', files: [{ path: 'Program.cs', content: 'var builder = WebApplication.CreateBuilder(args);\nvar app = builder.Build();\n\napp.MapGet("/health", () => Results.Ok(new { status = "ok" }));\napp.Run();\n' }, { path: 'README.md', content: '# Learning API\n\nDescribe the contract and delivery plan.\n' }] },
  { id: 'csharp-order-api', title: 'Order API', description: 'Ship a sealed, testable .NET API with modern contracts.', language: 'csharp', files: [{ path: 'Program.cs', content: 'var builder = WebApplication.CreateBuilder(args);\nvar app = builder.Build();\n\napp.MapGet("/health", () => Results.Ok(new { status = "ok" }));\napp.Run();\n' }, { path: 'README.md', content: '# Order API\n\nDescribe validation, tests, telemetry, and rollback.\n' }] },
]

export function ExperienceHub({ view, course, completed, onSelectLesson, onNotice }: { view: View; course: Course; completed: string[]; onSelectLesson: (slug: string) => void; onNotice: (message: string) => void }) {
  if (view === 'dashboard') return <DashboardPanel course={course} completed={completed} onSelectLesson={onSelectLesson} />
  if (view === 'projects') return <ProjectStudio course={course} onNotice={onNotice} />
  if (view === 'community') return <CommunityPanel course={course} onNotice={onNotice} />
  return <CoachPanel course={course} onSelectLesson={onSelectLesson} />
}

function DashboardPanel({ course, completed, onSelectLesson }: { course: Course; completed: string[]; onSelectLesson: (slug: string) => void }) {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null)
  const [reviews, setReviews] = useState<Review[]>([])
  useEffect(() => { void Promise.all([fetch(`${baseUrl}/api/experience/dashboard`, { headers: headers() }).then(r => r.ok ? r.json() : null), fetch(`${baseUrl}/api/experience/reviews`, { headers: headers() }).then(r => r.ok ? r.json() : [])]).then(([nextDashboard, nextReviews]) => { setDashboard(nextDashboard); setReviews(nextReviews) }) }, [])
  const completeReview = async (lessonSlug: string) => { await fetch(`${baseUrl}/api/experience/reviews/${lessonSlug}/complete`, { method: 'POST', headers: headers() }); setReviews(current => current.filter(review => review.lessonSlug !== lessonSlug)); onSelectLesson(lessonSlug) }
  const total = course.modules.flatMap(module => module.lessons).length
  const completedCount = dashboard?.completedLessons ?? completed.filter(slug => course.modules.some(module => module.lessons.some(lesson => lesson.slug === slug))).length
  return <section className="mx-auto w-full max-w-5xl px-7 py-12 sm:px-12"><p className="text-[10px] font-bold tracking-[1.4px] text-[#b981ff]">LEARNING DASHBOARD</p><h1 className="mt-2 font-display text-5xl font-semibold tracking-[-2px] text-white">Make progress visible.</h1><div className="mt-8 grid gap-4 sm:grid-cols-3">{[['Lessons complete', `${completedCount} / ${dashboard?.totalLessons ?? total}`], ['Current streak', `${dashboard?.currentStreakDays ?? 0} days`], ['Projects', String(dashboard?.projectCount ?? 0)]].map(([label, value]) => <div key={label} className="rounded-xl border border-[#3b3052] bg-[#171321] p-5"><p className="text-xs text-[#bdb2cf]">{label}</p><strong className="mt-2 block font-display text-3xl text-white">{value}</strong></div>)}</div><div className="mt-8 rounded-xl border border-[#3b3052] bg-[#171321] p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold tracking-[1.3px] text-[#b981ff]">SPACED REVIEW</p><h2 className="mt-1 font-display text-2xl text-white">Keep concepts fresh</h2></div><Sparkles className="text-[#b981ff]"/></div>{reviews.length ? <div className="mt-5 grid gap-2">{reviews.map(review => <button key={review.lessonSlug} onClick={() => void completeReview(review.lessonSlug)} className="flex items-center justify-between rounded-lg bg-[#231c31] px-4 py-3 text-left text-sm text-[#eee6fa] hover:bg-[#312546]"><span>{review.title}</span><span className="text-xs text-[#cba9ff]">Review & reschedule →</span></button>)}</div> : <p className="mt-4 text-sm text-[#bdb2cf]">Complete lessons to build a personalized 1, 2, 4…30-day review queue.</p>}</div><AssessmentPanel course={course} onSelectLesson={onSelectLesson}/></section>
}

function AssessmentPanel({ course, onSelectLesson }: { course: Course; onSelectLesson: (slug: string) => void }) {
  const moduleId = course.id === 'python-web' ? 'python-foundations' : 'foundations'
  const [assessment, setAssessment] = useState<Assessment | null>(null)
  const [answers, setAnswers] = useState<Record<string, string>>({})
  const [result, setResult] = useState<AssessmentResult | null>(null)
  useEffect(() => { void fetch(`${baseUrl}/api/experience/assessments/${course.id}/${moduleId}`, { headers: headers() }).then(response => response.ok ? response.json() : null).then(setAssessment).catch(() => setAssessment(null)); setAnswers({}); setResult(null) }, [course.id, moduleId])
  const submit = async () => { if (!assessment) return; const response = await fetch(`${baseUrl}/api/experience/assessments/${course.id}/${moduleId}`, { method: 'POST', headers: headers(), body: JSON.stringify({ answers }) }); if (response.ok) setResult(await response.json()) }
  if (!assessment) return null
  return <div className="mt-8 rounded-xl border border-[#3b3052] bg-[#171321] p-6"><p className="text-[10px] font-bold tracking-[1.3px] text-[#b981ff]">MODULE CHECKPOINT</p><h2 className="mt-1 font-display text-2xl text-white">{assessment.title}</h2><p className="mt-2 text-sm text-[#bdb2cf]">Retrieve what you know. Results recommend targeted review instead of blocking your path.</p><div className="mt-5 grid gap-5">{assessment.questions.map(question => <fieldset key={question.id}><legend className="text-sm font-semibold text-[#eee6fa]">{question.prompt}</legend><div className="mt-2 grid gap-2">{question.choices.map(choice => <label key={choice} className="flex cursor-pointer items-center gap-2 rounded-lg bg-[#231c31] px-3 py-2 text-sm text-[#d9cdea]"><input type="radio" name={question.id} checked={answers[question.id] === choice} onChange={() => setAnswers(current => ({ ...current, [question.id]: choice }))}/>{choice}</label>)}</div></fieldset>)}</div><button disabled={Object.keys(answers).length !== assessment.questions.length} onClick={() => void submit()} className="mt-5 rounded-lg bg-[#8d4be2] px-4 py-3 text-sm font-bold text-white disabled:opacity-50">Check understanding</button>{result && <div className="mt-5 rounded-lg border border-[#584272] bg-[#21182f] p-4"><p className="text-sm text-white">{result.correctAnswers} / {result.totalQuestions} · {result.feedback}</p>{result.recommendedReviewLessonSlugs.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{result.recommendedReviewLessonSlugs.map(slug => <button key={slug} onClick={() => onSelectLesson(slug)} className="rounded bg-[#6d36ce42] px-2 py-1 text-xs text-[#d9c0ff]">Review lesson →</button>)}</div>}</div>}</div>
}

function ProjectStudio({ course, onNotice }: { course: Course; onNotice: (message: string) => void }) {
  const [templates, setTemplates] = useState<Template[]>(fallbackTemplates)
  const [project, setProject] = useState<Project | null>(null)
  const [activePath, setActivePath] = useState('')
  const activeFile = project?.files.find(file => file.path === activePath)
  useEffect(() => { void fetch(`${baseUrl}/api/experience/projects/templates`, { headers: headers() }).then(r => r.ok ? r.json() : fallbackTemplates).then(setTemplates).catch(() => setTemplates(fallbackTemplates)) }, [])
  const open = async (template: Template) => { const response = await fetch(`${baseUrl}/api/experience/projects/${template.id}`, { method: 'POST', headers: headers() }); const next = response.ok ? await response.json() as Project : { id: `local-${template.id}`, templateId: template.id, title: template.title, updatedAt: new Date().toISOString(), files: template.files }; setProject(next); setActivePath(next.files[0]?.path ?? ''); onNotice(response.ok ? 'Project workspace opened.' : 'Opened a local project workspace. Sign in to persist it.') }
  const update = (content: string) => { if (!project || !activeFile) return; setProject({ ...project, files: project.files.map(file => file.path === activePath ? { ...file, content } : file) }) }
  const save = async () => { if (!project || !activeFile || project.id.startsWith('local-')) return onNotice('Local workspace saved in this browser session. Sign in to persist it.'); const response = await fetch(`${baseUrl}/api/experience/projects/${project.id}/files/${activePath}`, { method: 'PUT', headers: headers(), body: JSON.stringify({ content: activeFile.content }) }); onNotice(response.ok ? 'File saved to your project.' : 'Could not save this file yet.') }
  const language = course.languageId === 'python' ? 'python' : 'csharp'
  return <section className="mx-auto w-full max-w-6xl px-7 py-12 sm:px-12"><p className="text-[10px] font-bold tracking-[1.4px] text-[#b981ff]">PORTFOLIO PROJECT STUDIO</p><h1 className="mt-2 font-display text-5xl font-semibold tracking-[-2px] text-white">Build work worth showing.</h1>{!project ? <div className="mt-8 grid gap-4 md:grid-cols-2">{templates.filter(template => template.language === course.languageId || (course.languageId === 'csharp' && template.language === 'csharp')).map(template => <button key={template.id} onClick={() => void open(template)} className="rounded-xl border border-[#3b3052] bg-[#171321] p-6 text-left hover:border-[#9b5cff]"><p className="text-[10px] font-bold tracking-[1.2px] text-[#b981ff]">{template.language.toUpperCase()}</p><h2 className="mt-2 font-display text-2xl text-white">{template.title}</h2><p className="mt-3 text-sm leading-relaxed text-[#bdb2cf]">{template.description}</p><span className="mt-5 inline-block text-xs font-bold text-[#cba9ff]">Open workspace →</span></button>)}</div> : <div className="mt-8 overflow-hidden rounded-xl border border-[#3b3052] bg-[#171321] md:grid md:grid-cols-[220px_1fr]"><aside className="border-b border-[#3b3052] p-4 md:border-b-0 md:border-r"><p className="text-xs font-bold text-white">{project.title}</p><div className="mt-4 grid gap-1">{project.files.map(file => <button key={file.path} onClick={() => setActivePath(file.path)} className={`rounded px-3 py-2 text-left text-xs ${file.path === activePath ? 'bg-[#6d36ce42] text-white' : 'text-[#bdb2cf] hover:bg-[#ffffff0b]'}`}>{file.path}</button>)}</div></aside><div><div className="flex items-center justify-between border-b border-[#3b3052] px-4 py-3"><span className="font-mono text-xs text-[#cba9ff]">{activePath}</span><button onClick={() => void save()} className="flex items-center gap-1 rounded bg-[#8d4be2] px-3 py-1.5 text-xs font-bold text-white"><Save size={13}/>Save</button></div><Editor height="420px" language={language} theme="vs-dark" value={activeFile?.content ?? ''} onChange={value => update(value ?? '')} options={{ automaticLayout: true, minimap: { enabled: false }, fontSize: 13 }}/></div></div>}</section>
}

function CoachPanel({ course, onSelectLesson }: { course: Course; onSelectLesson: (slug: string) => void }) {
  const firstLesson = useMemo(() => course.modules.flatMap(module => module.lessons)[0], [course])
  const [lessonSlug, setLessonSlug] = useState(firstLesson?.slug ?? '')
  const [message, setMessage] = useState('I am unsure how to begin this exercise.')
  const [guidance, setGuidance] = useState('')
  const [guardrails, setGuardrails] = useState<string[]>([])
  const ask = async () => { const response = await fetch(`${baseUrl}/api/experience/coach`, { method: 'POST', headers: headers(), body: JSON.stringify({ lessonSlug, message }) }); if (!response.ok) return setGuidance('The coach is unavailable. Remove secrets from your message and try again.'); const body = await response.json(); setGuidance(body.guidance); setGuardrails(body.guardrails) }
  return <section className="mx-auto w-full max-w-3xl px-7 py-12 sm:px-12"><p className="text-[10px] font-bold tracking-[1.4px] text-[#b981ff]">GUIDED COACH</p><h1 className="mt-2 font-display text-5xl font-semibold tracking-[-2px] text-white">Learn by thinking, not copying.</h1><p className="mt-4 text-sm leading-relaxed text-[#bdb2cf]">The coach gives a next reasoning step, protects secrets, and does not provide complete copy-paste solutions.</p><label className="mt-7 block text-xs font-semibold text-[#ded3ed]">Lesson<select value={lessonSlug} onChange={event => { setLessonSlug(event.target.value); onSelectLesson(event.target.value) }} className="mt-2 w-full rounded-lg border border-[#4b3a67] bg-[#171321] px-3 py-2 text-sm text-white">{course.modules.flatMap(module => module.lessons).map(lesson => <option key={lesson.slug} value={lesson.slug}>{lesson.title}</option>)}</select></label><label className="mt-4 block text-xs font-semibold text-[#ded3ed]">What are you stuck on?<textarea value={message} onChange={event => setMessage(event.target.value)} className="mt-2 min-h-32 w-full rounded-lg border border-[#4b3a67] bg-[#171321] p-3 text-sm text-white"/></label><button onClick={() => void ask()} className="mt-4 flex items-center gap-2 rounded-lg bg-[#8d4be2] px-4 py-3 text-sm font-bold text-white"><Send size={15}/>Ask for a next step</button>{guidance && <div className="mt-6 rounded-xl border border-[#584272] bg-[#171321] p-5"><p className="text-sm leading-relaxed text-[#eee6fa]">{guidance}</p><ul className="mt-4 list-disc space-y-1 pl-4 text-xs text-[#cba9ff]">{guardrails.map(item => <li key={item}>{item}</li>)}</ul></div>}</section>
}

function CommunityPanel({ course, onNotice }: { course: Course; onNotice: (message: string) => void }) {
  const [posts, setPosts] = useState<CommunityPost[]>([])
  const [title, setTitle] = useState('')
  const [body, setBody] = useState('')
  const [needsMentor, setNeedsMentor] = useState(false)
  const load = async () => { const response = await fetch(`${baseUrl}/api/experience/community/${course.id}`, { headers: headers() }); if (response.ok) setPosts(await response.json()) }
  useEffect(() => { void load() }, [course.id])
  const post = async () => { const response = await fetch(`${baseUrl}/api/experience/community/${course.id}`, { method: 'POST', headers: headers(), body: JSON.stringify({ title, body, needsMentor }) }); if (!response.ok) return onNotice('Sign in and provide a respectful title and message to post.'); setTitle(''); setBody(''); setNeedsMentor(false); await load(); onNotice('Your community post is live.') }
  return <section className="mx-auto w-full max-w-4xl px-7 py-12 sm:px-12"><p className="text-[10px] font-bold tracking-[1.4px] text-[#b981ff]">COMMUNITY & MENTORS</p><h1 className="mt-2 font-display text-5xl font-semibold tracking-[-2px] text-white">Learn with people.</h1><div className="mt-8 rounded-xl border border-[#3b3052] bg-[#171321] p-5"><input value={title} onChange={event => setTitle(event.target.value)} placeholder="Ask a focused question or share a project update" className="w-full rounded-lg border border-[#4b3a67] bg-[#0f0d17] px-3 py-2 text-sm text-white"/><textarea value={body} onChange={event => setBody(event.target.value)} placeholder="Include context, what you tried, and what you observed. Never share passwords, tokens, or private data." className="mt-3 min-h-28 w-full rounded-lg border border-[#4b3a67] bg-[#0f0d17] p-3 text-sm text-white"/><label className="mt-3 flex items-center gap-2 text-xs text-[#cba9ff]"><input checked={needsMentor} onChange={event => setNeedsMentor(event.target.checked)} type="checkbox"/>Request mentor input</label><button onClick={() => void post()} className="mt-4 flex items-center gap-2 rounded-lg bg-[#8d4be2] px-4 py-3 text-sm font-bold text-white"><MessageCircle size={15}/>Post to community</button></div><div className="mt-7 grid gap-3">{posts.length ? posts.map(post => <CommunityThread key={post.id} post={post} onPosted={load} onNotice={onNotice}/>) : <p className="rounded-xl border border-dashed border-[#4b3a67] p-6 text-sm text-[#bdb2cf]">Be the first to start a thoughtful conversation in this track.</p>}</div></section>
}

function CommunityThread({ post, onPosted, onNotice }: { post: CommunityPost; onPosted: () => Promise<void>; onNotice: (message: string) => void }) {
  const [reply, setReply] = useState('')
  const [open, setOpen] = useState(false)
  const submitReply = async () => { const response = await fetch(`${baseUrl}/api/experience/community/posts/${post.id}/replies`, { method: 'POST', headers: headers(), body: JSON.stringify({ body: reply }) }); if (!response.ok) return onNotice('Sign in and provide a respectful, specific reply.'); setReply(''); setOpen(false); await onPosted(); onNotice('Reply posted.') }
  return <article className="rounded-xl border border-[#3b3052] bg-[#171321] p-5"><div className="flex gap-3"><h2 className="flex-1 font-display text-xl text-white">{post.title}</h2>{post.needsMentor && <span className="rounded-full bg-[#8d4be22b] px-2 py-1 text-[10px] font-bold text-[#cba9ff]">MENTOR REQUEST</span>}</div><p className="mt-3 text-sm leading-relaxed text-[#ded3ed]">{post.body}</p>{post.replies.length > 0 && <div className="mt-4 grid gap-2 border-l border-[#5c477b] pl-3">{post.replies.map(reply => <p key={reply.id} className="text-sm text-[#cfc2df]"><span className={reply.isMentor ? 'mr-2 text-[10px] font-bold tracking-[1px] text-[#cba9ff]' : 'hidden'}>MENTOR</span>{reply.body}</p>)}</div>}<button onClick={() => setOpen(value => !value)} className="mt-4 text-xs font-bold text-[#cba9ff]">{open ? 'Cancel reply' : `${post.replies.length} replies · Reply`}</button>{open && <div className="mt-3"><textarea value={reply} onChange={event => setReply(event.target.value)} placeholder="Add a constructive reply. Never share passwords, tokens, or private data." className="min-h-24 w-full rounded-lg border border-[#4b3a67] bg-[#0f0d17] p-3 text-sm text-white"/><button onClick={() => void submitReply()} className="mt-2 rounded bg-[#6f36c8] px-3 py-2 text-xs font-bold text-white">Reply</button></div>}</article>
}
